In [ ]:
!pip install --upgrade --no-cache-dir git+https://github.com/rongardF/tvdatafeed.git
# !pip install tvdatafeed
!pip install yfinance --upgrade --no-cache-dir
!pip install ta

# import libraries
import yfinance as yf # for financial data
import numpy as np # for scientific computing
import pandas as pd # for dealing with data frames
import seaborn as sns # for creating charts
import scipy.stats as scs # for technical computing (pronounced [saɪpa])
import statsmodels.api as sm # for providinga complement to scipy for statistical computations
import statsmodels.tsa.api as smt # for providinga complement to scipy for statistical computations
import matplotlib.pyplot as plt # for creating charts

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import datetime
from dateutil.relativedelta import relativedelta

import yfinance as yf
from google.colab import files
import plotly.express as px
import plotly.io as pio
import datetime
from google.colab import files
import pandas as pd
import ta as ta
from ta.utils import dropna
from ta.volatility import BollingerBands
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta import add_all_ta_features
from ta.utils import dropna
from ta.trend import ADXIndicator
from ta.volatility import AverageTrueRange
from ta.volume import on_balance_volume

from datetime import datetime
import time
from tvDatafeed import TvDatafeed, Interval

Collecting git+https://github.com/rongardF/tvdatafeed.git
  Cloning https://github.com/rongardF/tvdatafeed.git to /tmp/pip-req-build-3ewamrk0
  Running command git clone --filter=blob:none --quiet https://github.com/rongardF/tvdatafeed.git /tmp/pip-req-build-3ewamrk0
  Resolved https://github.com/rongardF/tvdatafeed.git to commit e6f6aaa7de439ac6e454d9b26d2760ded8dc4923
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tvdatafeed==2.1.0) (75.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from tvdatafeed==2.1.0) (2.2.2)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.12/dist-packages (from tvdatafeed==2.1.0) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from tvdatafeed==2.1.0) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->tvdatafeed==2.1.0) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->tvdatafeed==2.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->tvdatafeed==2.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->tvdatafeed==2.1.0) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->tvdatafeed==2.1.0) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->tvdatafeed==2.1.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->tvdatafeed==2.1.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->tvdatafeed==2.1.0) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->tvdatafeed==2.1.0) (1.17.0)
Building wheels for collected packages: tvdatafeed
  Building wheel for tvdatafeed (setup.py) ... done
  Created wheel for tvdatafeed: filename=tvdatafeed-2.1.0-py3-none-any.whl size=17532 sha256=3e490c684c5798f5b736ca821d00220549ac6fbaa3d3ad23919d30376fdc4685
  Stored in directory: /tmp/pip-ephem-wheel-cache-8d3cosej/wheels/88/4b/d2/ce1c8432f33d4ab6d148d6ece31055eadadda0a5dd9fb76366
Successfully built tvdatafeed
Installing collected packages: tvdatafeed
Successfully installed tvdatafeed-2.1.0
Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Collecting yfinance
  Downloading yfinance-1.5.2-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.2.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.15 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (2026.6.17)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.15->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.5.2-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.1/144.1 kB 8.9 MB/s eta 0:00:00
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.66
    Uninstalling yfinance-0.2.66:
      Successfully uninstalled yfinance-0.2.66
Successfully installed yfinance-1.5.2
Collecting ta
  Downloading ta-0.11.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from ta) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ta) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ta) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ta) (1.17.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.11.0-py3-none-any.whl size=29412 sha256=9e5eb22ae9a646118ea82a1a55ac947bd79ac43042b97350d10ad8d822e7d5a9
  Stored in directory: /root/.cache/pip/wheels/5c/a1/5f/c6b85a7d9452057be4ce68a8e45d77ba34234a6d46581777c6
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.11.0

In [ ]:
# om pickle import TRUE
date_now = datetime.now()
date_formated = date_now.strftime("%Y-%m-%d")
date_csv = date_now.strftime("%Y%m%d")
date_lastyear = datetime.now() - relativedelta(years=1)
st_date_formated = date_lastyear.strftime("%Y-%m-%d")

csvfile_intday = 'Result' + date_csv +'interday' + '.csv'
csvfile = 'Stocklist_' + date_csv + '.csv'
csvfile25_3 = 'Break25_OverVolMAx3' + date_csv + '.csv'



# add table 1st time
# def addtable1info(Stock_df):
#     try:
#         lv_syml_info = yf.Ticker(A)
#         info = lv_syml_info.info
#         if not info:
#             print(f"Ticker {A} ไม่สามารถดึงข้อมูลได้")
#             return
#         marketCap = info.get('marketCap', None)
#         Stock_df['Mcap'] = marketCap
#         pe = info.get('trailingPE', None)
#         Stock_df['PE'] = pe
#         payoutRatio = info.get('payoutRatio', None)
#         Stock_df['payoutRatio'] = payoutRatio
#         dividendYield = info.get('dividendYield', None)
#         Stock_df['dividendYield'] = dividendYield
#         floatShares = info.get('floatShares', None)
#         Stock_df['floatShares'] = floatShares
#         sharesOutstanding = info.get('sharesOutstanding', None)
#         Stock_df['sharesOutstanding'] = sharesOutstanding
#         if floatShares and sharesOutstanding:
#             Stock_df['freefloatShares%'] = (floatShares / sharesOutstanding) * 100
#         else:
#             Stock_df['freefloatShares%'] = None
#         enterpriseValue = info.get('enterpriseValue', None)
#         Stock_df['enterpriseValue'] = enterpriseValue
#     except Exception as e:
#         print(f"Error in addtable1info: {e}")

def addtable1info(Stock_df):
  # Plan A: read fundamentals from prebuilt FUND dict (TradingView) instead of per-symbol yf.Ticker().info
  _info = FUND.get(lv_syml, {}) if 'FUND' in globals() else {}
  Stock_df['Mcap'] = _info.get('marketCap', None)
  Stock_df['PE'] = _info.get('trailingPE', None)
  Stock_df['payoutRatio'] = _info.get('payoutRatio', None)
  Stock_df['dividendYield'] = _info.get('dividendYield', None)  # fraction (TV % / 100)
  Stock_df['floatShares'] = _info.get('floatShares', None)
  Stock_df['sharesOutstanding'] = _info.get('sharesOutstanding', None)
  Stock_df['freefloatShares%'] = (Stock_df['floatShares']/Stock_df['sharesOutstanding'])*100
  Stock_df['enterpriseValue'] = _info.get('enterpriseValue', None)

def addtable1(Stock_df):
  Stock_df['Name'] = lv_syml
  Stock_df['datetime_'] = Stock_df.index.date
  Stock_df['open-1'] = Stock_df['open'].shift(1)
  Stock_df['high-1'] = Stock_df['high'].shift(1)
  Stock_df['low-1'] = Stock_df['low'].shift(1)
  Stock_df['close-1'] = Stock_df['close'].shift(1)
  Stock_df['close-2'] = Stock_df['close'].shift(2)
  Stock_df['close-5'] = Stock_df['close'].shift(5)
  Stock_df['close-6'] = Stock_df['close'].shift(6)
  Stock_df['close-10'] = Stock_df['close'].shift(10)
  Stock_df['close-11'] = Stock_df['close'].shift(11)
  Stock_df['close-20'] = Stock_df['close'].shift(20)
  Stock_df['close-60'] = Stock_df['close'].shift(60)
  Stock_df['close-75'] = Stock_df['close'].shift(75)
  Stock_df['close-76'] = Stock_df['close'].shift(76)
  Stock_df['close-240'] = Stock_df['close'].shift(240)
  Stock_df['Values'] = Stock_df['volume'] * Stock_df['close']
  Stock_df['retune_chg'] =  100 * ((Stock_df['close']-Stock_df['close-1'])/Stock_df['close-1'])
  Stock_df['retune_log'] =  100 * (np.log(Stock_df['close']) - np.log(Stock_df['close'].shift(1)))
  Stock_df['retune_chg-1'] = Stock_df['retune_chg'].shift(1)
  Stock_df['retune_chg-2'] = Stock_df['retune_chg'].shift(2)
  Stock_df['retune_chg-5'] = Stock_df['retune_chg'].shift(5)
  Stock_df['retune_chg-10'] = Stock_df['retune_chg'].shift(10)
  Stock_df['retune_chg-12'] = Stock_df['retune_chg'].shift(12)
  Stock_df['retune_chg-20'] = Stock_df['retune_chg'].shift(20)
  Stock_df['retune_chg-26'] = Stock_df['retune_chg'].shift(26)
  Stock_df['retune_chg-40'] = Stock_df['retune_chg'].shift(40)
  Stock_df['retune_chg-60'] = Stock_df['retune_chg'].shift(60)
  Stock_df['retune_chg-75'] = Stock_df['retune_chg'].shift(75)
  Stock_df['OpenHigherlastclose'] = Stock_df['open'] > Stock_df['close-1']

  Stock_df['Uper'] = Stock_df['low'] > Stock_df['close-1']
  Stock_df['Open Gap'] = Stock_df['low'] > Stock_df['high-1']
  Stock_df['Jump'] = (Stock_df['OpenHigherlastclose'] == True) & (Stock_df['retune_chg'] > 1.5)
  Stock_df['Jump Gap'] = (Stock_df['OpenHigherlastclose'] == True) & (Stock_df['Open Gap'] == True) &(Stock_df['retune_chg'] > 1.5)
  Stock_df['Jump low'] = Stock_df['high'] < Stock_df['low-1']
  Stock_df['Jump up'] = Stock_df['low'] > Stock_df['high-1']
  Stock_df['Jump low-1'] = Stock_df['Jump low'].shift(1)
  Stock_df['Jump up-1'] = Stock_df['Jump up'].shift(1)
  Stock_df['Jump low-2'] = Stock_df['Jump low'].shift(2)
  Stock_df['Jump up-2'] = Stock_df['Jump up'].shift(2)


  Stock_df['close_st'] = Stock_df['close'].iloc[0]
  # Stock_df['close_st_manual'] = Stock_df['close'].iloc[-13]
  # Stock_df['close_st_manual'] = Stock_df.loc[datestartst_manual, 'close']
  if datestartst_manual in Stock_df.index:
    Stock_df['close_st_manual'] = Stock_df.loc[datestartst_manual, 'close']
  else:
    Stock_df['close_st_manual'] = 0

  Stock_df['return_chg_st'] =  100 * ((Stock_df['close']-Stock_df['close_st'])/Stock_df['close_st'])
  Stock_df['return_log_st'] =  100 * (np.log(Stock_df['close']) - np.log(Stock_df['close_st']))
  Stock_df['return_chg_manual'] = np.where(Stock_df['close_st_manual'] == 0, 1,100 * ((Stock_df['close']-Stock_df['close_st_manual'])/Stock_df['close_st_manual']))
  Stock_df['return_chg_week'] =  100 * ((Stock_df['close']-Stock_df['close-5'])/Stock_df['close-5'])
  Stock_df['return_chg_month'] =  100 * ((Stock_df['close']-Stock_df['close-20'])/Stock_df['close-20'])
  Stock_df['return_chg_q'] =  100 * ((Stock_df['close']-Stock_df['close-60'])/Stock_df['close-60'])
  Stock_df['return_chg_y'] =  100 * ((Stock_df['close']-Stock_df['close-240'])/Stock_df['close-240'])
    #หาytd
  Stock_df['return_chg_ytd'] = 100 * ((Stock_df['close'] - Stock_df['close'].iloc[-YTDx]) / Stock_df['close'].iloc[-YTDx])


def addtablecandlestick(Stock_df):
  Stock_df['candlerange'] = Stock_df['high'] - Stock_df['low']
  Stock_df['candlerangebody'] = Stock_df['close']  - Stock_df['open']
  Stock_df['candletaiLowGreen'] =  Stock_df['open'] - Stock_df['low']
  Stock_df['candletailLowRed'] = Stock_df['close'] - Stock_df['low']
  Stock_df['candletaiupRed'] =  Stock_df['high'] - Stock_df['open']
  Stock_df['candletaiupGreen'] =  Stock_df['high'] - Stock_df['close']



  Stock_df['%candleClose'] = ((Stock_df['close']-Stock_df['low'])/Stock_df['candlerange'])*100
  Stock_df['%candleClose-1'] = Stock_df['%candleClose'].shift(1)
  Stock_df['%candleClose-2'] = Stock_df['%candleClose'].shift(2)
  Stock_df['%candleClose-5'] = Stock_df['%candleClose'].shift(5)
  Stock_df['%candleClose-10'] = Stock_df['%candleClose'].shift(10)

  Stock_df['%candleBody'] = ((Stock_df['close']-Stock_df['open'])/Stock_df['candlerange'])*100
  Stock_df['%candleBody-1'] = Stock_df['%candleBody'].shift(1)
  Stock_df['%candleBody-2'] = Stock_df['%candleBody'].shift(2)
  Stock_df['%candleBody-5'] = Stock_df['%candleBody'].shift(5)
  Stock_df['%candleBody-10'] = Stock_df['%candleBody'].shift(10)

  Stock_df['%candleOpen'] = ((Stock_df['open']-Stock_df['low'])/Stock_df['candlerange'])*100
  Stock_df['%candleOpen-1'] = Stock_df['%candleOpen'].shift(1)
  Stock_df['%candleOpen-2'] = Stock_df['%candleOpen'].shift(2)
  Stock_df['%candleOpen-5'] = Stock_df['%candleOpen'].shift(5)
  Stock_df['%candleOpen-10'] = Stock_df['%candleOpen'].shift(10)


  Stock_df['candleOHLC'] = (Stock_df['close']==Stock_df['low'])&(Stock_df['close']==Stock_df['open'])&(Stock_df['close']==Stock_df['high'])
  Stock_df['candleHC'] = (Stock_df['close']!=Stock_df['open'])&(Stock_df['close']==Stock_df['high'])
  Stock_df['candleLC'] = (Stock_df['close']==Stock_df['low'])&(Stock_df['close']!=Stock_df['open'])
  Stock_df['candleOHC'] = (Stock_df['close']!=Stock_df['low'])&(Stock_df['close']==Stock_df['open'])&(Stock_df['close']==Stock_df['high'])
  Stock_df['candleOLC'] = (Stock_df['close']==Stock_df['low'])&(Stock_df['close']==Stock_df['open'])&(Stock_df['close']!=Stock_df['high'])

  Stock_df['candleDoji'] = (Stock_df['close']==Stock_df['open'])
  Stock_df['candleDoji-1'] = Stock_df['candleDoji'].shift(1)
  Stock_df['candleDoji-2'] = Stock_df['candleDoji'].shift(2)
  Stock_df['candleDoji-5'] = Stock_df['candleDoji'].shift(5)
  Stock_df['candleDoji-10'] = Stock_df['candleDoji'].shift(10)
  Stock_df['candleDoji_Drajonfly'] = ((Stock_df['close']==Stock_df['open'])&(Stock_df['close']==Stock_df['high']))
  Stock_df['candleDoji_Gravstone'] = ((Stock_df['close']==Stock_df['open'])&(Stock_df['close']==Stock_df['low']))
  Stock_df['candleDoji_4price'] = (Stock_df['close']==Stock_df['low'])&(Stock_df['close']==Stock_df['open'])&(Stock_df['close']==Stock_df['high'])

  Stock_df['candle_Hammer_G'] = (Stock_df['close']>Stock_df['open'])&(Stock_df['%candleClose']>60)&(Stock_df['%candleOpen']>60)
  Stock_df['candle_Hammer_G-1'] = Stock_df['candle_Hammer_G'].shift(1)
  Stock_df['candle_Hammer_G-2'] = Stock_df['candle_Hammer_G'].shift(2)
  Stock_df['candle_Hammer_G-5'] = Stock_df['candle_Hammer_G'].shift(5)
  Stock_df['candle_Hammer_R'] = (Stock_df['open']>Stock_df['close'])&(Stock_df['%candleOpen']>60)&(Stock_df['%candleClose']>60)
  Stock_df['candle_Hammer_R-1'] = Stock_df['candle_Hammer_R'].shift(1)
  Stock_df['candle_Hammer_R-2'] = Stock_df['candle_Hammer_R'].shift(2)
  Stock_df['candle_Hammer_R-5'] = Stock_df['candle_Hammer_R'].shift(5)
  Stock_df['candle_ReHammer_G'] = (Stock_df['close']>Stock_df['open'])&(Stock_df['%candleClose']<40)&(Stock_df['%candleOpen']<40)
  Stock_df['candle_ReHammer_G-1'] = Stock_df['candle_ReHammer_G'].shift(1)
  Stock_df['candle_ReHammer_G-2'] = Stock_df['candle_ReHammer_G'].shift(2)
  Stock_df['candle_ReHammer_G-5'] = Stock_df['candle_ReHammer_G'].shift(5)
  Stock_df['candle_ReHammer_R'] = (Stock_df['open']>Stock_df['close'])&(Stock_df['%candleOpen']<40)&(Stock_df['%candleClose']<40)
  Stock_df['candle_ReHammer_R-1'] = Stock_df['candle_ReHammer_R'].shift(1)
  Stock_df['candle_ReHammer_R-2'] = Stock_df['candle_ReHammer_R'].shift(2)
  Stock_df['candle_Bullish_engulfing'] = ((Stock_df['%candleOpen-1'] > Stock_df['%candleClose-1'])&(Stock_df['open']<Stock_df['close-1'])&(Stock_df['close']>Stock_df['open-1']))
  Stock_df['candle_Bullish_engulfing-1'] = Stock_df['candle_Bullish_engulfing'].shift(1)
  Stock_df['candle_Bullish_engulfing-2'] = Stock_df['candle_Bullish_engulfing'].shift(2)
  Stock_df['candle_Bearish_engulfing'] = ((Stock_df['%candleOpen-1'] < Stock_df['%candleClose-1'])&(Stock_df['open']>Stock_df['close-1'])&(Stock_df['close']<Stock_df['open-1']))
  Stock_df['candle_Bearish_engulfing-1'] = Stock_df['candle_Bearish_engulfing'].shift(1)
  Stock_df['candle_Bearish_engulfing-2'] = Stock_df['candle_Bearish_engulfing'].shift(2)
  Stock_df['candle_Bullish_Harami'] = ((Stock_df['%candleOpen-1'] < Stock_df['%candleClose-1'])&(Stock_df['high']<Stock_df['high-1'])&(Stock_df['low']>Stock_df['low']))
  Stock_df['candle_Bullish_Harami-1'] = Stock_df['candle_Bullish_Harami'].shift(1)
  Stock_df['candle_Bullish_Harami-2'] = Stock_df['candle_Bullish_Harami'].shift(2)
  Stock_df['candle_Bearish_Harami'] = ((Stock_df['%candleOpen-1'] > Stock_df['%candleClose-1'])&(Stock_df['open']>Stock_df['close-1'])&(Stock_df['low']>Stock_df['low-1']))
  Stock_df['candle_Bearish_Harami-1'] = Stock_df['candle_Bearish_Harami'].shift(1)
  Stock_df['candle_Bearish_Harami-2'] = Stock_df['candle_Bearish_Harami'].shift(2)






  # if Stock_df['close']>Stock_df['open']:
  #   Stock_df['candleRYG'] = 'G'
  #   Stock_df['%candle_tailLow'] = ((Stock_df['open'] - Stock_df['low'] )/Stock_df['candlerange'])*100
  #   Stock_df['%candle_tailup'] = ((Stock_df['high'] - Stock_df['close'])/Stock_df['candlerange'])*100
  #   Stock_df['%candlerangebody'] = ((Stock_df['close']  - Stock_df['open'])/Stock_df['candlerange'])*100

  # elif Stock_df['close']<Stock_df['open']:
  #   Stock_df['candleRYG'] = 'R'
  #   Stock_df['%candle_tailLow'] = ((Stock_df['close'] - Stock_df['low'] )/Stock_df['candlerange'])*100
  #   Stock_df['%candle_tailup'] = ((Stock_df['high'] - Stock_df['open'])/Stock_df['candlerange'])*100
  #   Stock_df['%candlerangebody'] = ((Stock_df['open'] - Stock_df['close'])/Stock_df['candlerange'])*100
  # else:
  #   Stock_df['candleRYG'] = 'Y'
  #   Stock_df['%candle_tailLow'] = ((Stock_df['close'] - Stock_df['low'] )/Stock_df['candlerange'])*100
  #   Stock_df['%candle_tailup'] = ((Stock_df['high'] - Stock_df['close'])/Stock_df['candlerange'])*100
  #   Stock_df['%candlerangebody'] = '0'


def addtablehikenashi(Stock_df):

  # คำนวณ Heikin Ashi
  Stock_df['HA_Close'] = (Stock_df['open'] + Stock_df['high'] + Stock_df['low'] + Stock_df['close']) / 4

  # สร้างคอลัมน์ HA_Open (ใช้ค่าเริ่มต้น)
  for i in range(Stock_df.shape[0]):
    if i > 0:
      Stock_df.loc[Stock_df.index[i],'HA_Open'] = (Stock_df['HA_Open'][i-1] + Stock_df['HA_Close'][i-1])/2
    elif i == 0:
      Stock_df.loc[Stock_df.index[0],'HA_Open'] = (Stock_df['open'][0] + Stock_df['close'][0])/2

  # คำนวณคอลัมน์ HA_High และ HA_Low
  Stock_df['HA_High'] = Stock_df[['high', 'HA_Open', 'HA_Close']].max(axis=1)
  Stock_df['HA_Low'] = Stock_df[['low', 'HA_Open', 'HA_Close']].min(axis=1)

  Stock_df['HA_Close-1'] = Stock_df['HA_Close'].shift(1)
  Stock_df['HA_Open-1'] = Stock_df['HA_Open'].shift(1)
  Stock_df['HA_High-1'] = Stock_df['HA_High'].shift(1)
  Stock_df['HA_Low-1'] = Stock_df['HA_Low'].shift(1)
  Stock_df['HA_Close_EMA10'] = Stock_df['HA_Close'].ewm(span=3).mean()
  Stock_df['HA_Close_EMA10-1'] = Stock_df['HA_Close_EMA10'].shift(1)
  Stock_df['HA_Close-2'] = Stock_df['HA_Close'].shift(2)
  Stock_df['HA_Open-2'] = Stock_df['HA_Open'].shift(2)
  Stock_df['HA_High-2'] = Stock_df['HA_High'].shift(2)
  Stock_df['HA_Low-2'] = Stock_df['HA_Low'].shift(2)
  Stock_df['HA_Close_EMA10-1'] = Stock_df['HA_Close_EMA10'].shift(2)



def addtableMA(Stock_df):
  Stock_df['MA05'] = Stock_df['close'].rolling(window=5).mean()
  Stock_df['MA10'] = Stock_df['close'].rolling(window=10).mean()
  Stock_df['MA15'] = Stock_df['close'].rolling(window=15).mean()
  Stock_df['MA20'] = Stock_df['close'].rolling(window=20).mean()
  Stock_df['MA25'] = Stock_df['close'].rolling(window=25).mean()
  Stock_df['MA30'] = Stock_df['close'].rolling(window=30).mean()
  Stock_df['MA40'] = Stock_df['close'].rolling(window=40).mean()
  Stock_df['MA60'] = Stock_df['close'].rolling(window=60).mean()
  Stock_df['MA100'] = Stock_df['close'].rolling(window=100).mean()
  Stock_df['MA120'] = Stock_df['close'].rolling(window=120).mean()
  Stock_df['MA200'] = Stock_df['close'].rolling(window=200).mean()
  Stock_df['MA240'] = Stock_df['close'].rolling(window=240).mean()
  Stock_df['MA500'] = Stock_df['close'].rolling(window=500).mean()
  Stock_df['std MA05'] = Stock_df['close'].rolling(window=5).std()
  Stock_df['std MA10'] = Stock_df['close'].rolling(window=10).std()
  Stock_df['std MA15'] = Stock_df['close'].rolling(window=15).std()
  Stock_df['std MA20'] = Stock_df['close'].rolling(window=20).std()
  Stock_df['std MA25'] = Stock_df['close'].rolling(window=25).std()
  Stock_df['std MA30'] = Stock_df['close'].rolling(window=30).std()
  Stock_df['std MA40'] = Stock_df['close'].rolling(window=40).std()
  Stock_df['std MA60'] = Stock_df['close'].rolling(window=60).std()
  Stock_df['std MA100'] = Stock_df['close'].rolling(window=100).std()
  Stock_df['std MA120'] = Stock_df['close'].rolling(window=120).std()
  Stock_df['std MA200'] = Stock_df['close'].rolling(window=200).std()
  Stock_df['std MA240'] = Stock_df['close'].rolling(window=240).std()
  Stock_df['std MA500'] = Stock_df['close'].rolling(window=500).std()
  Stock_df['Stock_dfGap%_c_05']=(Stock_df['close']-Stock_df['MA05'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_10']=(Stock_df['close']-Stock_df['MA10'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_15']=(Stock_df['close']-Stock_df['MA15'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_20']=(Stock_df['close']-Stock_df['MA20'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_25']=(Stock_df['close']-Stock_df['MA25'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_30']=(Stock_df['close']-Stock_df['MA30'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_40']=(Stock_df['close']-Stock_df['MA40'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_60']=(Stock_df['close']-Stock_df['MA60'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_100']=(Stock_df['close']-Stock_df['MA100'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_120']=(Stock_df['close']-Stock_df['MA120'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_200']=(Stock_df['close']-Stock_df['MA200'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_240']=(Stock_df['close']-Stock_df['MA240'])/Stock_df['close']*100
  Stock_df['Stock_dfGap%_c_500']=(Stock_df['close']-Stock_df['MA500'])/Stock_df['close']*100
  Stock_df['MA/SD_05'] =Stock_df['std MA05'] /Stock_df['MA05'] *100
  Stock_df['MA/SD_10'] =Stock_df['std MA10'] /Stock_df['MA10'] *100
  Stock_df['MA/SD_15'] =Stock_df['std MA15'] /Stock_df['MA15'] *100
  Stock_df['MA/SD_20'] =Stock_df['std MA20'] /Stock_df['MA20'] *100
  Stock_df['MA/SD_25'] =Stock_df['std MA25'] /Stock_df['MA25'] *100
  Stock_df['MA/SD_30'] =Stock_df['std MA30'] /Stock_df['MA30'] *100
  Stock_df['MA/SD_40'] =Stock_df['std MA40'] /Stock_df['MA40'] *100
  Stock_df['MA/SD_60'] =Stock_df['std MA60'] /Stock_df['MA60'] *100
  Stock_df['MA/SD_100'] =Stock_df['std MA100'] /Stock_df['MA100'] *100
  Stock_df['MA/SD_120'] =Stock_df['std MA120'] /Stock_df['MA120'] *100
  Stock_df['MA/SD_200'] =Stock_df['std MA200'] /Stock_df['MA200'] *100
  Stock_df['MA/SD_240'] =Stock_df['std MA240'] /Stock_df['MA240'] *100
  Stock_df['MA/SD_500'] =Stock_df['std MA500'] /Stock_df['MA500'] *100



def addtableVol(Stock_df):

  Stock_df['VolMA05'] = Stock_df['volume'].rolling(window=5).mean()
  Stock_df['VolMA10'] = Stock_df['volume'].rolling(window=10).mean()
  Stock_df['VolMA25'] = Stock_df['volume'].rolling(window=25).mean()
  Stock_df['VolMA60'] = Stock_df['volume'].rolling(window=60).mean()
  Stock_df['VolMA100'] = Stock_df['volume'].rolling(window=100).mean()
  Stock_df['VolMA120'] = Stock_df['volume'].rolling(window=120).mean()
  Stock_df['VolMA200'] = Stock_df['volume'].rolling(window=200).mean()
  Stock_df['VolMA240'] = Stock_df['volume'].rolling(window=240).mean()
  Stock_df['VolMA600'] = Stock_df['volume'].rolling(window=600).mean()
  Stock_df['VolMax05'] = Stock_df['volume'].rolling(window=5).max()
  Stock_df['VolMax10'] = Stock_df['volume'].rolling(window=10).max()
  Stock_df['VolMax25'] = Stock_df['volume'].rolling(window=25).max()
  Stock_df['VolMax60'] = Stock_df['volume'].rolling(window=60).max()
  Stock_df['VolMax100'] = Stock_df['volume'].rolling(window=100).max()
  Stock_df['VolMax120'] = Stock_df['volume'].rolling(window=120).max()
  Stock_df['VolMax200'] = Stock_df['volume'].rolling(window=200).max()
  Stock_df['VolMax240'] = Stock_df['volume'].rolling(window=240).max()
  Stock_df['VolMax600'] = Stock_df['volume'].rolling(window=600).max()
  Stock_df['volume-1'] = Stock_df['volume'].shift(1)
  Stock_df['VolMax-1_05'] = Stock_df['VolMax05'].shift(1)
  Stock_df['VolMax-1_10'] = Stock_df['VolMax10'].shift(1)
  Stock_df['VolMax-1_25'] = Stock_df['VolMax25'].shift(1)
  Stock_df['VolMax-1_60'] = Stock_df['VolMax60'].shift(1)
  Stock_df['VolMax-1_100'] = Stock_df['VolMax100'].shift(1)
  Stock_df['VolMax-1_120'] = Stock_df['VolMax120'].shift(1)
  Stock_df['VolMax-1_200'] = Stock_df['VolMax200'].shift(1)
  Stock_df['VolMax-1_240'] = Stock_df['VolMax240'].shift(1)
  Stock_df['VolMax-1_600'] = Stock_df['VolMax600'].shift(1)
  Stock_df['volume-2'] = Stock_df['volume'].shift(2)
  Stock_df['VolMax-2_25'] = Stock_df['VolMax25'].shift(2)
  Stock_df['VolMax-2_60'] = Stock_df['VolMax60'].shift(2)
  Stock_df['VolMax-2_100'] = Stock_df['VolMax100'].shift(2)
  Stock_df['VolMax-2_120'] = Stock_df['VolMax120'].shift(2)
  Stock_df['VolMax-2_200'] = Stock_df['VolMax200'].shift(2)
  Stock_df['VolMax-2_240'] = Stock_df['VolMax240'].shift(2)
  Stock_df['VolMax-2_600'] = Stock_df['VolMax600'].shift(2)
  Stock_df['volume-3'] = Stock_df['volume'].shift(3)
  Stock_df['VolMax-3_25'] = Stock_df['VolMax25'].shift(3)
  Stock_df['VolMax-3_60'] = Stock_df['VolMax60'].shift(3)
  Stock_df['VolMax-3_100'] = Stock_df['VolMax100'].shift(3)
  Stock_df['VolMax-3_200'] = Stock_df['VolMax200'].shift(3)
  Stock_df['VolMax-3_600'] = Stock_df['VolMax600'].shift(3)
  Stock_df['volume-5'] = Stock_df['volume'].shift(5)
  Stock_df['VolMax-5_25'] = Stock_df['VolMax25'].shift(5)
  Stock_df['VolMax-5_60'] = Stock_df['VolMax60'].shift(5)
  Stock_df['VolMax-5_100'] = Stock_df['VolMax100'].shift(5)
  Stock_df['VolMax-5_200'] = Stock_df['VolMax200'].shift(5)
  Stock_df['VolMax-5_600'] = Stock_df['VolMax600'].shift(5)
  Stock_df['volume-10'] = Stock_df['volume'].shift(10)
  Stock_df['VolMax-10_25'] = Stock_df['VolMax25'].shift(10)
  Stock_df['VolMax-10_60'] = Stock_df['VolMax60'].shift(10)
  Stock_df['VolMax-10_100'] = Stock_df['VolMax100'].shift(10)
  Stock_df['VolMax-10_200'] = Stock_df['VolMax200'].shift(10)
  Stock_df['VolMax-10_600'] = Stock_df['VolMax600'].shift(10)



def addtablereturn(Stock_df):
  Stock_df['retune_chg_ma05']  = Stock_df['retune_chg'].rolling(window=5).mean()
  Stock_df['retune_chg_ma05std']  = Stock_df['retune_chg'].rolling(window=5).std()
  Stock_df['retune_chg_ma10']  = Stock_df['retune_chg'].rolling(window=10).mean()
  Stock_df['retune_chg_ma10std']  = Stock_df['retune_chg'].rolling(window=10).std()
  Stock_df['retune_chg_ma15']  = Stock_df['retune_chg'].rolling(window=15).mean()
  Stock_df['retune_chg_ma15std']  = Stock_df['retune_chg'].rolling(window=15).std()
  Stock_df['retune_chg_ma20']  = Stock_df['retune_chg'].rolling(window=20).mean()
  Stock_df['retune_chg_ma25']  = Stock_df['retune_chg'].rolling(window=25).mean()
  Stock_df['retune_chg_ma25std']  = Stock_df['retune_chg'].rolling(window=25).std()
  Stock_df['retune_chg_ma60']  = Stock_df['retune_chg'].rolling(window=60).mean()
  Stock_df['retune_chg_ma60std']  = Stock_df['retune_chg'].rolling(window=60).std()
  Stock_df['retune_chg_ma100']  = Stock_df['retune_chg'].rolling(window=100).mean()
  Stock_df['retune_chg_ma100std']  = Stock_df['retune_chg'].rolling(window=100).std()
  Stock_df['retune_chg_ma200']  = Stock_df['retune_chg'].rolling(window=200).mean()
  Stock_df['retune_chg_ma200std']  = Stock_df['retune_chg'].rolling(window=200).std()
  Stock_df['retune_chg_ma240']  = Stock_df['retune_chg'].rolling(window=240).mean()
  Stock_df['retune_chg_ma240std']  = Stock_df['retune_chg'].rolling(window=240).std()
  Stock_df['retune_chg_ma600']  = Stock_df['retune_chg'].rolling(window=600).mean()
  Stock_df['retune_chg_ma600std']  = Stock_df['retune_chg'].rolling(window=600).std()
  Stock_df['retune_chg_ma05<10<25']  = (Stock_df['retune_chg_ma05'] < Stock_df['retune_chg_ma10']) & (Stock_df['retune_chg_ma10'] < Stock_df['retune_chg_ma25'])
  Stock_df['retune_chg_ma05<10<25-1']  = Stock_df['retune_chg_ma05<10<25'].shift(1)
  Stock_df['retune_chg_ma05<10<25std'] = (Stock_df['retune_chg_ma05std'] < Stock_df['retune_chg_ma10std']) & (Stock_df['retune_chg_ma10std'] < Stock_df['retune_chg_ma25std'])&(Stock_df['retune_chg_ma25']>0)
  Stock_df['retune_chg_ma05<10<25std-1']  = Stock_df['retune_chg_ma05<10<25std'].shift(1)
  Stock_df['retune_chg_ma25>0']= (Stock_df['retune_chg_ma25']>0)#ใชกำกับ ธง ใหไม่เปน ขาลง




def addtableVal(Stock_df):
  Stock_df['ValMA25'] =  Stock_df['VolMA25'] * Stock_df['close']
  Stock_df['ValMA60'] = Stock_df['VolMA60'] * Stock_df['close']
  Stock_df['ValMA120'] = Stock_df['VolMA120'] * Stock_df['close']
  Stock_df['ValMA240'] = Stock_df['VolMA240'] * Stock_df['close']
  Stock_df['ValMA600'] = Stock_df['VolMA600'] * Stock_df['close']


def addtableMin(Stock_df):
  Stock_df['PMin03'] = Stock_df['close'].rolling(window=3).min()
  Stock_df['PMin05'] = Stock_df['close'].rolling(window=5).min()
  Stock_df['PMin10'] = Stock_df['close'].rolling(window=10).min()
  Stock_df['PMin20'] = Stock_df['close'].rolling(window=20).min()
  Stock_df['PMin25'] = Stock_df['close'].rolling(window=25).min()
  Stock_df['PMin40'] = Stock_df['close'].rolling(window=40).min()
  Stock_df['PMin60'] = Stock_df['close'].rolling(window=60).min()
  Stock_df['PMin100'] = Stock_df['close'].rolling(window=100).min()
  Stock_df['PMin120'] = Stock_df['close'].rolling(window=120).min()
  Stock_df['PMin200'] = Stock_df['close'].rolling(window=200).min()
  Stock_df['PMin240'] = Stock_df['close'].rolling(window=240).min()
  Stock_df['PMin600'] = Stock_df['close'].rolling(window=600).min()

  Stock_df['PMin03-1'] = Stock_df['PMin03'].shift(1)
  Stock_df['PMin05-1'] = Stock_df['PMin05'].shift(1)
  Stock_df['PMin10-1'] = Stock_df['PMin10'].shift(1)
  Stock_df['PMin20-1'] = Stock_df['PMin20'].shift(1)
  Stock_df['PMin25-1'] = Stock_df['PMin25'].shift(1)
  Stock_df['PMin40-1'] = Stock_df['PMin40'].shift(1)
  Stock_df['PMin60-1'] = Stock_df['PMin60'].shift(1)
  Stock_df['PMin100-1'] = Stock_df['PMin100'].shift(1)
  Stock_df['PMin120-1'] = Stock_df['PMin120'].shift(1)
  Stock_df['PMin200-1'] = Stock_df['PMin200'].shift(1)
  Stock_df['PMin240-1'] = Stock_df['PMin240'].shift(1)
  Stock_df['PMin600-1'] = Stock_df['PMin600'].shift(1)

  Stock_df['PMin03-2'] = Stock_df['PMin03'].shift(2)
  Stock_df['PMin05-2'] = Stock_df['PMin05'].shift(2)
  Stock_df['PMin10-2'] = Stock_df['PMin10'].shift(2)
  Stock_df['PMin20-2'] = Stock_df['PMin20'].shift(2)
  Stock_df['PMin25-2'] = Stock_df['PMin25'].shift(2)
  Stock_df['PMin40-2'] = Stock_df['PMin40'].shift(2)
  Stock_df['PMin60-2'] = Stock_df['PMin60'].shift(2)
  Stock_df['PMin100-2'] = Stock_df['PMin100'].shift(2)
  Stock_df['PMin120-2'] = Stock_df['PMin120'].shift(2)
  Stock_df['PMin200-2'] = Stock_df['PMin200'].shift(2)
  Stock_df['PMin240-2'] = Stock_df['PMin240'].shift(2)
  Stock_df['PMin600-2'] = Stock_df['PMin600'].shift(2)

  Stock_df['PMin03-5'] = Stock_df['PMin03'].shift(5)
  Stock_df['PMin05-5'] = Stock_df['PMin05'].shift(5)
  Stock_df['PMin10-5'] = Stock_df['PMin10'].shift(5)
  Stock_df['PMin20-5'] = Stock_df['PMin20'].shift(5)
  Stock_df['PMin25-5'] = Stock_df['PMin25'].shift(5)
  Stock_df['PMin40-5'] = Stock_df['PMin40'].shift(5)
  Stock_df['PMin60-5'] = Stock_df['PMin60'].shift(5)
  Stock_df['PMin100-5'] = Stock_df['PMin100'].shift(5)
  Stock_df['PMin120-5'] = Stock_df['PMin120'].shift(5)
  Stock_df['PMin200-5'] = Stock_df['PMin200'].shift(5)
  Stock_df['PMin240-5'] = Stock_df['PMin240'].shift(5)

  Stock_df['PMin03-10'] = Stock_df['PMin03'].shift(10)
  Stock_df['PMin05-10'] = Stock_df['PMin05'].shift(10)
  Stock_df['PMin10-10'] = Stock_df['PMin10'].shift(10)
  Stock_df['PMin20-10'] = Stock_df['PMin20'].shift(10)
  Stock_df['PMin25-10'] = Stock_df['PMin25'].shift(10)
  Stock_df['PMin40-10'] = Stock_df['PMin40'].shift(10)
  Stock_df['PMin60-10'] = Stock_df['PMin60'].shift(10)
  Stock_df['PMin100-10'] = Stock_df['PMin100'].shift(10)
  Stock_df['PMin120-10'] = Stock_df['PMin120'].shift(10)
  Stock_df['PMin200-10'] = Stock_df['PMin200'].shift(10)
  Stock_df['PMin240-10'] = Stock_df['PMin240'].shift(10)

  Stock_df['PMin03-20'] = Stock_df['PMin03'].shift(20)
  Stock_df['PMin05-20'] = Stock_df['PMin05'].shift(20)
  Stock_df['PMin10-20'] = Stock_df['PMin10'].shift(20)
  Stock_df['PMin20-20'] = Stock_df['PMin20'].shift(20)
  Stock_df['PMin25-20'] = Stock_df['PMin25'].shift(20)
  Stock_df['PMin40-20'] = Stock_df['PMin40'].shift(20)
  Stock_df['PMin60-20'] = Stock_df['PMin60'].shift(20)
  Stock_df['PMin100-20'] = Stock_df['PMin100'].shift(20)
  Stock_df['PMin120-20'] = Stock_df['PMin120'].shift(20)
  Stock_df['PMin200-20'] = Stock_df['PMin200'].shift(20)
  Stock_df['PMin240-20'] = Stock_df['PMin240'].shift(20)

  Stock_df['PMin03-25'] = Stock_df['PMin03'].shift(25)
  Stock_df['PMin05-25'] = Stock_df['PMin05'].shift(25)
  Stock_df['PMin10-25'] = Stock_df['PMin10'].shift(25)
  Stock_df['PMin20-25'] = Stock_df['PMin20'].shift(25)
  Stock_df['PMin25-25'] = Stock_df['PMin25'].shift(25)
  Stock_df['PMin40-25'] = Stock_df['PMin40'].shift(25)
  Stock_df['PMin60-25'] = Stock_df['PMin60'].shift(25)
  Stock_df['PMin100-25'] = Stock_df['PMin100'].shift(25)
  Stock_df['PMin120-25'] = Stock_df['PMin120'].shift(25)
  Stock_df['PMin200-25'] = Stock_df['PMin200'].shift(25)
  Stock_df['PMin240-25'] = Stock_df['PMin240'].shift(25)

  Stock_df['PMin03-60'] = Stock_df['PMin03'].shift(60)
  Stock_df['PMin05-60'] = Stock_df['PMin05'].shift(60)
  Stock_df['PMin10-60'] = Stock_df['PMin10'].shift(60)
  Stock_df['PMin20-60'] = Stock_df['PMin20'].shift(60)
  Stock_df['PMin25-60'] = Stock_df['PMin25'].shift(60)
  Stock_df['PMin40-60'] = Stock_df['PMin40'].shift(60)
  Stock_df['PMin60-60'] = Stock_df['PMin60'].shift(60)
  Stock_df['PMin100-60'] = Stock_df['PMin100'].shift(60)
  Stock_df['PMin120-60'] = Stock_df['PMin120'].shift(60)
  Stock_df['PMin200-60'] = Stock_df['PMin200'].shift(60)
  Stock_df['PMin240-60'] = Stock_df['PMin240'].shift(60)

  Stock_df['PMin03-100'] = Stock_df['PMin03'].shift(100)
  Stock_df['PMin05-100'] = Stock_df['PMin05'].shift(100)
  Stock_df['PMin10-100'] = Stock_df['PMin10'].shift(100)
  Stock_df['PMin20-100'] = Stock_df['PMin20'].shift(100)
  Stock_df['PMin25-100'] = Stock_df['PMin25'].shift(100)
  Stock_df['PMin40-100'] = Stock_df['PMin40'].shift(100)
  Stock_df['PMin60-100'] = Stock_df['PMin60'].shift(100)
  Stock_df['PMin100-100'] = Stock_df['PMin100'].shift(100)
  Stock_df['PMin120-100'] = Stock_df['PMin120'].shift(100)
  Stock_df['PMin200-100'] = Stock_df['PMin200'].shift(100)
  Stock_df['PMin240-100'] = Stock_df['PMin240'].shift(100)



  Stock_df['PMin03MA'] = Stock_df['PMin03'].rolling(window=3).mean()
  Stock_df['PMin05MA'] = Stock_df['PMin05'].rolling(window=5).mean()
  Stock_df['PMin10MA'] = Stock_df['PMin10'].rolling(window=10).mean()
  Stock_df['PMin20MA'] = Stock_df['PMin20'].rolling(window=20).mean()
  Stock_df['PMin25MA'] = Stock_df['PMin25'].rolling(window=25).mean()
  Stock_df['PMin40MA'] = Stock_df['PMin40'].rolling(window=40).mean()
  Stock_df['PMin60MA'] = Stock_df['PMin60'].rolling(window=60).mean()
  Stock_df['PMin100MA'] = Stock_df['PMin100'].rolling(window=100).mean()
  Stock_df['PMin120MA'] = Stock_df['PMin120'].rolling(window=120).mean()
  Stock_df['PMin200MA'] = Stock_df['PMin200'].rolling(window=200).mean()
  Stock_df['PMin240MA'] = Stock_df['PMin240'].rolling(window=240).mean()
  Stock_df['PMin600MA'] = Stock_df['PMin600'].rolling(window=600).mean()

  Stock_df['PMin03MA-1'] = Stock_df['PMin03MA'].shift(1)
  Stock_df['PMin05MA-1'] = Stock_df['PMin05MA'].shift(1)
  Stock_df['PMin10MA-1'] = Stock_df['PMin10MA'].shift(1)
  Stock_df['PMin20MA-1'] = Stock_df['PMin20MA'].shift(1)
  Stock_df['PMin25MA-1'] = Stock_df['PMin25MA'].shift(1)
  Stock_df['PMin40MA-1'] = Stock_df['PMin40MA'].shift(1)
  Stock_df['PMin60MA-1'] = Stock_df['PMin60MA'].shift(1)
  Stock_df['PMin100MA-1'] = Stock_df['PMin100MA'].shift(1)
  Stock_df['PMin120MA-1'] = Stock_df['PMin120MA'].shift(1)
  Stock_df['PMin200MA-1'] = Stock_df['PMin200MA'].shift(1)
  Stock_df['PMin240MA-1'] = Stock_df['PMin240MA'].shift(1)
  Stock_df['PMin600MA-1'] = Stock_df['PMin600MA'].shift(1)


def addtableMax(Stock_df):
  Stock_df['PMax03'] = Stock_df['close'].rolling(window=3).max()
  Stock_df['PMax05'] = Stock_df['close'].rolling(window=5).max()
  Stock_df['PMax10'] = Stock_df['close'].rolling(window=10).max()
  Stock_df['PMax20'] = Stock_df['close'].rolling(window=20).max()
  Stock_df['PMax25'] = Stock_df['close'].rolling(window=25).max()
  Stock_df['PMax40'] = Stock_df['close'].rolling(window=40).max()
  Stock_df['PMax60'] = Stock_df['close'].rolling(window=60).max()
  Stock_df['PMax100'] = Stock_df['close'].rolling(window=100).max()
  Stock_df['PMax120'] = Stock_df['close'].rolling(window=120).max()
  Stock_df['PMax200'] = Stock_df['close'].rolling(window=200).max()
  Stock_df['PMax240'] = Stock_df['close'].rolling(window=240).max()
  Stock_df['PMax600'] = Stock_df['close'].rolling(window=600).max()

  Stock_df['PMax03-1'] = Stock_df['PMax03'].shift(1)
  Stock_df['PMax05-1'] = Stock_df['PMax05'].shift(1)
  Stock_df['PMax10-1'] = Stock_df['PMax10'].shift(1)
  Stock_df['PMax20-1'] = Stock_df['PMax20'].shift(1)
  Stock_df['PMax25-1'] = Stock_df['PMax25'].shift(1)
  Stock_df['PMax40-1'] = Stock_df['PMax40'].shift(1)
  Stock_df['PMax60-1'] = Stock_df['PMax60'].shift(1)
  Stock_df['PMax100-1'] = Stock_df['PMax100'].shift(1)
  Stock_df['PMax120-1'] = Stock_df['PMax120'].shift(1)
  Stock_df['PMax200-1'] = Stock_df['PMax200'].shift(1)
  Stock_df['PMax240-1'] = Stock_df['PMax240'].shift(1)
  Stock_df['PMax600-1'] = Stock_df['PMax600'].shift(1)

  Stock_df['PMax03-2'] = Stock_df['PMax03'].shift(2)
  Stock_df['PMax05-2'] = Stock_df['PMax05'].shift(2)
  Stock_df['PMax10-2'] = Stock_df['PMax10'].shift(2)
  Stock_df['PMax20-2'] = Stock_df['PMax20'].shift(2)
  Stock_df['PMax25-2'] = Stock_df['PMax25'].shift(2)
  Stock_df['PMax40-2'] = Stock_df['PMax40'].shift(2)
  Stock_df['PMax60-2'] = Stock_df['PMax60'].shift(2)
  Stock_df['PMax100-2'] = Stock_df['PMax100'].shift(2)
  Stock_df['PMax120-2'] = Stock_df['PMax120'].shift(2)
  Stock_df['PMax200-2'] = Stock_df['PMax200'].shift(2)
  Stock_df['PMax240-2'] = Stock_df['PMax240'].shift(2)
  Stock_df['PMax600-2'] = Stock_df['PMax600'].shift(2)

  Stock_df['PMax03-5'] = Stock_df['PMax03'].shift(5)
  Stock_df['PMax05-5'] = Stock_df['PMax05'].shift(5)
  Stock_df['PMax10-5'] = Stock_df['PMax10'].shift(5)
  Stock_df['PMax20-5'] = Stock_df['PMax20'].shift(5)
  Stock_df['PMax25-5'] = Stock_df['PMax25'].shift(5)
  Stock_df['PMax40-5'] = Stock_df['PMax40'].shift(5)
  Stock_df['PMax60-5'] = Stock_df['PMax60'].shift(5)
  Stock_df['PMax100-5'] = Stock_df['PMax100'].shift(5)
  Stock_df['PMax120-5'] = Stock_df['PMax120'].shift(5)
  Stock_df['PMax200-5'] = Stock_df['PMax200'].shift(5)
  Stock_df['PMax240-5'] = Stock_df['PMax240'].shift(5)

  Stock_df['PMax03-10'] = Stock_df['PMax03'].shift(10)
  Stock_df['PMax05-10'] = Stock_df['PMax05'].shift(10)
  Stock_df['PMax10-10'] = Stock_df['PMax10'].shift(10)
  Stock_df['PMax20-10'] = Stock_df['PMax20'].shift(10)
  Stock_df['PMax25-10'] = Stock_df['PMax25'].shift(10)
  Stock_df['PMax40-10'] = Stock_df['PMax40'].shift(10)
  Stock_df['PMax60-10'] = Stock_df['PMax60'].shift(10)
  Stock_df['PMax100-10'] = Stock_df['PMax100'].shift(10)
  Stock_df['PMax120-10'] = Stock_df['PMax120'].shift(10)
  Stock_df['PMax200-10'] = Stock_df['PMax200'].shift(10)
  Stock_df['PMax240-10'] = Stock_df['PMax240'].shift(10)

  Stock_df['PMax03-20'] = Stock_df['PMax03'].shift(20)
  Stock_df['PMax05-20'] = Stock_df['PMax05'].shift(20)
  Stock_df['PMax10-20'] = Stock_df['PMax10'].shift(20)
  Stock_df['PMax20-20'] = Stock_df['PMax20'].shift(20)
  Stock_df['PMax25-20'] = Stock_df['PMax25'].shift(20)
  Stock_df['PMax40-20'] = Stock_df['PMax40'].shift(20)
  Stock_df['PMax60-20'] = Stock_df['PMax60'].shift(20)
  Stock_df['PMax100-20'] = Stock_df['PMax100'].shift(20)
  Stock_df['PMax120-20'] = Stock_df['PMax120'].shift(20)
  Stock_df['PMax200-20'] = Stock_df['PMax200'].shift(20)
  Stock_df['PMax240-20'] = Stock_df['PMax240'].shift(20)

  Stock_df['PMax03-25'] = Stock_df['PMax03'].shift(25)
  Stock_df['PMax05-25'] = Stock_df['PMax05'].shift(25)
  Stock_df['PMax10-25'] = Stock_df['PMax10'].shift(25)
  Stock_df['PMax20-25'] = Stock_df['PMax20'].shift(25)
  Stock_df['PMax25-25'] = Stock_df['PMax25'].shift(25)
  Stock_df['PMax40-25'] = Stock_df['PMax40'].shift(25)
  Stock_df['PMax60-25'] = Stock_df['PMax60'].shift(25)
  Stock_df['PMax100-25'] = Stock_df['PMax100'].shift(25)
  Stock_df['PMax120-25'] = Stock_df['PMax120'].shift(25)
  Stock_df['PMax200-25'] = Stock_df['PMax200'].shift(25)
  Stock_df['PMax240-25'] = Stock_df['PMax240'].shift(25)

  Stock_df['PMax03-60'] = Stock_df['PMax03'].shift(60)
  Stock_df['PMax05-60'] = Stock_df['PMax05'].shift(60)
  Stock_df['PMax10-60'] = Stock_df['PMax10'].shift(60)
  Stock_df['PMax20-60'] = Stock_df['PMax20'].shift(60)
  Stock_df['PMax25-60'] = Stock_df['PMax25'].shift(60)
  Stock_df['PMax40-60'] = Stock_df['PMax40'].shift(60)
  Stock_df['PMax60-60'] = Stock_df['PMax60'].shift(60)
  Stock_df['PMax100-60'] = Stock_df['PMax100'].shift(60)
  Stock_df['PMax120-60'] = Stock_df['PMax120'].shift(60)
  Stock_df['PMax200-60'] = Stock_df['PMax200'].shift(60)
  Stock_df['PMax240-60'] = Stock_df['PMax240'].shift(60)

  Stock_df['PMax03-100'] = Stock_df['PMax03'].shift(100)
  Stock_df['PMax05-100'] = Stock_df['PMax05'].shift(100)
  Stock_df['PMax10-100'] = Stock_df['PMax10'].shift(100)
  Stock_df['PMax20-100'] = Stock_df['PMax20'].shift(100)
  Stock_df['PMax25-100'] = Stock_df['PMax25'].shift(100)
  Stock_df['PMax40-100'] = Stock_df['PMax40'].shift(100)
  Stock_df['PMax60-100'] = Stock_df['PMax60'].shift(100)
  Stock_df['PMax100-100'] = Stock_df['PMax100'].shift(100)
  Stock_df['PMax120-100'] = Stock_df['PMax120'].shift(100)
  Stock_df['PMax200-100'] = Stock_df['PMax200'].shift(100)
  Stock_df['PMax240-100'] = Stock_df['PMax240'].shift(100)


  Stock_df['PMax03MA'] = Stock_df['PMax03'].rolling(window=3).mean()
  Stock_df['PMax05MA'] = Stock_df['PMax05'].rolling(window=5).mean()
  Stock_df['PMax10MA'] = Stock_df['PMax10'].rolling(window=10).mean()
  Stock_df['PMax20MA'] = Stock_df['PMax20'].rolling(window=20).mean()
  Stock_df['PMax25MA'] = Stock_df['PMax25'].rolling(window=25).mean()
  Stock_df['PMax40MA'] = Stock_df['PMax40'].rolling(window=40).mean()
  Stock_df['PMax60MA'] = Stock_df['PMax60'].rolling(window=60).mean()
  Stock_df['PMax100MA'] = Stock_df['PMax100'].rolling(window=100).mean()
  Stock_df['PMax120MA'] = Stock_df['PMax120'].rolling(window=120).mean()
  Stock_df['PMax200MA'] = Stock_df['PMax200'].rolling(window=200).mean()
  Stock_df['PMax240MA'] = Stock_df['PMax240'].rolling(window=240).mean()
  Stock_df['PMax600MA'] = Stock_df['PMax600'].rolling(window=600).mean()

  Stock_df['PMax03MA-1'] = Stock_df['PMax03MA'].shift(1)
  Stock_df['PMax05MA-1'] = Stock_df['PMax05MA'].shift(1)
  Stock_df['PMax10MA-1'] = Stock_df['PMax10MA'].shift(1)
  Stock_df['PMax20MA-1'] = Stock_df['PMax20MA'].shift(1)
  Stock_df['PMax25MA-1'] = Stock_df['PMax25MA'].shift(1)
  Stock_df['PMax40MA-1'] = Stock_df['PMax40MA'].shift(1)
  Stock_df['PMax60MA-1'] = Stock_df['PMax60MA'].shift(1)
  Stock_df['PMax100MA-1'] = Stock_df['PMax100MA'].shift(1)
  Stock_df['PMax120MA-1'] = Stock_df['PMax120MA'].shift(1)
  Stock_df['PMax200MA-1'] = Stock_df['PMax200MA'].shift(1)
  Stock_df['PMax240MA-1'] = Stock_df['PMax240MA'].shift(1)
  Stock_df['PMax600MA-1'] = Stock_df['PMax600MA'].shift(1)



def addtablelow(Stock_df):
  Stock_df['PLow03'] = Stock_df['low'].rolling(window=3).min()
  Stock_df['PLow05'] = Stock_df['low'].rolling(window=5).min()
  Stock_df['PLow10'] = Stock_df['low'].rolling(window=10).min()
  Stock_df['PLow20'] = Stock_df['low'].rolling(window=20).min()
  Stock_df['PLow25'] = Stock_df['low'].rolling(window=25).min()
  Stock_df['PLow40'] = Stock_df['low'].rolling(window=40).min()
  Stock_df['PLow60'] = Stock_df['low'].rolling(window=60).min()
  Stock_df['PLow100'] = Stock_df['low'].rolling(window=100).min()
  Stock_df['PLow120'] = Stock_df['low'].rolling(window=120).min()
  Stock_df['PLow200'] = Stock_df['low'].rolling(window=200).min()
  Stock_df['PLow240'] = Stock_df['low'].rolling(window=240).min()
  Stock_df['PLow600'] = Stock_df['low'].rolling(window=600).min()

  Stock_df['PLow03-1'] = Stock_df['PLow03'].shift(1)
  Stock_df['PLow05-1'] = Stock_df['PLow05'].shift(1)
  Stock_df['PLow10-1'] = Stock_df['PLow10'].shift(1)
  Stock_df['PLow20-1'] = Stock_df['PLow20'].shift(1)
  Stock_df['PLow25-1'] = Stock_df['PLow25'].shift(1)
  Stock_df['PLow40-1'] = Stock_df['PLow40'].shift(1)
  Stock_df['PLow60-1'] = Stock_df['PLow60'].shift(1)
  Stock_df['PLow100-1'] = Stock_df['PLow100'].shift(1)
  Stock_df['PLow120-1'] = Stock_df['PLow120'].shift(1)
  Stock_df['PLow200-1'] = Stock_df['PLow200'].shift(1)
  Stock_df['PLow240-1'] = Stock_df['PLow240'].shift(1)

  Stock_df['PLow03-2'] = Stock_df['PLow03'].shift(2)
  Stock_df['PLow05-2'] = Stock_df['PLow05'].shift(2)
  Stock_df['PLow10-2'] = Stock_df['PLow10'].shift(2)
  Stock_df['PLow20-2'] = Stock_df['PLow20'].shift(2)
  Stock_df['PLow25-2'] = Stock_df['PLow25'].shift(2)
  Stock_df['PLow40-2'] = Stock_df['PLow40'].shift(2)
  Stock_df['PLow60-2'] = Stock_df['PLow60'].shift(2)
  Stock_df['PLow100-2'] = Stock_df['PLow100'].shift(2)
  Stock_df['PLow120-2'] = Stock_df['PLow120'].shift(2)
  Stock_df['PLow200-2'] = Stock_df['PLow200'].shift(2)
  Stock_df['PLow240-2'] = Stock_df['PLow240'].shift(2)

  Stock_df['PLow03-5'] = Stock_df['PLow03'].shift(5)
  Stock_df['PLow05-5'] = Stock_df['PLow05'].shift(5)
  Stock_df['PLow10-5'] = Stock_df['PLow10'].shift(5)
  Stock_df['PLow20-5'] = Stock_df['PLow20'].shift(5)
  Stock_df['PLow25-5'] = Stock_df['PLow25'].shift(5)
  Stock_df['PLow40-5'] = Stock_df['PLow40'].shift(5)
  Stock_df['PLow60-5'] = Stock_df['PLow60'].shift(5)
  Stock_df['PLow100-5'] = Stock_df['PLow100'].shift(5)
  Stock_df['PLow120-5'] = Stock_df['PLow120'].shift(5)
  Stock_df['PLow200-5'] = Stock_df['PLow200'].shift(5)
  Stock_df['PLow240-5'] = Stock_df['PLow240'].shift(5)

  Stock_df['PLow03-10'] = Stock_df['PLow03'].shift(10)
  Stock_df['PLow05-10'] = Stock_df['PLow05'].shift(10)
  Stock_df['PLow10-10'] = Stock_df['PLow10'].shift(10)
  Stock_df['PLow20-10'] = Stock_df['PLow20'].shift(10)
  Stock_df['PLow25-10'] = Stock_df['PLow25'].shift(10)
  Stock_df['PLow40-10'] = Stock_df['PLow40'].shift(10)
  Stock_df['PLow60-10'] = Stock_df['PLow60'].shift(10)
  Stock_df['PLow100-10'] = Stock_df['PLow100'].shift(10)
  Stock_df['PLow120-10'] = Stock_df['PLow120'].shift(10)
  Stock_df['PLow200-10'] = Stock_df['PLow200'].shift(10)
  Stock_df['PLow240-10'] = Stock_df['PLow240'].shift(10)

  Stock_df['PLow03-20'] = Stock_df['PLow03'].shift(20)
  Stock_df['PLow05-20'] = Stock_df['PLow05'].shift(20)
  Stock_df['PLow10-20'] = Stock_df['PLow10'].shift(20)
  Stock_df['PLow20-20'] = Stock_df['PLow20'].shift(20)
  Stock_df['PLow25-20'] = Stock_df['PLow25'].shift(20)
  Stock_df['PLow40-20'] = Stock_df['PLow40'].shift(20)
  Stock_df['PLow60-20'] = Stock_df['PLow60'].shift(20)
  Stock_df['PLow100-20'] = Stock_df['PLow100'].shift(20)
  Stock_df['PLow120-20'] = Stock_df['PLow120'].shift(20)
  Stock_df['PLow200-20'] = Stock_df['PLow200'].shift(20)
  Stock_df['PLow240-20'] = Stock_df['PLow240'].shift(20)

  Stock_df['PLow03-25'] = Stock_df['PLow03'].shift(25)
  Stock_df['PLow05-25'] = Stock_df['PLow05'].shift(25)
  Stock_df['PLow10-25'] = Stock_df['PLow10'].shift(25)
  Stock_df['PLow20-25'] = Stock_df['PLow20'].shift(25)
  Stock_df['PLow25-25'] = Stock_df['PLow25'].shift(25)
  Stock_df['PLow40-25'] = Stock_df['PLow40'].shift(25)
  Stock_df['PLow60-25'] = Stock_df['PLow60'].shift(25)
  Stock_df['PLow100-25'] = Stock_df['PLow100'].shift(25)
  Stock_df['PLow120-25'] = Stock_df['PLow120'].shift(25)
  Stock_df['PLow200-25'] = Stock_df['PLow200'].shift(25)
  Stock_df['PLow240-25'] = Stock_df['PLow240'].shift(25)

  Stock_df['PLow03-60'] = Stock_df['PLow03'].shift(60)
  Stock_df['PLow05-60'] = Stock_df['PLow05'].shift(60)
  Stock_df['PLow10-60'] = Stock_df['PLow10'].shift(60)
  Stock_df['PLow20-60'] = Stock_df['PLow20'].shift(60)
  Stock_df['PLow25-60'] = Stock_df['PLow25'].shift(60)
  Stock_df['PLow40-60'] = Stock_df['PLow40'].shift(60)
  Stock_df['PLow60-60'] = Stock_df['PLow60'].shift(60)
  Stock_df['PLow100-60'] = Stock_df['PLow100'].shift(60)
  Stock_df['PLow120-60'] = Stock_df['PLow120'].shift(60)
  Stock_df['PLow200-60'] = Stock_df['PLow200'].shift(60)
  Stock_df['PLow240-60'] = Stock_df['PLow240'].shift(60)
  Stock_df['PLow03-100'] = Stock_df['PLow03'].shift(100)
  Stock_df['PLow05-100'] = Stock_df['PLow05'].shift(100)
  Stock_df['PLow10-100'] = Stock_df['PLow10'].shift(100)
  Stock_df['PLow20-100'] = Stock_df['PLow20'].shift(100)
  Stock_df['PLow25-100'] = Stock_df['PLow25'].shift(100)
  Stock_df['PLow60-100'] = Stock_df['PLow60'].shift(100)
  Stock_df['PLow100-100'] = Stock_df['PLow100'].shift(100)
  Stock_df['PLow120-100'] = Stock_df['PLow120'].shift(100)
  Stock_df['PLow200-100'] = Stock_df['PLow200'].shift(100)
  Stock_df['PLow240-100'] = Stock_df['PLow240'].shift(100)







def addtablehigh(Stock_df):
  Stock_df['PHIGH03'] = Stock_df['high'].rolling(window=3).max()
  Stock_df['PHIGH05'] = Stock_df['high'].rolling(window=5).max()
  Stock_df['PHIGH10'] = Stock_df['high'].rolling(window=10).max()
  Stock_df['PHIGH20'] = Stock_df['high'].rolling(window=20).max()
  Stock_df['PHIGH25'] = Stock_df['high'].rolling(window=25).max()
  Stock_df['PHIGH40'] = Stock_df['high'].rolling(window=40).max()
  Stock_df['PHIGH60'] = Stock_df['high'].rolling(window=60).max()
  Stock_df['PHIGH100'] = Stock_df['high'].rolling(window=100).max()
  Stock_df['PHIGH120'] = Stock_df['high'].rolling(window=120).max()
  Stock_df['PHIGH200'] = Stock_df['high'].rolling(window=200).max()
  Stock_df['PHIGH240'] = Stock_df['high'].rolling(window=240).max()
  Stock_df['PHIGH600'] = Stock_df['high'].rolling(window=600).max()

  Stock_df['PHIGH03-1'] = Stock_df['PHIGH03'].shift(1)
  Stock_df['PHIGH05-1'] = Stock_df['PHIGH05'].shift(1)
  Stock_df['PHIGH10-1'] = Stock_df['PHIGH10'].shift(1)
  Stock_df['PHIGH20-1'] = Stock_df['PHIGH20'].shift(1)
  Stock_df['PHIGH25-1'] = Stock_df['PHIGH25'].shift(1)
  Stock_df['PHIGH40-1'] = Stock_df['PHIGH40'].shift(1)
  Stock_df['PHIGH60-1'] = Stock_df['PHIGH60'].shift(1)
  Stock_df['PHIGH100-1'] = Stock_df['PHIGH100'].shift(1)
  Stock_df['PHIGH120-1'] = Stock_df['PHIGH120'].shift(1)
  Stock_df['PHIGH200-1'] = Stock_df['PHIGH200'].shift(1)
  Stock_df['PHIGH240-1'] = Stock_df['PHIGH240'].shift(1)

  Stock_df['PHIGH03-2'] = Stock_df['PHIGH03'].shift(2)
  Stock_df['PHIGH05-2'] = Stock_df['PHIGH05'].shift(2)
  Stock_df['PHIGH10-2'] = Stock_df['PHIGH10'].shift(2)
  Stock_df['PHIGH20-2'] = Stock_df['PHIGH20'].shift(2)
  Stock_df['PHIGH25-2'] = Stock_df['PHIGH25'].shift(2)
  Stock_df['PHIGH40-2'] = Stock_df['PHIGH40'].shift(2)
  Stock_df['PHIGH60-2'] = Stock_df['PHIGH60'].shift(2)
  Stock_df['PHIGH100-2'] = Stock_df['PHIGH100'].shift(2)
  Stock_df['PHIGH120-2'] = Stock_df['PHIGH120'].shift(2)
  Stock_df['PHIGH200-2'] = Stock_df['PHIGH200'].shift(2)
  Stock_df['PHIGH240-2'] = Stock_df['PHIGH240'].shift(2)

  Stock_df['PHIGH03-5'] = Stock_df['PHIGH03'].shift(5)
  Stock_df['PHIGH05-5'] = Stock_df['PHIGH05'].shift(5)
  Stock_df['PHIGH10-5'] = Stock_df['PHIGH10'].shift(5)
  Stock_df['PHIGH20-5'] = Stock_df['PHIGH20'].shift(5)
  Stock_df['PHIGH25-5'] = Stock_df['PHIGH25'].shift(5)
  Stock_df['PHIGH40-5'] = Stock_df['PHIGH40'].shift(5)
  Stock_df['PHIGH60-5'] = Stock_df['PHIGH60'].shift(5)
  Stock_df['PHIGH100-5'] = Stock_df['PHIGH100'].shift(5)
  Stock_df['PHIGH120-5'] = Stock_df['PHIGH120'].shift(5)
  Stock_df['PHIGH200-5'] = Stock_df['PHIGH200'].shift(5)
  Stock_df['PHIGH240-5'] = Stock_df['PHIGH240'].shift(5)

  Stock_df['PHIGH03-10'] = Stock_df['PHIGH03'].shift(10)
  Stock_df['PHIGH05-10'] = Stock_df['PHIGH05'].shift(10)
  Stock_df['PHIGH10-10'] = Stock_df['PHIGH10'].shift(10)
  Stock_df['PHIGH20-10'] = Stock_df['PHIGH20'].shift(10)
  Stock_df['PHIGH25-10'] = Stock_df['PHIGH25'].shift(10)
  Stock_df['PHIGH40-10'] = Stock_df['PHIGH40'].shift(10)
  Stock_df['PHIGH60-10'] = Stock_df['PHIGH60'].shift(10)
  Stock_df['PHIGH100-10'] = Stock_df['PHIGH100'].shift(10)
  Stock_df['PHIGH120-10'] = Stock_df['PHIGH120'].shift(10)
  Stock_df['PHIGH200-10'] = Stock_df['PHIGH200'].shift(10)
  Stock_df['PHIGH240-10'] = Stock_df['PHIGH240'].shift(10)

  Stock_df['PHIGH03-20'] = Stock_df['PHIGH03'].shift(20)
  Stock_df['PHIGH05-20'] = Stock_df['PHIGH05'].shift(20)
  Stock_df['PHIGH10-20'] = Stock_df['PHIGH10'].shift(20)
  Stock_df['PHIGH20-20'] = Stock_df['PHIGH20'].shift(20)
  Stock_df['PHIGH25-20'] = Stock_df['PHIGH25'].shift(20)
  Stock_df['PHIGH40-20'] = Stock_df['PHIGH40'].shift(20)
  Stock_df['PHIGH60-20'] = Stock_df['PHIGH60'].shift(20)
  Stock_df['PHIGH100-20'] = Stock_df['PHIGH100'].shift(20)
  Stock_df['PHIGH120-20'] = Stock_df['PHIGH120'].shift(20)
  Stock_df['PHIGH200-20'] = Stock_df['PHIGH200'].shift(20)
  Stock_df['PHIGH240-20'] = Stock_df['PHIGH240'].shift(20)

  Stock_df['PHIGH03-25'] = Stock_df['PHIGH03'].shift(25)
  Stock_df['PHIGH05-25'] = Stock_df['PHIGH05'].shift(25)
  Stock_df['PHIGH10-25'] = Stock_df['PHIGH10'].shift(25)
  Stock_df['PHIGH20-25'] = Stock_df['PHIGH20'].shift(25)
  Stock_df['PHIGH25-25'] = Stock_df['PHIGH25'].shift(25)
  Stock_df['PHIGH40-25'] = Stock_df['PHIGH40'].shift(25)
  Stock_df['PHIGH60-25'] = Stock_df['PHIGH60'].shift(25)
  Stock_df['PHIGH100-25'] = Stock_df['PHIGH100'].shift(25)
  Stock_df['PHIGH120-25'] = Stock_df['PHIGH120'].shift(25)
  Stock_df['PHIGH200-25'] = Stock_df['PHIGH200'].shift(25)
  Stock_df['PHIGH240-25'] = Stock_df['PHIGH240'].shift(25)

  Stock_df['PHIGH03-60'] = Stock_df['PHIGH03'].shift(60)
  Stock_df['PHIGH05-60'] = Stock_df['PHIGH05'].shift(60)
  Stock_df['PHIGH10-60'] = Stock_df['PHIGH10'].shift(60)
  Stock_df['PHIGH20-60'] = Stock_df['PHIGH20'].shift(60)
  Stock_df['PHIGH25-60'] = Stock_df['PHIGH25'].shift(60)
  Stock_df['PHIGH40-60'] = Stock_df['PHIGH40'].shift(60)
  Stock_df['PHIGH60-60'] = Stock_df['PHIGH60'].shift(60)
  Stock_df['PHIGH100-60'] = Stock_df['PHIGH100'].shift(60)
  Stock_df['PHIGH120-60'] = Stock_df['PHIGH120'].shift(60)
  Stock_df['PHIGH200-60'] = Stock_df['PHIGH200'].shift(60)
  Stock_df['PHIGH240-60'] = Stock_df['PHIGH240'].shift(60)

  Stock_df['PHIGH03-100'] = Stock_df['PHIGH03'].shift(100)
  Stock_df['PHIGH05-100'] = Stock_df['PHIGH05'].shift(100)
  Stock_df['PHIGH10-100'] = Stock_df['PHIGH10'].shift(100)
  Stock_df['PHIGH20-100'] = Stock_df['PHIGH20'].shift(100)
  Stock_df['PHIGH25-100'] = Stock_df['PHIGH25'].shift(100)
  Stock_df['PHIGH60-100'] = Stock_df['PHIGH60'].shift(100)
  Stock_df['PHIGH60-100'] = Stock_df['PHIGH60'].shift(100)
  Stock_df['PHIGH100-100'] = Stock_df['PHIGH100'].shift(100)
  Stock_df['PHIGH120-100'] = Stock_df['PHIGH120'].shift(100)
  Stock_df['PHIGH200-100'] = Stock_df['PHIGH200'].shift(100)
  Stock_df['PHIGH240-100'] = Stock_df['PHIGH240'].shift(100)



def addtableMinMaxptc(Stock_df):
  Stock_df['PMin03%'] = ((Stock_df['close'] - Stock_df['PMin03'])/Stock_df['close']) *100
  Stock_df['PMin05%'] = ((Stock_df['close'] - Stock_df['PMin05'])/Stock_df['close']) *100
  Stock_df['PMin10%'] = ((Stock_df['close'] - Stock_df['PMin10'])/Stock_df['close']) *100
  Stock_df['PMin20%'] = ((Stock_df['close'] - Stock_df['PMin20'])/Stock_df['close']) *100
  Stock_df['PMin25%'] = ((Stock_df['close'] - Stock_df['PMin25'])/Stock_df['close']) *100
  Stock_df['PMin60%'] = ((Stock_df['close'] - Stock_df['PMin60'])/Stock_df['close']) *100
  Stock_df['PMin100%'] = ((Stock_df['close'] - Stock_df['PMin100'])/Stock_df['close']) *100
  Stock_df['PMin200%'] = ((Stock_df['close'] - Stock_df['PMin200'])/Stock_df['close']) *100
  Stock_df['PMin600%'] = ((Stock_df['close'] - Stock_df['PMin600'])/Stock_df['close']) *100

  Stock_df['PMax03%'] = ((Stock_df['close'] - Stock_df['PMax03'])/Stock_df['close']) *100
  Stock_df['PMax05%'] = ((Stock_df['close'] - Stock_df['PMax05'])/Stock_df['close']) *100
  Stock_df['PMax10%'] = ((Stock_df['close'] - Stock_df['PMax10'])/Stock_df['close']) *100
  Stock_df['PMax20%'] = ((Stock_df['close'] - Stock_df['PMax20'])/Stock_df['close']) *100
  Stock_df['PMax25%'] = ((Stock_df['close'] - Stock_df['PMax25'])/Stock_df['close']) *100
  Stock_df['PMax60%'] = ((Stock_df['close'] - Stock_df['PMax60'])/Stock_df['close']) *100
  Stock_df['PMax100%'] = ((Stock_df['close'] - Stock_df['PMax100'])/Stock_df['close']) *100
  Stock_df['PMax200%'] = ((Stock_df['close'] - Stock_df['PMax200'])/Stock_df['close']) *100
  Stock_df['PMax600%'] = ((Stock_df['close'] - Stock_df['PMax600'])/Stock_df['close']) *100

  Stock_df['PMin03%-1'] = Stock_df['PMin03%'].shift(1)
  Stock_df['PMin05%-1'] = Stock_df['PMin05%'].shift(1)
  Stock_df['PMin10%-1'] = Stock_df['PMin10%'].shift(1)
  Stock_df['PMin20%-1'] = Stock_df['PMin20%'].shift(1)
  Stock_df['PMin25%-1']=Stock_df['PMin25%'].shift(1)
  Stock_df['PMin60%-1']=Stock_df['PMin60%'].shift(1)
  Stock_df['PMin100%-1']=Stock_df['PMin100%'].shift(1)
  Stock_df['PMin200%-1']=Stock_df['PMin200%'].shift(1)
  Stock_df['PMin600%-1']=Stock_df['PMin600%'].shift(1)

  Stock_df['PMax03%-1'] = Stock_df['PMax03%'].shift(1)
  Stock_df['PMax05%-1'] = Stock_df['PMax05%'].shift(1)
  Stock_df['PMax10%-1'] = Stock_df['PMax10%'].shift(1)
  Stock_df['PMax20%-1'] = Stock_df['PMax20%'].shift(1)
  Stock_df['PMax25%-1']=Stock_df['PMax25%'].shift(1)
  Stock_df['PMax60%-1']=Stock_df['PMax60%'].shift(1)
  Stock_df['PMax100%-1']=Stock_df['PMax100%'].shift(1)
  Stock_df['PMax200%-1']=Stock_df['PMax200%'].shift(1)
  Stock_df['PMax600%-1']=Stock_df['PMax600%'].shift(1)

  Stock_df['PMin03%-2'] = Stock_df['PMin03%'].shift(2)
  Stock_df['PMin05%-2'] = Stock_df['PMin05%'].shift(2)
  Stock_df['PMin10%-2'] = Stock_df['PMin10%'].shift(2)
  Stock_df['PMin20%-2'] = Stock_df['PMin20%'].shift(2)
  Stock_df['PMin25%-2']=Stock_df['PMin25%'].shift(2)
  Stock_df['PMin60%-2']=Stock_df['PMin60%'].shift(2)
  Stock_df['PMin100%-2']=Stock_df['PMin100%'].shift(2)
  Stock_df['PMin200%-2']=Stock_df['PMin200%'].shift(2)
  Stock_df['PMin600%-2']=Stock_df['PMin600%'].shift(2)

  Stock_df['PMax03%-2'] = Stock_df['PMax03%'].shift(2)
  Stock_df['PMax05%-2'] = Stock_df['PMax05%'].shift(2)
  Stock_df['PMax10%-2'] = Stock_df['PMax10%'].shift(2)
  Stock_df['PMax20%-2'] = Stock_df['PMax20%'].shift(2)
  Stock_df['PMax25%-2']=Stock_df['PMax25%'].shift(2)
  Stock_df['PMax60%-2']=Stock_df['PMax60%'].shift(2)
  Stock_df['PMax100%-2']=Stock_df['PMax100%'].shift(2)
  Stock_df['PMax200%-2']=Stock_df['PMax200%'].shift(2)
  Stock_df['PMax600%-2']=Stock_df['PMax600%'].shift(2)

  Stock_df['PMin60%-3']=Stock_df['PMin60%'].shift(3)

  Stock_df['PMin60%dif'] = Stock_df['PMin60%']-Stock_df['PMin60%-1']
  Stock_df['PMin200%dif']=Stock_df['PMin200%']-Stock_df['PMin200%-1']

def addtablehighlowptc(Stock_df):
  Stock_df['PLow03%'] = ((Stock_df['close'] - Stock_df['PLow03'])/Stock_df['close']) *100
  Stock_df['PLow05%'] = ((Stock_df['close'] - Stock_df['PLow05'])/Stock_df['close']) *100
  Stock_df['PLow10%'] = ((Stock_df['close'] - Stock_df['PLow10'])/Stock_df['close']) *100
  Stock_df['PLow20%'] = ((Stock_df['close'] - Stock_df['PLow20'])/Stock_df['close']) *100
  Stock_df['PLow25%'] = ((Stock_df['close'] - Stock_df['PLow25'])/Stock_df['close']) *100
  Stock_df['PLow60%'] = ((Stock_df['close'] - Stock_df['PLow60'])/Stock_df['close']) *100
  Stock_df['PLow100%'] = ((Stock_df['close'] - Stock_df['PLow100'])/Stock_df['close']) *100
  Stock_df['PLow200%'] = ((Stock_df['close'] - Stock_df['PLow200'])/Stock_df['close']) *100
  Stock_df['PLow600%'] = ((Stock_df['close'] - Stock_df['PLow600'])/Stock_df['close']) *100

  Stock_df['PHIGH03%'] = ((Stock_df['close'] - Stock_df['PHIGH03'])/Stock_df['close']) *100
  Stock_df['PHIGH05%'] = ((Stock_df['close'] - Stock_df['PHIGH05'])/Stock_df['close']) *100
  Stock_df['PHIGH10%'] = ((Stock_df['close'] - Stock_df['PHIGH10'])/Stock_df['close']) *100
  Stock_df['PHIGH20%'] = ((Stock_df['close'] - Stock_df['PHIGH20'])/Stock_df['close']) *100
  Stock_df['PHIGH25%'] = ((Stock_df['close'] - Stock_df['PHIGH25'])/Stock_df['close']) *100
  Stock_df['PHIGH60%'] = ((Stock_df['close'] - Stock_df['PHIGH60'])/Stock_df['close']) *100
  Stock_df['PHIGH100%'] = ((Stock_df['close'] - Stock_df['PHIGH100'])/Stock_df['close']) *100
  Stock_df['PHIGH200%'] = ((Stock_df['close'] - Stock_df['PHIGH200'])/Stock_df['close']) *100
  Stock_df['PHIGH600%'] = ((Stock_df['close'] - Stock_df['PHIGH600'])/Stock_df['close']) *100

  Stock_df['PLow03%-1'] = Stock_df['PLow03%'].shift(1)
  Stock_df['PLow05%-1'] = Stock_df['PLow05%'].shift(1)
  Stock_df['PLow10%-1'] = Stock_df['PLow10%'].shift(1)
  Stock_df['PLow20%-1'] = Stock_df['PLow20%'].shift(1)
  Stock_df['PLow25%-1']=Stock_df['PLow25%'].shift(1)
  Stock_df['PLow60%-1']=Stock_df['PLow60%'].shift(1)
  Stock_df['PLow100%-1']=Stock_df['PLow100%'].shift(1)
  Stock_df['PLow200%-1']=Stock_df['PLow200%'].shift(1)
  Stock_df['PLow600%-1']=Stock_df['PLow600%'].shift(1)

  Stock_df['PHIGH03%-1'] = Stock_df['PHIGH03%'].shift(1)
  Stock_df['PHIGH05%-1'] = Stock_df['PHIGH05%'].shift(1)
  Stock_df['PHIGH10%-1'] = Stock_df['PHIGH10%'].shift(1)
  Stock_df['PHIGH20%-1'] = Stock_df['PHIGH20%'].shift(1)
  Stock_df['PHIGH25%-1']=Stock_df['PHIGH25%'].shift(1)
  Stock_df['PHIGH60%-1']=Stock_df['PHIGH60%'].shift(1)
  Stock_df['PHIGH100%-1']=Stock_df['PHIGH100%'].shift(1)
  Stock_df['PHIGH200%-1']=Stock_df['PHIGH200%'].shift(1)
  Stock_df['PHIGH600%-1']=Stock_df['PHIGH600%'].shift(1)

  Stock_df['PLow03%-2'] = Stock_df['PLow03%'].shift(2)
  Stock_df['PLow05%-2'] = Stock_df['PLow05%'].shift(2)
  Stock_df['PLow10%-2'] = Stock_df['PLow10%'].shift(2)
  Stock_df['PLow20%-2'] = Stock_df['PLow20%'].shift(2)
  Stock_df['PLow25%-2']=Stock_df['PLow25%'].shift(2)
  Stock_df['PLow60%-2']=Stock_df['PLow60%'].shift(2)
  Stock_df['PLow100%-2']=Stock_df['PLow100%'].shift(2)
  Stock_df['PLow200%-2']=Stock_df['PLow200%'].shift(2)
  Stock_df['PLow600%-2']=Stock_df['PLow600%'].shift(2)

  Stock_df['PHIGH03%-2'] = Stock_df['PHIGH03%'].shift(2)
  Stock_df['PHIGH05%-2'] = Stock_df['PHIGH05%'].shift(2)
  Stock_df['PHIGH10%-2'] = Stock_df['PHIGH10%'].shift(2)
  Stock_df['PHIGH20%-2'] = Stock_df['PHIGH20%'].shift(2)
  Stock_df['PHIGH25%-2']=Stock_df['PHIGH25%'].shift(2)
  Stock_df['PHIGH60%-2']=Stock_df['PHIGH60%'].shift(2)
  Stock_df['PHIGH100%-2']=Stock_df['PHIGH100%'].shift(2)
  Stock_df['PHIGH200%-2']=Stock_df['PHIGH200%'].shift(2)
  Stock_df['PHIGH600%-2']=Stock_df['PHIGH600%'].shift(2)

  Stock_df['PLow60%-3']=Stock_df['PLow60%'].shift(3)

  Stock_df['PLow60%dif'] = Stock_df['PLow60%']-Stock_df['PLow60%-1']
  Stock_df['PLow200%dif']=Stock_df['PLow200%']-Stock_df['PLow200%-1']


def addtablefibonacci_ptc(Stock_df):
  Stock_df['PRangeMaxMin03']=Stock_df['PMax03']-Stock_df['PMin03']
  Stock_df['PRangeMaxMin05']=Stock_df['PMax05']-Stock_df['PMin05']
  Stock_df['PRangeMaxMin10']=Stock_df['PMax10']-Stock_df['PMin10']
  Stock_df['PRangeMaxMin20']=Stock_df['PMax20']-Stock_df['PMin20']
  Stock_df['PRangeMaxMin25']=Stock_df['PMax25']-Stock_df['PMin25']
  Stock_df['PRangeMaxMin60']=Stock_df['PMax60']-Stock_df['PMin60']
  Stock_df['PRangeMaxMin100']=Stock_df['PMax100']-Stock_df['PMin100']
  Stock_df['PRangeMaxMin120']=Stock_df['PMax120']-Stock_df['PMin120']
  Stock_df['PRangeMaxMin200']=Stock_df['PMax200']-Stock_df['PMin200']
  Stock_df['PRangeMaxMin240']=Stock_df['PMax240']-Stock_df['PMin240']
  Stock_df['PRangeMaxMin600']=Stock_df['PMax600']-Stock_df['PMin600']

  Stock_df['PRangeMaxMin03%%']=(Stock_df['PRangeMaxMin03']/Stock_df['PMin03'])*100
  Stock_df['PRangeMaxMin05%']=(Stock_df['PRangeMaxMin05']/Stock_df['PMin05'])*100
  Stock_df['PRangeMaxMin10%']=(Stock_df['PRangeMaxMin10']/Stock_df['PMin10'])*100
  Stock_df['PRangeMaxMin20%']=(Stock_df['PRangeMaxMin20']/Stock_df['PMin20'])*100
  Stock_df['PRangeMaxMin25%']=(Stock_df['PRangeMaxMin25']/Stock_df['PMin25'])*100
  Stock_df['PRangeMaxMin60%']=(Stock_df['PRangeMaxMin60']/Stock_df['PMin60'])*100
  Stock_df['PRangeMaxMin100%']=(Stock_df['PRangeMaxMin100']/Stock_df['PMin100'])*100
  Stock_df['PRangeMaxMin120%']=(Stock_df['PRangeMaxMin120']/Stock_df['PMin120'])*100
  Stock_df['PRangeMaxMin200%']=(Stock_df['PRangeMaxMin200']/Stock_df['PMin200'])*100
  Stock_df['PRangeMaxMin240%']=(Stock_df['PRangeMaxMin240']/Stock_df['PMin240'])*100
  Stock_df['PRangeMaxMin600%']=(Stock_df['PRangeMaxMin600']/Stock_df['PMin600'])*100


  Stock_df['P_as_of03']=Stock_df['close']-Stock_df['PMin03']
  Stock_df['P_as_of05']=Stock_df['close']-Stock_df['PMin05']
  Stock_df['P_as_of10']=Stock_df['close']-Stock_df['PMin10']
  Stock_df['P_as_of20']=Stock_df['close']-Stock_df['PMin20']
  Stock_df['P_as_of25']=Stock_df['close']-Stock_df['PMin25']
  Stock_df['P_as_of60']=Stock_df['close']-Stock_df['PMin60']
  Stock_df['P_as_of100']=Stock_df['close']-Stock_df['PMin100']
  Stock_df['P_as_of120']=Stock_df['close']-Stock_df['PMin120']
  Stock_df['P_as_of200']=Stock_df['close']-Stock_df['PMin200']
  Stock_df['P_as_of240']=Stock_df['close']-Stock_df['PMin240']
  Stock_df['P_as_of600']=Stock_df['close']-Stock_df['PMin600']



  Stock_df['P_fibo_03']=((Stock_df['PRangeMaxMin03']-Stock_df['P_as_of03'])/Stock_df['PRangeMaxMin03'])*100
  Stock_df['P_fibo_05']=((Stock_df['PRangeMaxMin05']-Stock_df['P_as_of05'])/Stock_df['PRangeMaxMin05'])*100
  Stock_df['P_fibo_10']=((Stock_df['PRangeMaxMin10']-Stock_df['P_as_of10'])/Stock_df['PRangeMaxMin10'])*100
  Stock_df['P_fibo_20']=((Stock_df['PRangeMaxMin20']-Stock_df['P_as_of20'])/Stock_df['PRangeMaxMin20'])*100
  Stock_df['P_fibo_25']=((Stock_df['PRangeMaxMin25']-Stock_df['P_as_of25'])/Stock_df['PRangeMaxMin25'])*100
  Stock_df['P_fibo_60']=((Stock_df['PRangeMaxMin60']-Stock_df['P_as_of60'])/Stock_df['PRangeMaxMin60'])*100
  Stock_df['P_fibo_100']=((Stock_df['PRangeMaxMin100']-Stock_df['P_as_of100'])/Stock_df['PRangeMaxMin100'])*100
  Stock_df['P_fibo_120']=((Stock_df['PRangeMaxMin120']-Stock_df['P_as_of120'])/Stock_df['PRangeMaxMin120'])*100
  Stock_df['P_fibo_200']=((Stock_df['PRangeMaxMin200']-Stock_df['P_as_of200'])/Stock_df['PRangeMaxMin200'])*100
  Stock_df['P_fibo_240']=((Stock_df['PRangeMaxMin240']-Stock_df['P_as_of240'])/Stock_df['PRangeMaxMin240'])*100
  Stock_df['P_fibo_600']=((Stock_df['PRangeMaxMin600']-Stock_df['P_as_of600'])/Stock_df['PRangeMaxMin600'])*100

  Stock_df['P_fibo_03-1']= Stock_df['P_fibo_03'].shift(1)
  Stock_df['P_fibo_05-1']= Stock_df['P_fibo_05'].shift(1)
  Stock_df['P_fibo_10-1']= Stock_df['P_fibo_10'].shift(1)
  Stock_df['P_fibo_20-1']= Stock_df['P_fibo_20'].shift(1)
  Stock_df['P_fibo_25-1']= Stock_df['P_fibo_25'].shift(1)
  Stock_df['P_fibo_60-1']= Stock_df['P_fibo_60'].shift(1)
  Stock_df['P_fibo_100-1']= Stock_df['P_fibo_100'].shift(1)
  Stock_df['P_fibo_120-1']= Stock_df['P_fibo_120'].shift(1)
  Stock_df['P_fibo_200-1']= Stock_df['P_fibo_200'].shift(1)
  Stock_df['P_fibo_240-1']= Stock_df['P_fibo_240'].shift(1)
  Stock_df['P_fibo_600-1']= Stock_df['P_fibo_600'].shift(1)

  Stock_df['P_fibo_03-2']= Stock_df['P_fibo_03'].shift(2)
  Stock_df['P_fibo_05-2']= Stock_df['P_fibo_05'].shift(2)
  Stock_df['P_fibo_10-2']= Stock_df['P_fibo_10'].shift(2)
  Stock_df['P_fibo_20-2']= Stock_df['P_fibo_20'].shift(2)
  Stock_df['P_fibo_25-2']= Stock_df['P_fibo_25'].shift(2)
  Stock_df['P_fibo_60-2']= Stock_df['P_fibo_60'].shift(2)
  Stock_df['P_fibo_100-2']= Stock_df['P_fibo_100'].shift(2)
  Stock_df['P_fibo_120-2']= Stock_df['P_fibo_120'].shift(2)
  Stock_df['P_fibo_200-2']= Stock_df['P_fibo_200'].shift(2)
  Stock_df['P_fibo_240-2']= Stock_df['P_fibo_240'].shift(2)
  Stock_df['P_fibo_600-2']= Stock_df['P_fibo_600'].shift(2)

  Stock_df['P_fibo_03-5']= Stock_df['P_fibo_03'].shift(5)
  Stock_df['P_fibo_05-5']= Stock_df['P_fibo_05'].shift(5)
  Stock_df['P_fibo_10-5']= Stock_df['P_fibo_10'].shift(5)
  Stock_df['P_fibo_20-5']= Stock_df['P_fibo_20'].shift(5)
  Stock_df['P_fibo_25-5']= Stock_df['P_fibo_25'].shift(5)
  Stock_df['P_fibo_60-5']= Stock_df['P_fibo_60'].shift(5)
  Stock_df['P_fibo_100-5']= Stock_df['P_fibo_100'].shift(5)
  Stock_df['P_fibo_120-5']= Stock_df['P_fibo_120'].shift(5)
  Stock_df['P_fibo_200-5']= Stock_df['P_fibo_200'].shift(5)
  Stock_df['P_fibo_240-5']= Stock_df['P_fibo_240'].shift(5)
  Stock_df['P_fibo_600-5']= Stock_df['P_fibo_600'].shift(5)

  Stock_df['P_fibo_03-10']= Stock_df['P_fibo_03'].shift(10)
  Stock_df['P_fibo_05-10']= Stock_df['P_fibo_05'].shift(10)
  Stock_df['P_fibo_10-10']= Stock_df['P_fibo_10'].shift(10)
  Stock_df['P_fibo_20-10']= Stock_df['P_fibo_20'].shift(10)
  Stock_df['P_fibo_25-10']= Stock_df['P_fibo_25'].shift(10)
  Stock_df['P_fibo_60-10']= Stock_df['P_fibo_60'].shift(10)
  Stock_df['P_fibo_100-10']= Stock_df['P_fibo_100'].shift(10)
  Stock_df['P_fibo_120-10']= Stock_df['P_fibo_120'].shift(10)
  Stock_df['P_fibo_200-10']= Stock_df['P_fibo_200'].shift(10)
  Stock_df['P_fibo_240-10']= Stock_df['P_fibo_240'].shift(10)
  Stock_df['P_fibo_600-10']= Stock_df['P_fibo_600'].shift(10)




def addtableEMA(Stock_df):
  Stock_df['EMA3'] = Stock_df['close'].ewm(span=3).mean()
  Stock_df['EMA12'] = Stock_df['close'].ewm(span=12).mean()
  Stock_df['EMA26'] = Stock_df['close'].ewm(span=26).mean()
  Stock_df['EMA40'] = Stock_df['close'].ewm(span=40).mean()
  Stock_df['EMA75'] = Stock_df['close'].ewm(span=75).mean()
  Stock_df['EMA89'] = Stock_df['close'].ewm(span=89).mean()

  Stock_df['STD_EMA3'] = Stock_df['close'].ewm(span=3).std()
  Stock_df['STD_EMA12'] = Stock_df['close'].ewm(span=12).std()
  Stock_df['STD_EMA26'] = Stock_df['close'].ewm(span=26).std()
  Stock_df['STD_EMA75'] = Stock_df['close'].ewm(span=75).std()
  Stock_df['STD_EMA89'] = Stock_df['close'].ewm(span=89).std()

  Stock_df['EMA3-1'] = Stock_df['EMA3'].shift(1)
  Stock_df['EMA12-1'] = Stock_df['EMA12'].shift(1)
  Stock_df['EMA26-1'] = Stock_df['EMA26'].shift(1)
  Stock_df['EMA75-1'] = Stock_df['EMA75'].shift(1)
  Stock_df['EMA89-1'] = Stock_df['EMA89'].shift(1)

  Stock_df['STD_EMA3-1'] = Stock_df['STD_EMA3'].shift(1)
  Stock_df['STD_EMA12-1'] = Stock_df['STD_EMA12'].shift(1)
  Stock_df['STD_EMA26-1'] = Stock_df['STD_EMA26'].shift(1)
  Stock_df['STD_EMA75-1'] = Stock_df['STD_EMA75'].shift(1)
  Stock_df['STD_EMA89-1'] = Stock_df['STD_EMA89'].shift(1)


  Stock_df['EMA12%C'] = ((Stock_df['close'] - Stock_df['EMA12'] ) / Stock_df['close']) *100
  Stock_df['EMA26%C'] = ((Stock_df['close'] - Stock_df['EMA26']  ) / Stock_df['close']) *100
  Stock_df['EMA75%C'] = ((Stock_df['close'] - Stock_df['EMA75']   ) / Stock_df['close']) *100
  Stock_df['EMA89%C'] = ((Stock_df['close'] - Stock_df['EMA89']  ) / Stock_df['close']) *100
  Stock_df['EMA12%C-1'] = Stock_df['EMA12%C'].shift(1)
  Stock_df['EMA26%C-1'] = Stock_df['EMA26%C'].shift(1)
  Stock_df['EMA75%C-1'] = Stock_df['EMA75%C'].shift(1)
  Stock_df['EMA89%C-1'] = Stock_df['EMA89%C'].shift(1)
  Stock_df['EMA12-12'] = Stock_df['EMA12'].shift(11)
  Stock_df['EMA26-26'] = Stock_df['EMA26'].shift(25)
  Stock_df['EMA75-75'] = Stock_df['EMA75'].shift(74)
  Stock_df['%EMA12-26'] = ((Stock_df['EMA12'] - Stock_df['EMA26']) / Stock_df['EMA12'])*100

  Stock_df['EMA03'] = Stock_df['close'].ewm(span=3).mean()
  Stock_df['EMA05'] = Stock_df['close'].ewm(span=5).mean()
  Stock_df['EMA10'] = Stock_df['close'].ewm(span=10).mean()
  Stock_df['EMA15'] = Stock_df['close'].ewm(span=15).mean()
  Stock_df['EMA20'] = Stock_df['close'].ewm(span=20).mean()
  Stock_df['EMA25'] = Stock_df['close'].ewm(span=25).mean()
  Stock_df['EMA30'] = Stock_df['close'].ewm(span=30).mean()
  Stock_df['EMA40'] = Stock_df['close'].ewm(span=40).mean()
  Stock_df['EMA60'] = Stock_df['close'].ewm(span=60).mean()
  Stock_df['EMA100'] = Stock_df['close'].ewm(span=100).mean()
  Stock_df['EMA120'] = Stock_df['close'].ewm(span=120).mean()
  Stock_df['EMA200'] = Stock_df['close'].ewm(span=200).mean()
  Stock_df['EMA240'] = Stock_df['close'].ewm(span=240).mean()
  Stock_df['EMA500'] = Stock_df['close'].ewm(span=500).mean()
  Stock_df['STD_EMA05'] = Stock_df['close'].ewm(span=5).std()
  Stock_df['STD_EMA10'] = Stock_df['close'].ewm(span=10).std()
  Stock_df['STD_EMA15'] = Stock_df['close'].ewm(span=15).std()
  Stock_df['STD_EMA20'] = Stock_df['close'].ewm(span=20).std()
  Stock_df['STD_EMA25'] = Stock_df['close'].ewm(span=25).std()
  Stock_df['STD_EMA30'] = Stock_df['close'].ewm(span=30).std()
  Stock_df['STD_EMA40'] = Stock_df['close'].ewm(span=40).std()
  Stock_df['STD_EMA60'] = Stock_df['close'].ewm(span=60).std()
  Stock_df['STD_EMA100'] = Stock_df['close'].ewm(span=100).std()
  Stock_df['STD_EMA120'] = Stock_df['close'].ewm(span=120).std()
  Stock_df['STD_EMA200'] = Stock_df['close'].ewm(span=200).std()
  Stock_df['STD_EMA240'] = Stock_df['close'].ewm(span=240).std()
  Stock_df['STD_EMA500'] = Stock_df['close'].ewm(span=500).std()

  Stock_df['EMA05%C']=(Stock_df['close'] - Stock_df['EMA05'] )/Stock_df['close']*100
  Stock_df['EMA10%C']=(Stock_df['close'] - Stock_df['EMA10'] )/Stock_df['close']*100
  Stock_df['EMA15%C']=(Stock_df['close'] - Stock_df['EMA15'] )/Stock_df['close']*100
  Stock_df['EMA20%C']=(Stock_df['close'] - Stock_df['EMA20'] )/Stock_df['close']*100
  Stock_df['EMA25%C']=(Stock_df['close'] - Stock_df['EMA25'] )/Stock_df['close']*100
  Stock_df['EMA30%C']=(Stock_df['close'] - Stock_df['EMA30'] )/Stock_df['close']*100
  Stock_df['EMA40%C']=(Stock_df['close'] - Stock_df['EMA40'] )/Stock_df['close']*100
  Stock_df['EMA60%C']=(Stock_df['close'] - Stock_df['EMA60'] )/Stock_df['close']*100
  Stock_df['EMA100%C']=(Stock_df['close'] - Stock_df['EMA100'] )/Stock_df['close']*100
  Stock_df['EMA120%C']=(Stock_df['close'] - Stock_df['EMA120'] )/Stock_df['close']*100
  Stock_df['EMA200%C']=(Stock_df['close'] - Stock_df['EMA200'] )/Stock_df['close']*100
  Stock_df['EMA240%C']=(Stock_df['close'] - Stock_df['EMA240'] )/Stock_df['close']*100
  Stock_df['EMA500%C']=(Stock_df['close'] -Stock_df['EMA500'])  /Stock_df['close']*100

  Stock_df['SD/EMA_05'] =Stock_df['STD_EMA05'] /Stock_df['EMA05'] *100
  Stock_df['SD/EMA_10'] =Stock_df['STD_EMA10'] /Stock_df['EMA10'] *100
  Stock_df['SD/EMA_15'] =Stock_df['STD_EMA15'] /Stock_df['EMA15'] *100
  Stock_df['SD/EMA_20'] =Stock_df['STD_EMA20'] /Stock_df['EMA20'] *100
  Stock_df['SD/EMA_25'] =Stock_df['STD_EMA25'] /Stock_df['EMA25'] *100
  Stock_df['SD/EMA_30'] =Stock_df['STD_EMA30'] /Stock_df['EMA30'] *100
  Stock_df['SD/EMA_40'] =Stock_df['STD_EMA40'] /Stock_df['EMA40'] *100
  Stock_df['SD/EMA_60'] =Stock_df['STD_EMA60'] /Stock_df['EMA60'] *100
  Stock_df['SD/EMA_100'] =Stock_df['STD_EMA100'] /Stock_df['EMA100'] *100
  Stock_df['SD/EMA_120'] =Stock_df['STD_EMA120'] /Stock_df['EMA120'] *100
  Stock_df['SD/EMA_200'] =Stock_df['STD_EMA200'] /Stock_df['EMA200'] *100
  Stock_df['SD/EMA_240'] =Stock_df['STD_EMA240'] /Stock_df['EMA240'] *100
  Stock_df['SD/EMA_500'] =Stock_df['STD_EMA500'] /Stock_df['EMA500'] *100


  Stock_df['EMA03-1']=Stock_df['EMA03'].shift(1)
  Stock_df['EMA05-1']=Stock_df['EMA05'].shift(1)
  Stock_df['EMA10-1']=Stock_df['EMA10'].shift(1)
  Stock_df['EMA12-1']=Stock_df['EMA12'].shift(1)
  Stock_df['EMA15-1']=Stock_df['EMA15'].shift(1)
  Stock_df['EMA20-1']=Stock_df['EMA20'].shift(1)
  Stock_df['EMA25-1']=Stock_df['EMA25'].shift(1)
  Stock_df['EMA26-1']=Stock_df['EMA26'].shift(1)
  Stock_df['EMA30-1']=Stock_df['EMA30'].shift(1)
  Stock_df['EMA40-1']=Stock_df['EMA40'].shift(1)
  Stock_df['EMA60-1']=Stock_df['EMA60'].shift(1)
  Stock_df['EMA75-1']=Stock_df['EMA75'].shift(1)
  Stock_df['EMA89-1']=Stock_df['EMA89'].shift(1)
  Stock_df['EMA100-1']=Stock_df['EMA100'].shift(1)
  Stock_df['EMA120-1']=Stock_df['EMA120'].shift(1)
  Stock_df['EMA200-1']=Stock_df['EMA200'].shift(1)
  Stock_df['EMA240-1']=Stock_df['EMA240'].shift(1)
  Stock_df['EMA500-1']=Stock_df['EMA500'].shift(1)
  Stock_df['STD_EMA05-1']=Stock_df['STD_EMA05'].shift(1)
  Stock_df['STD_EMA10-1']=Stock_df['STD_EMA10'].shift(1)
  Stock_df['STD_EMA15-1']=Stock_df['STD_EMA15'].shift(1)
  Stock_df['STD_EMA20-1']=Stock_df['STD_EMA20'].shift(1)
  Stock_df['STD_EMA25-1']=Stock_df['STD_EMA25'].shift(1)
  Stock_df['STD_EMA30-1']=Stock_df['STD_EMA30'].shift(1)
  Stock_df['STD_EMA40-1']=Stock_df['STD_EMA40'].shift(1)
  Stock_df['STD_EMA60-1']=Stock_df['STD_EMA60'].shift(1)
  Stock_df['STD_EMA100-1']=Stock_df['STD_EMA100'].shift(1)
  Stock_df['STD_EMA120-1']=Stock_df['STD_EMA120'].shift(1)
  Stock_df['STD_EMA200-1']=Stock_df['STD_EMA200'].shift(1)
  Stock_df['STD_EMA240-1']=Stock_df['STD_EMA240'].shift(1)
  Stock_df['STD_EMA500-1']=Stock_df['STD_EMA500'].shift(1)
  Stock_df['SD/EMA_05-1'] =Stock_df['SD/EMA_05'].shift(1)
  Stock_df['SD/EMA_10-1'] =Stock_df['SD/EMA_10'].shift(1)
  Stock_df['SD/EMA_15-1'] =Stock_df['SD/EMA_15'].shift(1)
  Stock_df['SD/EMA_20-1'] =Stock_df['SD/EMA_20'].shift(1)
  Stock_df['SD/EMA_25-1'] =Stock_df['SD/EMA_25'].shift(1)
  Stock_df['SD/EMA_30-1'] =Stock_df['SD/EMA_30'].shift(1)
  Stock_df['SD/EMA_40-1'] =Stock_df['SD/EMA_40'].shift(1)
  Stock_df['SD/EMA_60-1'] =Stock_df['SD/EMA_60'].shift(1)
  Stock_df['SD/EMA_100-1'] =Stock_df['SD/EMA_100'].shift(1)
  Stock_df['SD/EMA_120-1'] =Stock_df['SD/EMA_120'].shift(1)
  Stock_df['SD/EMA_200-1'] =Stock_df['SD/EMA_200'].shift(1)
  Stock_df['SD/EMA_240-1'] =Stock_df['SD/EMA_240'].shift(1)
  Stock_df['SD/EMA_500-1'] =Stock_df['SD/EMA_500'].shift(1)

  Stock_df['retune_chg_EMA05'] = Stock_df['retune_chg'].ewm(span=5).mean()
  Stock_df['retune_chg_EMA10'] = Stock_df['retune_chg'].ewm(span=10).mean()
  Stock_df['retune_chg_EMA15'] = Stock_df['retune_chg'].ewm(span=15).mean()
  Stock_df['retune_chg_EMA20'] = Stock_df['retune_chg'].ewm(span=20).mean()
  Stock_df['retune_chg_EMA25'] = Stock_df['retune_chg'].ewm(span=25).mean()
  Stock_df['retune_chg_EMA30'] = Stock_df['retune_chg'].ewm(span=30).mean()
  Stock_df['retune_chg_EMA40'] = Stock_df['retune_chg'].ewm(span=40).mean()
  Stock_df['retune_chg_EMA60'] = Stock_df['retune_chg'].ewm(span=60).mean()
  Stock_df['retune_chg_EMA100'] = Stock_df['retune_chg'].ewm(span=100).mean()
  Stock_df['retune_chg_EMA120'] = Stock_df['retune_chg'].ewm(span=120).mean()
  Stock_df['retune_chg_EMA200'] = Stock_df['retune_chg'].ewm(span=200).mean()
  Stock_df['retune_chg_EMA240'] = Stock_df['retune_chg'].ewm(span=240).mean()
  Stock_df['retune_chg_EMA500'] = Stock_df['retune_chg'].ewm(span=500).mean()
  Stock_df['retune_chg_STD_EMA_EMA05'] = Stock_df['retune_chg'].ewm(span=5).std()
  Stock_df['retune_chg_STD_EMA_EMA10'] = Stock_df['retune_chg'].ewm(span=10).std()
  Stock_df['retune_chg_STD_EMA_EMA15'] = Stock_df['retune_chg'].ewm(span=15).std()
  Stock_df['retune_chg_STD_EMA_EMA20'] = Stock_df['retune_chg'].ewm(span=20).std()
  Stock_df['retune_chg_STD_EMA_EMA25'] = Stock_df['retune_chg'].ewm(span=25).std()
  Stock_df['retune_chg_STD_EMA_EMA30'] = Stock_df['retune_chg'].ewm(span=30).std()
  Stock_df['retune_chg_STD_EMA_EMA40'] = Stock_df['retune_chg'].ewm(span=40).std()
  Stock_df['retune_chg_STD_EMA_EMA60'] = Stock_df['retune_chg'].ewm(span=60).std()
  Stock_df['retune_chg_STD_EMA_EMA100'] = Stock_df['retune_chg'].ewm(span=100).std()
  Stock_df['retune_chg_STD_EMA_EMA120'] = Stock_df['retune_chg'].ewm(span=120).std()
  Stock_df['retune_chg_STD_EMA_EMA200'] = Stock_df['retune_chg'].ewm(span=200).std()
  Stock_df['retune_chg_STD_EMA_EMA240'] = Stock_df['retune_chg'].ewm(span=240).std()
  Stock_df['retune_chg_STD_EMA_EMA500'] = Stock_df['retune_chg'].ewm(span=500).std()

  Stock_df['retune_chg_SD/EMA_05'] =Stock_df['retune_chg_STD_EMA_EMA05'] /Stock_df['retune_chg_EMA05'] *100
  Stock_df['retune_chg_SD/EMA_10'] =Stock_df['retune_chg_STD_EMA_EMA10'] /Stock_df['retune_chg_EMA10'] *100
  Stock_df['retune_chg_SD/EMA_15'] =Stock_df['retune_chg_STD_EMA_EMA15'] /Stock_df['retune_chg_EMA15'] *100
  Stock_df['retune_chg_SD/EMA_20'] =Stock_df['retune_chg_STD_EMA_EMA20'] /Stock_df['retune_chg_EMA20'] *100
  Stock_df['retune_chg_SD/EMA_25'] =Stock_df['retune_chg_STD_EMA_EMA25'] /Stock_df['retune_chg_EMA25'] *100
  Stock_df['retune_chg_SD/EMA_30'] =Stock_df['retune_chg_STD_EMA_EMA30'] /Stock_df['retune_chg_EMA30'] *100
  Stock_df['retune_chg_SD/EMA_40'] =Stock_df['retune_chg_STD_EMA_EMA40'] /Stock_df['retune_chg_EMA40'] *100
  Stock_df['retune_chg_SD/EMA_60'] =Stock_df['retune_chg_STD_EMA_EMA60'] /Stock_df['retune_chg_EMA60'] *100
  Stock_df['retune_chg_SD/EMA_100'] =Stock_df['retune_chg_STD_EMA_EMA100'] /Stock_df['retune_chg_EMA100'] *100
  Stock_df['retune_chg_SD/EMA_120'] =Stock_df['retune_chg_STD_EMA_EMA120'] /Stock_df['retune_chg_EMA120'] *100
  Stock_df['retune_chg_SD/EMA_200'] =Stock_df['retune_chg_STD_EMA_EMA200'] /Stock_df['retune_chg_EMA200'] *100
  Stock_df['retune_chg_SD/EMA_240'] =Stock_df['retune_chg_STD_EMA_EMA240'] /Stock_df['retune_chg_EMA240'] *100
  Stock_df['retune_chg_SD/EMA_500'] =Stock_df['retune_chg_STD_EMA_EMA500'] /Stock_df['retune_chg_EMA500'] *100

  Stock_df['EMA05-2']=Stock_df['EMA05'].shift(2)
  Stock_df['EMA10-2']=Stock_df['EMA10'].shift(2)
  Stock_df['EMA12-2']=Stock_df['EMA12'].shift(2)
  Stock_df['EMA26-2']=Stock_df['EMA25'].shift(2)
  Stock_df['EMA40-2']=Stock_df['EMA40'].shift(2)
  Stock_df['EMA60-2']=Stock_df['EMA60'].shift(2)
  Stock_df['EMA75-2']=Stock_df['EMA75'].shift(2)
  Stock_df['EMA89-2']=Stock_df['EMA89'].shift(2)
  Stock_df['EMA100-2']=Stock_df['EMA100'].shift(2)
  Stock_df['EMA200-2']=Stock_df['EMA200'].shift(2)

  Stock_df['EMA05-5']=Stock_df['EMA05'].shift(5)
  Stock_df['EMA10-5']=Stock_df['EMA10'].shift(5)
  Stock_df['EMA12-5']=Stock_df['EMA12'].shift(5)
  Stock_df['EMA26-5']=Stock_df['EMA25'].shift(5)
  Stock_df['EMA40-5']=Stock_df['EMA40'].shift(5)
  Stock_df['EMA60-5']=Stock_df['EMA60'].shift(5)
  Stock_df['EMA75-5']=Stock_df['EMA75'].shift(5)
  Stock_df['EMA89-5']=Stock_df['EMA89'].shift(5)
  Stock_df['EMA100-5']=Stock_df['EMA100'].shift(5)
  Stock_df['EMA200-5']=Stock_df['EMA200'].shift(5)

  Stock_df['EMA05-6']=Stock_df['EMA05'].shift(6)
  Stock_df['EMA10-6']=Stock_df['EMA10'].shift(6)
  Stock_df['EMA12-6']=Stock_df['EMA12'].shift(6)
  Stock_df['EMA26-6']=Stock_df['EMA25'].shift(6)
  Stock_df['EMA40-6']=Stock_df['EMA40'].shift(6)
  Stock_df['EMA60-6']=Stock_df['EMA60'].shift(6)
  Stock_df['EMA75-6']=Stock_df['EMA75'].shift(6)
  Stock_df['EMA89-6']=Stock_df['EMA89'].shift(6)
  Stock_df['EMA100-6']=Stock_df['EMA100'].shift(6)
  Stock_df['EMA200-6']=Stock_df['EMA200'].shift(6)

  Stock_df['EMA05-10']=Stock_df['EMA05'].shift(10)
  Stock_df['EMA10-10']=Stock_df['EMA10'].shift(10)
  Stock_df['EMA12-10']=Stock_df['EMA12'].shift(10)
  Stock_df['EMA26-10']=Stock_df['EMA25'].shift(10)
  Stock_df['EMA40-10']=Stock_df['EMA40'].shift(10)
  Stock_df['EMA60-10']=Stock_df['EMA60'].shift(10)
  Stock_df['EMA75-10']=Stock_df['EMA75'].shift(10)
  Stock_df['EMA89-10']=Stock_df['EMA89'].shift(10)
  Stock_df['EMA100-10']=Stock_df['EMA100'].shift(10)
  Stock_df['EMA200-10']=Stock_df['EMA200'].shift(10)

  Stock_df['EMA05-11']=Stock_df['EMA05'].shift(11)
  Stock_df['EMA10-11']=Stock_df['EMA10'].shift(11)
  Stock_df['EMA12-11']=Stock_df['EMA12'].shift(11)
  Stock_df['EMA26-11']=Stock_df['EMA25'].shift(11)
  Stock_df['EMA40-11']=Stock_df['EMA40'].shift(11)
  Stock_df['EMA60-11']=Stock_df['EMA60'].shift(11)
  Stock_df['EMA75-11']=Stock_df['EMA75'].shift(11)
  Stock_df['EMA89-11']=Stock_df['EMA89'].shift(11)
  Stock_df['EMA100-11']=Stock_df['EMA100'].shift(11)
  Stock_df['EMA200-11']=Stock_df['EMA200'].shift(11)

  Stock_df['EMA05-40']=Stock_df['EMA05'].shift(40)
  Stock_df['EMA10-40']=Stock_df['EMA10'].shift(40)
  Stock_df['EMA12-40']=Stock_df['EMA12'].shift(40)
  Stock_df['EMA26-40']=Stock_df['EMA25'].shift(40)
  Stock_df['EMA40-40']=Stock_df['EMA40'].shift(40)
  Stock_df['EMA60-40']=Stock_df['EMA60'].shift(40)
  Stock_df['EMA75-40']=Stock_df['EMA75'].shift(40)
  Stock_df['EMA89-40']=Stock_df['EMA89'].shift(40)
  Stock_df['EMA100-40']=Stock_df['EMA100'].shift(40)
  Stock_df['EMA200-40']=Stock_df['EMA200'].shift(40)

  Stock_df['EMA05-75']=Stock_df['EMA05'].shift(75)
  Stock_df['EMA10-75']=Stock_df['EMA10'].shift(75)
  Stock_df['EMA12-75']=Stock_df['EMA12'].shift(75)
  Stock_df['EMA26-75']=Stock_df['EMA25'].shift(75)
  Stock_df['EMA26-40']=Stock_df['EMA40'].shift(75)
  Stock_df['EMA60-75']=Stock_df['EMA60'].shift(75)
  Stock_df['EMA75-75']=Stock_df['EMA75'].shift(75)
  Stock_df['EMA89-75']=Stock_df['EMA89'].shift(75)
  Stock_df['EMA100-75']=Stock_df['EMA100'].shift(75)
  Stock_df['EMA200-75']=Stock_df['EMA200'].shift(75)


def addtablebreakHL(Stock_df):
  Stock_df['BreakPMax05'] = Stock_df['close'] > Stock_df['PMax05-1']
  Stock_df['BreakPMin05'] = Stock_df['close'] < Stock_df['PMin05-1']
  Stock_df['BreakPMax10'] = Stock_df['close'] > Stock_df['PMax10-1']
  Stock_df['BreakPMin10'] = Stock_df['close'] < Stock_df['PMin10-1']
  Stock_df['BreakPMax20'] = Stock_df['close'] > Stock_df['PMax20-1']
  Stock_df['BreakPMin20'] = Stock_df['close'] < Stock_df['PMin20-1']
  Stock_df['BreakPMax25'] = Stock_df['close'] > Stock_df['PMax25-1']
  Stock_df['BreakPMin25'] = Stock_df['close'] < Stock_df['PMin25-1']
  Stock_df['BreakPMax40'] = Stock_df['close'] > Stock_df['PMax40-1']
  Stock_df['BreakPMin40'] = Stock_df['close'] < Stock_df['PMin40-1']
  Stock_df['BreakPMax60'] = Stock_df['close'] > Stock_df['PMax60-1']
  Stock_df['BreakPMin60'] = Stock_df['close'] < Stock_df['PMin60-1']
  Stock_df['BreakPMax100'] = Stock_df['close'] > Stock_df['PMax100-1']
  Stock_df['BreakPMin100'] = Stock_df['close'] < Stock_df['PMin100-1']
  Stock_df['BreakPMax120'] = Stock_df['close'] > Stock_df['PMax120-1']
  Stock_df['BreakPMin120'] = Stock_df['close'] < Stock_df['PMin120-1']
  Stock_df['BreakPMax200'] = Stock_df['close'] > Stock_df['PMax200-1']
  Stock_df['BreakPMin200'] = Stock_df['close'] < Stock_df['PMin200-1']
  Stock_df['BreakPMax600'] = Stock_df['close'] > Stock_df['PMax600-1']
  Stock_df['BreakPMin600'] = Stock_df['close'] < Stock_df['PMin600-1']

  Stock_df['BreakPMin05-1'] = Stock_df['BreakPMin05'].shift(1)
  Stock_df['BreakPMax05-1'] = Stock_df['BreakPMax05'].shift(1)
  Stock_df['BreakPMax10-1'] = Stock_df['BreakPMax10'].shift(1)
  Stock_df['BreakPMin10-1'] = Stock_df['BreakPMin10'].shift(1)
  Stock_df['BreakPMax20-1'] = Stock_df['BreakPMax20'].shift(1)
  Stock_df['BreakPMin20-1'] = Stock_df['BreakPMin20'].shift(1)
  Stock_df['BreakPMax25-1'] = Stock_df['BreakPMax25'].shift(1)
  Stock_df['BreakPMin25-1'] = Stock_df['BreakPMin25'].shift(1)
  Stock_df['BreakPMin40-1'] = Stock_df['BreakPMin40'].shift(1)
  Stock_df['BreakPMax40-1'] = Stock_df['BreakPMax40'].shift(1)
  Stock_df['BreakPMax60-1'] = Stock_df['BreakPMax60'].shift(1)
  Stock_df['BreakPMin60-1'] = Stock_df['BreakPMin60'].shift(1)
  Stock_df['BreakPMax100-1'] = Stock_df['BreakPMax100'].shift(1)
  Stock_df['BreakPMin100-1'] = Stock_df['BreakPMin100'].shift(1)
  Stock_df['BreakPMax120-1'] = Stock_df['BreakPMax120'].shift(1)
  Stock_df['BreakPMin120-1'] = Stock_df['BreakPMin120'].shift(1)
  Stock_df['BreakPMax200-1'] = Stock_df['BreakPMax200'].shift(1)
  Stock_df['BreakPMin200-1'] = Stock_df['BreakPMin200'].shift(1)
  Stock_df['BreakPMax600-1'] = Stock_df['BreakPMax600'].shift(1)
  Stock_df['BreakPMin600-1'] = Stock_df['BreakPMin600'].shift(1)

  Stock_df['BreakPMin05-2'] = Stock_df['BreakPMin05'].shift(2)
  Stock_df['BreakPMax05-2'] = Stock_df['BreakPMax05'].shift(2)
  Stock_df['BreakPMax10-2'] = Stock_df['BreakPMax10'].shift(2)
  Stock_df['BreakPMin10-2'] = Stock_df['BreakPMin10'].shift(2)
  Stock_df['BreakPMax20-2'] = Stock_df['BreakPMax20'].shift(2)
  Stock_df['BreakPMin20-2'] = Stock_df['BreakPMin20'].shift(2)
  Stock_df['BreakPMax25-2'] = Stock_df['BreakPMax25'].shift(2)
  Stock_df['BreakPMin25-2'] = Stock_df['BreakPMin25'].shift(2)
  Stock_df['BreakPMin40-2'] = Stock_df['BreakPMin40'].shift(2)
  Stock_df['BreakPMax40-2'] = Stock_df['BreakPMax40'].shift(2)
  Stock_df['BreakPMax60-2'] = Stock_df['BreakPMax60'].shift(2)
  Stock_df['BreakPMin60-2'] = Stock_df['BreakPMin60'].shift(2)
  Stock_df['BreakPMax100-2'] = Stock_df['BreakPMax100'].shift(2)
  Stock_df['BreakPMin100-2'] = Stock_df['BreakPMin100'].shift(2)
  Stock_df['BreakPMax120-2'] = Stock_df['BreakPMax120'].shift(2)
  Stock_df['BreakPMin120-2'] = Stock_df['BreakPMin120'].shift(2)
  Stock_df['BreakPMax200-2'] = Stock_df['BreakPMax200'].shift(2)
  Stock_df['BreakPMin200-2'] = Stock_df['BreakPMin200'].shift(2)
  Stock_df['BreakPMax600-2'] = Stock_df['BreakPMax600'].shift(2)
  Stock_df['BreakPMin600-2'] = Stock_df['BreakPMin600'].shift(2)

  Stock_df['BreakPMin05-5'] = Stock_df['BreakPMin05'].shift(5)
  Stock_df['BreakPMax05-5'] = Stock_df['BreakPMax05'].shift(5)
  Stock_df['BreakPMax10-5'] = Stock_df['BreakPMax10'].shift(5)
  Stock_df['BreakPMin10-5'] = Stock_df['BreakPMin10'].shift(5)
  Stock_df['BreakPMax20-5'] = Stock_df['BreakPMax20'].shift(5)
  Stock_df['BreakPMin20-5'] = Stock_df['BreakPMin20'].shift(5)
  Stock_df['BreakPMin40-5'] = Stock_df['BreakPMin40'].shift(5)
  Stock_df['BreakPMax40-25'] = Stock_df['BreakPMax40'].shift(5)
  Stock_df['BreakPMax25-5'] = Stock_df['BreakPMax25'].shift(5)
  Stock_df['BreakPMin25-5'] = Stock_df['BreakPMin25'].shift(5)
  Stock_df['BreakPMax60-5'] = Stock_df['BreakPMax60'].shift(5)
  Stock_df['BreakPMin60-5'] = Stock_df['BreakPMin60'].shift(5)
  Stock_df['BreakPMax100-5'] = Stock_df['BreakPMax100'].shift(5)
  Stock_df['BreakPMin100-5'] = Stock_df['BreakPMin100'].shift(5)
  Stock_df['BreakPMax120-5'] = Stock_df['BreakPMax120'].shift(5)
  Stock_df['BreakPMin120-5'] = Stock_df['BreakPMin120'].shift(5)
  Stock_df['BreakPMax200-5'] = Stock_df['BreakPMax200'].shift(5)
  Stock_df['BreakPMin200-5'] = Stock_df['BreakPMin200'].shift(5)
  Stock_df['BreakPMax600-5'] = Stock_df['BreakPMax600'].shift(5)
  Stock_df['BreakPMin600-5'] = Stock_df['BreakPMin600'].shift(5)


def addtableCal(Stock_df):
  Stock_df['closeMax25'] = Stock_df['close'].rolling(window=25).max()
  Stock_df['%closeMax25'] = ((Stock_df['closeMax25'] - Stock_df['close']) / Stock_df['close'])*100
  Stock_df['Maxhigh25'] = Stock_df['high'].rolling(window=25).max()
  Stock_df['Maxhigh25-1'] = Stock_df['Maxhigh25'].shift(1)
  Stock_df['MA25-25'] = Stock_df['MA25'].shift(25)
  Stock_df['SlopeMA25'] = (Stock_df['MA25'] - Stock_df['MA25-25']) / 25

def addtableCalinfo(Stock_df):
  Stock_df['%VolumeTurnoveFloat'] = (Stock_df['volume']/Stock_df['floatShares']) * 100
  Stock_df['%VolumeTurnove'] = (Stock_df['volume']/Stock_df['sharesOutstanding']) *100
  Stock_df['%Mcapturnover'] = (Stock_df['Values']/Stock_df['Mcap'])*100

def addtableADX(Stock_df):
  Stock_df['ADX'] = ta.trend.adx(Stock_df['high'],Stock_df['low'],Stock_df["close"],14,False)
  Stock_df['DI+'] = ta.trend.adx_pos(Stock_df['high'],Stock_df['low'],Stock_df["close"],14,False)
  Stock_df['DI-'] = ta.trend.adx_neg(Stock_df['high'],Stock_df['low'],Stock_df["close"],14,False)
  Stock_df['ADX_Hline1'] = 30
  Stock_df['ADX_Hline2'] = 45
  Stock_df['ADX-1'] = Stock_df['ADX'].shift(1)
  Stock_df['DI+-1'] = Stock_df['DI+'].shift(1)
  Stock_df['DI--1']= Stock_df['DI-'].shift(1)
  Stock_df['ADX-2'] =Stock_df['ADX'].shift(2)
  Stock_df['DI+-2'] = Stock_df['DI+'].shift(2)
  Stock_df['DI--2'] = Stock_df['DI-'].shift(2)



  # Stock_df['EMA12-1'] = Stock_df['close'].ewm(span=12).mean().shift(1)
  # Stock_df['EMA26-1'] = Stock_df['close'].ewm(span=26).mean().shift(1)
  # Stock_df['EMA75-1'] = Stock_df['close'].ewm(span=75).mean().shift(1)

  # for bb

def addtable1_bb(Stock_df):
  Stock_df['rstd'] = Stock_df['close'].rolling(window=25).std()
  Stock_df['upper_band'] = Stock_df['MA25'] + 2 * Stock_df['rstd']
  Stock_df['lower_band'] = Stock_df['MA25'] - 2 * Stock_df['rstd']
  Stock_df['upper_band_1'] = Stock_df['upper_band'].shift(1)
  Stock_df['lower_band_1'] = Stock_df['lower_band'].shift(1)

def addtable1_donc_c(Stock_df):
  Stock_df['hi'] = Stock_df['high']
  Stock_df['lo'] = Stock_df['low']
  Stock_df['uc'] = Stock_df['hi'].rolling(n, min_periods=n).max()
  Stock_df['lc'] = Stock_df['lo'].rolling(n, min_periods=n).min()
  Stock_df['mc'] = (Stock_df['uc']+Stock_df['lc'])/2
  Stock_df['uc-1'] = Stock_df['uc'].shift(1)
  Stock_df['lc-1'] = Stock_df['lc'].shift(1)
  Stock_df['MA25'] = Stock_df['close'].rolling(window=25).mean()

def addtable1_donc_25(Stock_df):
  Stock_df['hi25'] = Stock_df['high']
  Stock_df['lo25'] = Stock_df['low']
  Stock_df['uc25'] = Stock_df['hi'].rolling(25, min_periods=n).max()
  Stock_df['lc25'] = Stock_df['lo'].rolling(25, min_periods=n).min()
  Stock_df['mc25'] = (Stock_df['uc']+Stock_df['lc'])/2
  Stock_df['uc-1_25'] = Stock_df['uc'].shift(25)
  Stock_df['lc-1_25'] = Stock_df['lc'].shift(25)
  # Stock_df['MA60'] = Stock_df['close'].rolling(window=25).mean()

def addtable1_donc_60(Stock_df):
  Stock_df['hi60'] = Stock_df['high']
  Stock_df['lo60'] = Stock_df['low']
  Stock_df['uc60'] = Stock_df['hi'].rolling(60, min_periods=n).max()
  Stock_df['lc60'] = Stock_df['lo'].rolling(60, min_periods=n).min()
  Stock_df['mc60'] = (Stock_df['uc']+Stock_df['lc'])/2
  Stock_df['uc-1_60'] = Stock_df['uc'].shift(60)
  Stock_df['lc-1_60'] = Stock_df['lc'].shift(60)
  # Stock_df['MA200'] = Stock_df['close'].rolling(window=60).mean()

def addtable1_donc_200(Stock_df):
  Stock_df['hi200'] = Stock_df['high']
  Stock_df['lo200'] = Stock_df['low']
  Stock_df['uc200'] = Stock_df['hi'].rolling(200, min_periods=n).max()
  Stock_df['lc200'] = Stock_df['lo'].rolling(200, min_periods=n).min()
  Stock_df['mc200'] = (Stock_df['uc']+Stock_df['lc'])/2
  Stock_df['uc-1_200'] = Stock_df['uc'].shift(200)
  Stock_df['lc-1_200'] = Stock_df['lc'].shift(200)
  # Stock_df['MA200'] = Stock_df['close'].rolling(window=200).mean()

def addtable1_rsi(Stock_df):
  Stock_df['RSI14'] = ta.momentum.rsi(Stock_df["close"], 14,  False)
  Stock_df['RSI14_last'] = ta.momentum.rsi(Stock_df["close"].shift(1), 14,  False)
  Stock_df['RSI14-1'] = Stock_df['RSI14'].shift(1)
  Stock_df['RSI14-2'] = Stock_df['RSI14'].shift(2)
  Stock_df['RSI14-3'] = Stock_df['RSI14'].shift(3)
  Stock_df['RSI14-4'] = Stock_df['RSI14'].shift(4)
  Stock_df['RSI14-5'] = Stock_df['RSI14'].shift(5)
  Stock_df['RSI14-10'] = Stock_df['RSI14'].shift(10)
  Stock_df['RSI14-12'] = Stock_df['RSI14'].shift(12)
  Stock_df['RSI14-14'] = Stock_df['RSI14'].shift(14)
  Stock_df['RSI14-26'] = Stock_df['RSI14'].shift(26)
  Stock_df['RSI14-40'] = Stock_df['RSI14'].shift(40)
  Stock_df['RSI14-75'] = Stock_df['RSI14'].shift(75)
  Stock_df['RSI14-89'] = Stock_df['RSI14'].shift(89)
  Stock_df['RSI25'] = ta.momentum.rsi(Stock_df["close"], 25,  False)
  Stock_df['RSI25_last'] = ta.momentum.rsi(Stock_df["close"].shift(1), 25,  False)
  Stock_df['RSI60'] = ta.momentum.rsi(Stock_df["close"], 60,  False)
  Stock_df['RSI60_last'] = ta.momentum.rsi(Stock_df["close"].shift(1), 60,  False)

def addtable1_MCDX(Stock_df):
  Stock_df['RSI50'] = ta.momentum.rsi(Stock_df["close"], 50,  False)
  Stock_df['MCDX_red'] = (Stock_df['RSI50'] - 50) * 1.5
  Stock_df['RSI30'] = ta.momentum.rsi(Stock_df["close"], 50,  False)
  Stock_df['MCDX_yellow'] = (Stock_df['RSI30'] - 30) * 0.7
  Stock_df['MCDX_green'] = 20 - (Stock_df['MCDX_red']+Stock_df['MCDX_yellow'])
  Stock_df['MCDX_red-1'] = Stock_df['MCDX_red'].shift(1)
  Stock_df['MCDX_yellow-1'] = Stock_df['MCDX_yellow'].shift(1)
  Stock_df['MCDX_green-1'] = Stock_df['MCDX_green'].shift(1)
  Stock_df['MCDX_red-2'] = Stock_df['MCDX_red'].shift(2)
  Stock_df['MCDX_yellow-2'] = Stock_df['MCDX_yellow'].shift(2)
  Stock_df['MCDX_green-2'] = Stock_df['MCDX_green'].shift(2)
  Stock_df['MCDX_red-5'] = Stock_df['MCDX_red'].shift(5)
  Stock_df['MCDX_yellow-5'] = Stock_df['MCDX_yellow'].shift(5)
  Stock_df['MCDX_green-5'] = Stock_df['MCDX_green'].shift(5)
  Stock_df['MCDX_max_red'] = Stock_df['MCDX_red'].rolling(window=10).max()
  Stock_df['MCDX_max_yellow'] = Stock_df['MCDX_yellow'].rolling(window=10).max()
  Stock_df['MCDX_max_green'] = Stock_df['MCDX_green'].rolling(window=10).max()


def addtable_vp600(Stock_df):
  grouped600 = Stock_df.groupby("close")
  dfgroup600 = grouped600[["volume"]].aggregate(np.sum)
  dfgroup600 = dfgroup600.sort_values(by='volume')
  dfgroup600['close_vp600'] = dfgroup600.index
  last_row_vp600 = dfgroup600.tail(1)
  last_row_vp600 = last_row_vp600[['close_vp600']]
  vp600 = last_row_vp600.iloc[[0],[0]]

  for i in last_row_vp600['close_vp600']:
      Stock_df['VP600']  = i

def addtable_vp200(Stock_df):
  Stock_df200 = Stock_df.tail(200)
  grouped200 = Stock_df200.groupby("close")
  dfgroup200 = grouped200[["volume"]].aggregate(np.sum)
  dfgroup200 = dfgroup200.sort_values(by='volume')
  dfgroup200['close_vp200'] = dfgroup200.index
  last_row_vp200 = dfgroup200.tail(1)
  last_row_vp200 = last_row_vp200[['close_vp200']]
  vp200 = last_row_vp200.iloc[[0],[0]]

  for i in last_row_vp200['close_vp200']:
      Stock_df['VP200']  = i

def addtable_vp60(Stock_df):
  Stock_df60 = Stock_df.tail(60)
  grouped60 = Stock_df60.groupby("close")
  dfgroup60 = grouped60[["volume"]].aggregate(np.sum)
  dfgroup60 = dfgroup60.sort_values(by='volume')
  dfgroup60['close_vp60'] = dfgroup60.index
  last_row_vp60 = dfgroup60.tail(1)
  last_row_vp60 = last_row_vp60[['close_vp60']]
  vp60 = last_row_vp60.iloc[[0],[0]]

  for i in last_row_vp60['close_vp60']:
      Stock_df['VP60']  = i

def addtable_vp25(Stock_df):
  Stock_df25 = Stock_df.tail(25)
  grouped25 = Stock_df25.groupby("close")
  dfgroup25 = grouped25[["volume"]].aggregate(np.sum)
  dfgroup25 = dfgroup25.sort_values(by='volume')
  dfgroup25['close_vp25'] = dfgroup25.index
  last_row_vp25 = dfgroup25.tail(1)
  last_row_vp25 = last_row_vp25[['close_vp25']]
  vp25 = last_row_vp25.iloc[[0],[0]]

  for i in last_row_vp25['close_vp25']:
      Stock_df['VP25']  = i


def addtable_downtrend(Stock_df):
  Stock_df['MA05_20TF'] = Stock_df['MA05'] > Stock_df['MA20']
  Stock_df['MA20_25TF'] = Stock_df['MA20'] > Stock_df['MA25']
  Stock_df['MA25_60TF'] = Stock_df['MA25'] > Stock_df['MA60']
  Stock_df['MA60_100TF'] = Stock_df['MA60'] > Stock_df['MA100']
  Stock_df['MA100_200TF'] = Stock_df['MA100'] > Stock_df['MA200']

def addtable_Volatility(Stock_df):
  Stock_df['Volatility%_5d'] = Stock_df['retune_log'].rolling(window=5).std()
  Stock_df['Volatility%_10d'] = Stock_df['retune_log'].rolling(window=10).std()
  Stock_df['Volatility%_20d'] = Stock_df['retune_log'].rolling(window=20).std()
  Stock_df['Volatility%_25d'] = Stock_df['retune_log'].rolling(window=25).std()
  Stock_df['Volatility%_40d'] = Stock_df['retune_log'].rolling(window=40).std()
  Stock_df['Volatility%_60d'] = Stock_df['retune_log'].rolling(window=60).std()
  Stock_df['Volatility%_100d'] = Stock_df['retune_log'].rolling(window=100).std()
  Stock_df['Volatility%_120d'] = Stock_df['retune_log'].rolling(window=120).std()
  Stock_df['Volatility%_200d'] = Stock_df['retune_log'].rolling(window=200).std()
  Stock_df['Volatility%_240d'] = Stock_df['retune_log'].rolling(window=240).std()
  Stock_df['Volatility%_5d-1'] = Stock_df['Volatility%_5d'].shift(1)
  Stock_df['Volatility%_10d-1'] = Stock_df['Volatility%_10d'].shift(1)
  Stock_df['Volatility%_20d-1'] = Stock_df['Volatility%_20d'].shift(1)
  Stock_df['Volatility%_25d-1'] = Stock_df['Volatility%_25d'].shift(1)
  Stock_df['Volatility%_40d-1'] = Stock_df['Volatility%_40d'].shift(1)
  Stock_df['Volatility%_60d-1'] = Stock_df['Volatility%_60d'].shift(1)
  Stock_df['Volatility%_100d-1'] = Stock_df['Volatility%_100d'].shift(1)
  Stock_df['Volatility%_120d-1'] = Stock_df['Volatility%_120d'].shift(1)
  Stock_df['Volatility%_200d-1'] = Stock_df['Volatility%_200d'].shift(1)
  Stock_df['Volatility%_240d-1'] = Stock_df['Volatility%_240d'].shift(1)
  Stock_df['Volatility%_5d-2'] = Stock_df['Volatility%_5d'].shift(2)
  Stock_df['Volatility%_10d-2'] = Stock_df['Volatility%_10d'].shift(2)
  Stock_df['Volatility%_20d-2'] = Stock_df['Volatility%_20d'].shift(2)
  Stock_df['Volatility%_25d-2'] = Stock_df['Volatility%_25d'].shift(2)
  Stock_df['Volatility%_40d-2'] = Stock_df['Volatility%_40d'].shift(2)
  Stock_df['Volatility%_60d-2'] = Stock_df['Volatility%_60d'].shift(2)
  Stock_df['Volatility%_100d-2'] = Stock_df['Volatility%_100d'].shift(2)
  Stock_df['Volatility%_120d-2'] = Stock_df['Volatility%_120d'].shift(2)
  Stock_df['Volatility%_200d-2'] = Stock_df['Volatility%_200d'].shift(2)
  Stock_df['Volatility%_240d-2'] = Stock_df['Volatility%_240d'].shift(2)
  Stock_df['Volatility%_5d-5'] = Stock_df['Volatility%_5d'].shift(5)
  Stock_df['Volatility%_10d-5'] = Stock_df['Volatility%_10d'].shift(5)
  Stock_df['Volatility%_20d-5'] = Stock_df['Volatility%_20d'].shift(5)
  Stock_df['Volatility%_25d-5'] = Stock_df['Volatility%_25d'].shift(5)
  Stock_df['Volatility%_40d-5'] = Stock_df['Volatility%_40d'].shift(5)
  Stock_df['Volatility%_60d-5'] = Stock_df['Volatility%_60d'].shift(5)
  Stock_df['Volatility%_100d-5'] = Stock_df['Volatility%_100d'].shift(5)
  Stock_df['Volatility%_120d-5'] = Stock_df['Volatility%_120d'].shift(5)
  Stock_df['Volatility%_200d-5'] = Stock_df['Volatility%_200d'].shift(5)
  Stock_df['Volatility%_240d-5'] = Stock_df['Volatility%_240d'].shift(5)
  Stock_df['Volatility%_5d-10'] = Stock_df['Volatility%_5d'].shift(10)
  Stock_df['Volatility%_10d-10'] = Stock_df['Volatility%_10d'].shift(10)
  Stock_df['Volatility%_20d-10'] = Stock_df['Volatility%_20d'].shift(10)
  Stock_df['Volatility%_25d-10'] = Stock_df['Volatility%_25d'].shift(10)
  Stock_df['Volatility%_40d-10'] = Stock_df['Volatility%_40d'].shift(10)
  Stock_df['Volatility%_60d-10'] = Stock_df['Volatility%_60d'].shift(10)
  Stock_df['Volatility%_100d-10'] = Stock_df['Volatility%_100d'].shift(10)
  Stock_df['Volatility%_120d-10'] = Stock_df['Volatility%_120d'].shift(10)
  Stock_df['Volatility%_200d-10'] = Stock_df['Volatility%_200d'].shift(10)
  Stock_df['Volatility%_240d-10'] = Stock_df['Volatility%_240d'].shift(10)
  Stock_df['Volatility%_5d-25'] = Stock_df['Volatility%_5d'].shift(25)
  Stock_df['Volatility%_10d-25'] = Stock_df['Volatility%_10d'].shift(25)
  Stock_df['Volatility%_20d-25'] = Stock_df['Volatility%_20d'].shift(25)
  Stock_df['Volatility%_25d-25'] = Stock_df['Volatility%_25d'].shift(25)
  Stock_df['Volatility%_40d-25'] = Stock_df['Volatility%_40d'].shift(25)
  Stock_df['Volatility%_60d-25'] = Stock_df['Volatility%_60d'].shift(25)
  Stock_df['Volatility%_100d-25'] = Stock_df['Volatility%_100d'].shift(25)
  Stock_df['Volatility%_120d-25'] = Stock_df['Volatility%_120d'].shift(25)
  Stock_df['Volatility%_200d-25'] = Stock_df['Volatility%_200d'].shift(25)
  Stock_df['Volatility%_240d-25'] = Stock_df['Volatility%_240d'].shift(25)




def addtable1_rsiweekly(StockW_df):
  StockW_df['RSI14W'] = ta.momentum.rsi(StockW_df["close"], 14,  False)
  StockW_df['RSI14W-1'] = StockW_df['RSI14W'].shift(1)
  StockW_df['RSI14W-2'] = StockW_df['RSI14W'].shift(2)
  StockW_df['RSI14W-3'] = StockW_df['RSI14W'].shift(3)
  StockW_df['RSI14W-4'] = StockW_df['RSI14W'].shift(4)
  StockW_df['RSI14W-5'] = StockW_df['RSI14W'].shift(5)
  StockW_df['RSI14W-10'] = StockW_df['RSI14W'].shift(10)
  StockW_df['RSI14W-12'] = StockW_df['RSI14W'].shift(12)
  StockW_df['RSI14W-14'] = StockW_df['RSI14W'].shift(14)
  StockW_df['RSI14W-26'] = StockW_df['RSI14W'].shift(26)
  StockW_df['RSI14W-40'] = StockW_df['RSI14W'].shift(40)
  StockW_df['RSI14W-75'] = StockW_df['RSI14W'].shift(75)
  StockW_df['RSI14W-89'] = StockW_df['RSI14W'].shift(89)
  # StockW_df['RSI25'] = ta.momentum.rsi(StockW_df["close"], 25,  False)
  # StockW_df['RSI25_last'] = ta.momentum.rsi(StockW_df["close"].shift(1), 25,  False)
  # StockW_df['RSI60'] = ta.momentum.rsi(StockW_df["close"], 60,  False)
  # StockW_df['RSI60_last'] = ta.momentum.rsi(StockW_df["close"].shift(1), 60,  False)


# add condition in col table 1st time
def addlaststocktable(StockL_df):
  StockL_df['2000THB'] = 2000/StockL_df['close']
  StockL_df['4000THB'] = 4000/StockL_df['close']
  StockL_df['check_closeMax25'] = (StockL_df['close'] == StockL_df['closeMax25'])
  StockL_df['%check_closeMax25'] = ((StockL_df['close'] - StockL_df['closeMax25'])/ StockL_df['close']) * 100
  StockL_df['BreakMA5'] = (StockL_df['close'] > StockL_df['MA05']) & (StockL_df['close-1'] < StockL_df['MA05'])
  StockL_df['BreakMA10']=(StockL_df['close']>StockL_df['MA10'])&(StockL_df['close-1']<StockL_df['MA10'])
  StockL_df['BreakMA20']=(StockL_df['close']>StockL_df['MA20'])&(StockL_df['close-1']<StockL_df['MA20'])
  StockL_df['BreakMA25']=(StockL_df['close']>StockL_df['MA25'])&(StockL_df['close-1']<StockL_df['MA25'])
  StockL_df['BreakMA30']=(StockL_df['close']>StockL_df['MA30'])&(StockL_df['close-1']<StockL_df['MA30'])
  StockL_df['BreakMA40']=(StockL_df['close']>StockL_df['MA40'])&(StockL_df['close-1']<StockL_df['MA40'])
  StockL_df['BreakMA60']=(StockL_df['close']>StockL_df['MA60'])&(StockL_df['close-1']<StockL_df['MA60'])
  StockL_df['BreakMA120']=(StockL_df['close']>StockL_df['MA120'])&(StockL_df['close-1']<StockL_df['MA120'])
  StockL_df['BreakMA240']=(StockL_df['close']>StockL_df['MA240'])&(StockL_df['close-1']<StockL_df['MA240'])
  StockL_df['BreakMA500']=(StockL_df['close']>StockL_df['MA500'])&(StockL_df['close-1']<StockL_df['MA500'])

  StockL_df['BreakMaxclose5'] = (StockL_df['close'] > StockL_df['PMax05-1']) & (StockL_df['close-1'] < StockL_df['PMax05-1'])
  StockL_df['BreakMaxclose10']=(StockL_df['close']>StockL_df['PMax10-1'])&(StockL_df['close-1']<StockL_df['PMax10-1'])
  StockL_df['BreakMaxclose20']=(StockL_df['close']>StockL_df['PMax20-1'])&(StockL_df['close-1']<StockL_df['PMax20-1'])
  StockL_df['BreakMaxclose25']=(StockL_df['close']>StockL_df['PMax25-1'])&(StockL_df['close-1']<StockL_df['PMax25-1'])
  StockL_df['BreakMaxclose60']=(StockL_df['close']>StockL_df['PMax60-1'])&(StockL_df['close-1']<StockL_df['PMax60-1'])
  StockL_df['BreakMaxclose100']=(StockL_df['close']>StockL_df['PMax100-1'])&(StockL_df['close-1']<StockL_df['PMax100-1'])
  StockL_df['BreakMaxclose120']=(StockL_df['close']>StockL_df['PMax120-1'])&(StockL_df['close-1']<StockL_df['PMax120-1'])
  StockL_df['BreakMaxclose240']=(StockL_df['close']>StockL_df['PMax240-1'])&(StockL_df['close-1']<StockL_df['PMax240-1'])
  StockL_df['BreakMaxclose600']=(StockL_df['close']>StockL_df['PMax600-1'])&(StockL_df['close-1']<StockL_df['PMax600-1'])

  StockL_df['VolMA60x3'] = (StockL_df['VolMA60'] ) * 3
  StockL_df['VolMA60x2'] = (StockL_df['VolMA60'] ) * 2
  StockL_df['OverVolMAx3'] = (StockL_df['volume'] > StockL_df['VolMA60x3'] )
  StockL_df['OverVolMAx2'] = (StockL_df['volume'] > StockL_df['VolMA60x2'] )
  StockL_df['%chg'] = ((StockL_df['close'] - StockL_df['close-1'])/StockL_df['close-1']) *100
  StockL_df['%chg-1'] = ((StockL_df['close-1'] - StockL_df['close-2'])/StockL_df['close-2']) *100
  StockL_df['%chginday'] = ((StockL_df['close'] - StockL_df['open'])/StockL_df['open']) *100
  StockL_df['Break_UC'] = (StockL_df['uc-1'] < StockL_df['uc'])
  StockL_df['Break_LC'] = (StockL_df['lc-1'] > StockL_df['lc'])
  # StockL_df['vp60%'] = (StockL_df['close'] - StockL_df['VP60']) / StockL_df['VP60']
  # StockL_df['vp200%'] = (StockL_df['close'] - StockL_df['VP200']) / StockL_df['VP200']
  # StockL_df['vp600%'] = (StockL_df['close'] - StockL_df['VP600']) / StockL_df['VP600']
  StockL_df['RSI_up'] = (StockL_df['RSI14'] > StockL_df['RSI25'])&(StockL_df['RSI14'] > StockL_df['RSI60'])&(StockL_df['RSI25'] > StockL_df['RSI60'])

  StockL_df['RSI14_thoughtsback'] = (StockL_df['RSI14'] < 70) & ((StockL_df['RSI14-1'] > 70) | (StockL_df['RSI14-2'] > 70) | (StockL_df['RSI14-3'] > 70) | (StockL_df['RSI14-4'] > 70))

  StockL_df['ZoneUpper_fibo_03']=( StockL_df['P_fibo_03']<= 20)
  StockL_df['ZoneUpper_fibo_05']=( StockL_df['P_fibo_05']<= 20)
  StockL_df['ZoneUpper_fibo_10']=( StockL_df['P_fibo_10']<= 20)
  StockL_df['ZoneUpper_fibo_20']=( StockL_df['P_fibo_20']<= 20)
  StockL_df['ZoneUpper_fibo_25']=( StockL_df['P_fibo_25']<= 20)
  StockL_df['ZoneUpper_fibo_60']=( StockL_df['P_fibo_60']<= 20)
  StockL_df['ZoneUpper_fibo_100']=( StockL_df['P_fibo_100']<= 20)
  StockL_df['ZoneUpper_fibo_120']=( StockL_df['P_fibo_120']<= 20)
  StockL_df['ZoneUpper_fibo_200']=( StockL_df['P_fibo_200']<= 20)
  StockL_df['ZoneUpper_fibo_240']=( StockL_df['P_fibo_240']<= 20)
  StockL_df['ZoneUpper_fibo_600']=( StockL_df['P_fibo_600']<= 20)

  StockL_df['Zone236_fibo_03']=( StockL_df['P_fibo_03']>20)&( StockL_df['P_fibo_03']<26)
  StockL_df['Zone236_fibo_05']=( StockL_df['P_fibo_05']>20)&( StockL_df['P_fibo_05']<26)
  StockL_df['Zone236_fibo_10']=( StockL_df['P_fibo_10']>20)&( StockL_df['P_fibo_10']<26)
  StockL_df['Zone236_fibo_20']=( StockL_df['P_fibo_20']>20)&( StockL_df['P_fibo_20']<26)
  StockL_df['Zone236_fibo_25']=( StockL_df['P_fibo_25']>20)&( StockL_df['P_fibo_25']<26)
  StockL_df['Zone236_fibo_60']=( StockL_df['P_fibo_60']>20)&( StockL_df['P_fibo_60']<26)
  StockL_df['Zone236_fibo_100']=( StockL_df['P_fibo_100']>20)&( StockL_df['P_fibo_100']<26)
  StockL_df['Zone236_fibo_120']=( StockL_df['P_fibo_120']>20)&( StockL_df['P_fibo_120']<26)
  StockL_df['Zone236_fibo_200']=( StockL_df['P_fibo_200']>20)&( StockL_df['P_fibo_200']<26)
  StockL_df['Zone236_fibo_240']=( StockL_df['P_fibo_240']>20)&( StockL_df['P_fibo_240']<26)
  StockL_df['Zone236_fibo_600']=( StockL_df['P_fibo_600']>20)&( StockL_df['P_fibo_600']<26)

  StockL_df['Zone382_fibo_03']=( StockL_df['P_fibo_03']>35)&( StockL_df['P_fibo_03']<41)
  StockL_df['Zone382_fibo_05']=( StockL_df['P_fibo_05']>35)&( StockL_df['P_fibo_05']<41)
  StockL_df['Zone382_fibo_10']=( StockL_df['P_fibo_10']>35)&( StockL_df['P_fibo_10']<41)
  StockL_df['Zone382_fibo_20']=( StockL_df['P_fibo_20']>35)&( StockL_df['P_fibo_20']<41)
  StockL_df['Zone382_fibo_25']=( StockL_df['P_fibo_25']>35)&( StockL_df['P_fibo_25']<41)
  StockL_df['Zone382_fibo_60']=( StockL_df['P_fibo_60']>35)&( StockL_df['P_fibo_60']<41)
  StockL_df['Zone382_fibo_100']=( StockL_df['P_fibo_100']>35)&( StockL_df['P_fibo_100']<41)
  StockL_df['Zone382_fibo_120']=( StockL_df['P_fibo_120']>35)&( StockL_df['P_fibo_120']<41)
  StockL_df['Zone382_fibo_200']=( StockL_df['P_fibo_200']>35)&( StockL_df['P_fibo_200']<41)
  StockL_df['Zone382_fibo_240']=( StockL_df['P_fibo_240']>35)&( StockL_df['P_fibo_240']<41)
  StockL_df['Zone382_fibo_600']=( StockL_df['P_fibo_600']>35)&( StockL_df['P_fibo_600']<41)

  StockL_df['Zone50_fibo_03']=( StockL_df['P_fibo_03']>47)&( StockL_df['P_fibo_03']<53)
  StockL_df['Zone50_fibo_05']=( StockL_df['P_fibo_05']>47)&( StockL_df['P_fibo_05']<53)
  StockL_df['Zone50_fibo_10']=( StockL_df['P_fibo_10']>47)&( StockL_df['P_fibo_10']<53)
  StockL_df['Zone50_fibo_20']=( StockL_df['P_fibo_20']>47)&( StockL_df['P_fibo_20']<53)
  StockL_df['Zone50_fibo_25']=( StockL_df['P_fibo_25']>47)&( StockL_df['P_fibo_25']<53)
  StockL_df['Zone50_fibo_60']=( StockL_df['P_fibo_60']>47)&( StockL_df['P_fibo_60']<53)
  StockL_df['Zone50_fibo_100']=( StockL_df['P_fibo_100']>47)&( StockL_df['P_fibo_100']<53)
  StockL_df['Zone50_fibo_120']=( StockL_df['P_fibo_120']>47)&( StockL_df['P_fibo_120']<53)
  StockL_df['Zone50_fibo_200']=( StockL_df['P_fibo_200']>47)&( StockL_df['P_fibo_200']<53)
  StockL_df['Zone50_fibo_240']=( StockL_df['P_fibo_240']>47)&( StockL_df['P_fibo_240']<53)
  StockL_df['Zone50_fibo_600']=( StockL_df['P_fibo_600']>47)&( StockL_df['P_fibo_600']<53)

  StockL_df['Zone618_fibo_03']=( StockL_df['P_fibo_03']>58)&( StockL_df['P_fibo_03']<64)
  StockL_df['Zone618_fibo_05']=( StockL_df['P_fibo_05']>58)&( StockL_df['P_fibo_05']<64)
  StockL_df['Zone618_fibo_10']=( StockL_df['P_fibo_10']>58)&( StockL_df['P_fibo_10']<64)
  StockL_df['Zone618_fibo_20']=( StockL_df['P_fibo_20']>58)&( StockL_df['P_fibo_20']<64)
  StockL_df['Zone618_fibo_25']=( StockL_df['P_fibo_25']>58)&( StockL_df['P_fibo_25']<64)
  StockL_df['Zone618_fibo_60']=( StockL_df['P_fibo_60']>58)&( StockL_df['P_fibo_60']<64)
  StockL_df['Zone618_fibo_100']=( StockL_df['P_fibo_100']>58)&( StockL_df['P_fibo_100']<64)
  StockL_df['Zone618_fibo_120']=( StockL_df['P_fibo_120']>58)&( StockL_df['P_fibo_120']<64)
  StockL_df['Zone618_fibo_200']=( StockL_df['P_fibo_200']>58)&( StockL_df['P_fibo_200']<64)
  StockL_df['Zone618_fibo_240']=( StockL_df['P_fibo_240']>58)&( StockL_df['P_fibo_240']<64)
  StockL_df['Zone618_fibo_600']=( StockL_df['P_fibo_600']>58)&( StockL_df['P_fibo_600']<64)

  StockL_df['Zone786_fibo_03']=( StockL_df['P_fibo_03']>75)&( StockL_df['P_fibo_03']<81)
  StockL_df['Zone786_fibo_05']=( StockL_df['P_fibo_05']>75)&( StockL_df['P_fibo_05']<81)
  StockL_df['Zone786_fibo_10']=( StockL_df['P_fibo_10']>75)&( StockL_df['P_fibo_10']<81)
  StockL_df['Zone786_fibo_20']=( StockL_df['P_fibo_20']>75)&( StockL_df['P_fibo_20']<81)
  StockL_df['Zone786_fibo_25']=( StockL_df['P_fibo_25']>75)&( StockL_df['P_fibo_25']<81)
  StockL_df['Zone786_fibo_60']=( StockL_df['P_fibo_60']>75)&( StockL_df['P_fibo_60']<81)
  StockL_df['Zone786_fibo_100']=( StockL_df['P_fibo_100']>75)&( StockL_df['P_fibo_100']<81)
  StockL_df['Zone786_fibo_120']=( StockL_df['P_fibo_120']>75)&( StockL_df['P_fibo_120']<81)
  StockL_df['Zone786_fibo_200']=( StockL_df['P_fibo_200']>75)&( StockL_df['P_fibo_200']<81)
  StockL_df['Zone786_fibo_240']=( StockL_df['P_fibo_240']>75)&( StockL_df['P_fibo_240']<81)
  StockL_df['Zone786_fibo_600']=( StockL_df['P_fibo_600']>75)&( StockL_df['P_fibo_600']<81)

  StockL_df['ZoneLower_fibo_03']= (StockL_df['P_fibo_03']>=81)
  StockL_df['ZoneLower_fibo_05']= (StockL_df['P_fibo_05']>=81)
  StockL_df['ZoneLower_fibo_10']= (StockL_df['P_fibo_10']>=81)
  StockL_df['ZoneLower_fibo_20']= (StockL_df['P_fibo_20']>=81)
  StockL_df['ZoneLower_fibo_25']= (StockL_df['P_fibo_25']>=81)
  StockL_df['ZoneLower_fibo_60']= (StockL_df['P_fibo_60']>=81)
  StockL_df['ZoneLower_fibo_100']= (StockL_df['P_fibo_100']>=81)
  StockL_df['ZoneLower_fibo_120']= (StockL_df['P_fibo_120']>=81)
  StockL_df['ZoneLower_fibo_200']= (StockL_df['P_fibo_200']>=81)
  StockL_df['ZoneLower_fibo_240']= (StockL_df['P_fibo_240']>=81)
  StockL_df['ZoneLower_fibo_600']= (StockL_df['P_fibo_600']>=81)


  StockL_df['MA200Uptrend'] = (StockL_df['MA15'] > StockL_df['MA25']) & (StockL_df['MA25'] > StockL_df['MA60']) & (StockL_df['MA60']  > StockL_df['MA120'])   &(StockL_df['MA120']  > StockL_df['MA200'])
  StockL_df['MA200Downtrend'] =(StockL_df['MA15'] < StockL_df['MA25']) & (StockL_df['MA25'] < StockL_df['MA60'])& (StockL_df['MA60']  < StockL_df['MA120'])& (StockL_df['MA120']  < StockL_df['MA200'])
  StockL_df['CDC'] = (StockL_df['EMA12'] > StockL_df['EMA26'] )
  StockL_df['CDC_last'] = (StockL_df['EMA12-1'] < StockL_df['EMA26-1'])
  StockL_df['CDC_break'] = (StockL_df['EMA12']>StockL_df['EMA26'])&(StockL_df['EMA12-1']<StockL_df['EMA26-1'])
  StockL_df['CDC_break-1'] = StockL_df['CDC_break'].shift(1)
  StockL_df['CDC_break-2'] = StockL_df['CDC_break'].shift(2)

  StockL_df['EMA12_Turning'] = (StockL_df['EMA12%C'] > 0) & (StockL_df['EMA12%C-1'] < 0)
  # StockL_df['EMA26_Turning'] = (StockL_df['EMA26%Close'] > 0) & (StockL_df['EMA26%Close-1'] < 0)
  StockL_df['EMA12%'] = ((StockL_df['EMA12'] - StockL_df['EMA12-12']) / StockL_df['EMA12-12']) * 100
  StockL_df['EMA26%'] = ((StockL_df['EMA26'] - StockL_df['EMA26-26']) / StockL_df['EMA26-26']) * 100
  StockL_df['BB upper_band break'] = ((StockL_df['upper_band'] < StockL_df['close'])&(StockL_df['upper_band_1'] > StockL_df['close-1']))
  StockL_df['BB lower_band break'] = ((StockL_df['lower_band'] > StockL_df['close'])&(StockL_df['lower_band_1'] < StockL_df['close-1']))
  StockL_df['volmax25TF'] = (StockL_df['volume'] == StockL_df['VolMax25'])
  StockL_df['volmax60TF'] = (StockL_df['volume'] == StockL_df['VolMax60'])
  StockL_df['volmax100TF'] = (StockL_df['volume'] == StockL_df['VolMax100'])
  StockL_df['volmax200TF'] = (StockL_df['volume'] == StockL_df['VolMax200'])
  StockL_df['volmax600TF'] = (StockL_df['volume'] == StockL_df['VolMax600'])
  StockL_df['volmax25TF-1'] = (StockL_df['volume-1'] == StockL_df['VolMax-1_25'])
  StockL_df['volmax60TF-1'] = (StockL_df['volume-1'] == StockL_df['VolMax-1_60'])
  StockL_df['volmax100TF-1'] = (StockL_df['volume-1'] == StockL_df['VolMax-1_100'])
  StockL_df['volmax200TF-1'] = (StockL_df['volume-1'] == StockL_df['VolMax-1_200'])
  StockL_df['volmax600TF-1'] = (StockL_df['volume-1'] == StockL_df['VolMax-1_600'])
  StockL_df['volmax25TF-2'] = (StockL_df['volume-2'] == StockL_df['VolMax-2_25'])
  StockL_df['volmax60TF-2'] = (StockL_df['volume-2'] == StockL_df['VolMax-2_60'])
  StockL_df['volmax100TF-2'] = (StockL_df['volume-2'] == StockL_df['VolMax-2_100'])
  StockL_df['volmax200TF-2'] = (StockL_df['volume-2'] == StockL_df['VolMax-2_200'])
  StockL_df['volmax600TF-2'] = (StockL_df['volume-2'] == StockL_df['VolMax-2_600'])
  StockL_df['volmax25TF-3'] = (StockL_df['volume-3'] == StockL_df['VolMax-3_25'])
  StockL_df['volmax60TF-3'] = (StockL_df['volume-3'] == StockL_df['VolMax-3_60'])
  StockL_df['volmax100TF-3'] = (StockL_df['volume-3'] == StockL_df['VolMax-3_100'])
  StockL_df['volmax200TF-3'] = (StockL_df['volume-3'] == StockL_df['VolMax-3_200'])
  StockL_df['volmax600TF-3'] = (StockL_df['volume-3'] == StockL_df['VolMax-3_600'])
  StockL_df['volmax25TF-5'] = (StockL_df['volume-5'] == StockL_df['VolMax-5_25'])
  StockL_df['volmax60TF-5'] = (StockL_df['volume-5'] == StockL_df['VolMax-5_60'])
  StockL_df['volmax100TF-5'] = (StockL_df['volume-5'] == StockL_df['VolMax-5_100'])
  StockL_df['volmax200TF-5'] = (StockL_df['volume-5'] == StockL_df['VolMax-5_200'])
  StockL_df['volmax600TF-5'] = (StockL_df['volume-5'] == StockL_df['VolMax-5_600'])
  StockL_df['volmax25TF-10'] = (StockL_df['volume-10'] == StockL_df['VolMax-10_25'])
  StockL_df['volmax60TF-10'] = (StockL_df['volume-10'] == StockL_df['VolMax-10_60'])
  StockL_df['volmax100TF-10'] = (StockL_df['volume-10'] == StockL_df['VolMax-10_100'])
  StockL_df['volmax200TF-10'] = (StockL_df['volume-10'] == StockL_df['VolMax-10_200'])
  StockL_df['volmax600TF-10'] = (StockL_df['volume-10'] == StockL_df['VolMax-10_600'])

  StockL_df['Val25_60_TF'] = ((StockL_df['Values']>StockL_df['ValMA25'])&(StockL_df['Values']>StockL_df['ValMA60']))
  StockL_df['Vol25_60_TF'] = ((StockL_df['volume']>StockL_df['VolMA25'])&(StockL_df['volume']>StockL_df['VolMA60']))


# xxx

  StockL_df['%chgclose_ema12'] = ((StockL_df['close'] - StockL_df['EMA12'])/StockL_df['close']) *100
  StockL_df['%chgclose_ema26'] = ((StockL_df['close'] - StockL_df['EMA26'])/StockL_df['close']) *100

  StockL_df['EMA05_break'] = (StockL_df['close']>StockL_df['EMA05'])&(StockL_df['close-1']<StockL_df['EMA05-1'])
  StockL_df['EMA10_break'] = (StockL_df['close']>StockL_df['EMA10'])&(StockL_df['close-1']<StockL_df['EMA10-1'])
  StockL_df['EMA12_break'] = (StockL_df['close']>StockL_df['EMA12'])&(StockL_df['close-1']<StockL_df['EMA12-1'])
  StockL_df['EMA26_break'] = (StockL_df['close']>StockL_df['EMA26'])&(StockL_df['close-1']<StockL_df['EMA26-1'])
  StockL_df['EMA40_break'] = (StockL_df['close']>StockL_df['EMA40'])&(StockL_df['close-1']<StockL_df['EMA40-1'])
  StockL_df['EMA40_break_down'] = (StockL_df['close']<StockL_df['EMA40'])&(StockL_df['close-1']>StockL_df['EMA40-1'])
  StockL_df['EMA75_break'] = (StockL_df['close']>StockL_df['EMA75'])&(StockL_df['close-1']<StockL_df['EMA75-1'])
  StockL_df['EMA89_break'] = (StockL_df['close']>StockL_df['EMA89'])&(StockL_df['close-1']<StockL_df['EMA89-1'])
  StockL_df['EMA200_break'] = (StockL_df['close']>StockL_df['EMA200'])&(StockL_df['close-1']<StockL_df['EMA200-1'])

  StockL_df['EMA05_break-1'] = (StockL_df['close-1']>StockL_df['EMA05-1'])&(StockL_df['close-2']<StockL_df['EMA05-2'])
  StockL_df['EMA10_break-1'] = (StockL_df['close-1']>StockL_df['EMA10-1'])&(StockL_df['close-2']<StockL_df['EMA10-2'])
  StockL_df['EMA12_break-1'] = (StockL_df['close-1']>StockL_df['EMA12-1'])&(StockL_df['close-2']<StockL_df['EMA12-2'])
  StockL_df['EMA26_break-1'] = (StockL_df['close-1']>StockL_df['EMA26-1'])&(StockL_df['close-2']<StockL_df['EMA26-2'])
  StockL_df['EMA40_break-1'] = (StockL_df['close-1']>StockL_df['EMA40-1'])&(StockL_df['close-2']<StockL_df['EMA40-2'])
  StockL_df['EMA40_break_down-1'] = (StockL_df['close-1']<StockL_df['EMA40-1'])&(StockL_df['close-2']>StockL_df['EMA40-2'])
  StockL_df['EMA75_break-1'] = (StockL_df['close-1']>StockL_df['EMA75-1'])&(StockL_df['close-2']<StockL_df['EMA75-2'])
  StockL_df['EMA89_break-1'] = (StockL_df['close-1']>StockL_df['EMA89-1'])&(StockL_df['close-2']<StockL_df['EMA89-2'])
  StockL_df['EMA200_break-1'] = (StockL_df['close-1']>StockL_df['EMA200-1'])&(StockL_df['close-2']<StockL_df['EMA200-2'])

  StockL_df['EMA05_break-5'] = (StockL_df['close-5']>StockL_df['EMA05-5'])&(StockL_df['close-6']<StockL_df['EMA05-6'])
  StockL_df['EMA10_break-5'] = (StockL_df['close-5']>StockL_df['EMA10-5'])&(StockL_df['close-6']<StockL_df['EMA10-6'])
  StockL_df['EMA12_break-5'] = (StockL_df['close-5']>StockL_df['EMA12-5'])&(StockL_df['close-6']<StockL_df['EMA12-6'])
  StockL_df['EMA26_break-5'] = (StockL_df['close-5']>StockL_df['EMA26-5'])&(StockL_df['close-6']<StockL_df['EMA26-6'])
  StockL_df['EMA40_break-5'] = (StockL_df['close-5']>StockL_df['EMA40-5'])&(StockL_df['close-6']<StockL_df['EMA40-6'])
  StockL_df['EMA40_break_down-5'] = (StockL_df['close-5']<StockL_df['EMA40-5'])&(StockL_df['close-6']>StockL_df['EMA40-6'])
  StockL_df['EMA75_break-5'] = (StockL_df['close-5']>StockL_df['EMA75-5'])&(StockL_df['close-6']<StockL_df['EMA75-6'])
  StockL_df['EMA89_break-5'] = (StockL_df['close-5']>StockL_df['EMA89-5'])&(StockL_df['close-6']<StockL_df['EMA89-6'])
  StockL_df['EMA200_break-5'] = (StockL_df['close-5']>StockL_df['EMA200-5'])&(StockL_df['close-6']<StockL_df['EMA200-6'])


  StockL_df['EMA05_break-10'] = (StockL_df['close-10']>StockL_df['EMA05-10'])&(StockL_df['close-11']<StockL_df['EMA05-11'])
  StockL_df['EMA10_break-10'] = (StockL_df['close-10']>StockL_df['EMA10-10'])&(StockL_df['close-11']<StockL_df['EMA10-11'])
  StockL_df['EMA12_break-10'] = (StockL_df['close-10']>StockL_df['EMA12-10'])&(StockL_df['close-11']<StockL_df['EMA12-11'])
  StockL_df['EMA26_break-10'] = (StockL_df['close-10']>StockL_df['EMA26-10'])&(StockL_df['close-11']<StockL_df['EMA26-11'])
  StockL_df['EMA40_break-10'] = (StockL_df['close-10']>StockL_df['EMA40-10'])&(StockL_df['close-11']<StockL_df['EMA40-11'])
  StockL_df['EMA40_break_down-10'] = (StockL_df['close-10']>StockL_df['EMA40-10'])&(StockL_df['close-11']<StockL_df['EMA40-11'])
  StockL_df['EMA75_break-10'] = (StockL_df['close-10']>StockL_df['EMA75-10'])&(StockL_df['close-11']<StockL_df['EMA75-11'])
  StockL_df['EMA89_break-10'] = (StockL_df['close-10']>StockL_df['EMA89-10'])&(StockL_df['close-11']<StockL_df['EMA89-11'])
  StockL_df['EMA200_break-10'] = (StockL_df['close-10']>StockL_df['EMA200-10'])&(StockL_df['close-11']<StockL_df['EMA200-11'])

  # StockL_df['Gap%VP600'] = ((StockL_df['close'] - StockL_df['VP600']) / StockL_df['close']) * 100
  # StockL_df['Gap%VP200'] = ((StockL_df['close'] - StockL_df['VP200']) / StockL_df['close']) * 100
  # StockL_df['Gap%VP60'] = ((StockL_df['close'] - StockL_df['VP60']) / StockL_df['close']) * 100
  # StockL_df['Gap%VP25'] = ((StockL_df['close'] - StockL_df['VP25']) / StockL_df['close']) * 100
  # StockL_df['EMA12%-EMA26%'] =(StockL_df['EMA12%']- StockL_df['EMA26%'])

  StockL_df['CDC_break_down'] = (StockL_df['EMA12']<StockL_df['EMA26'])&(StockL_df['EMA12-1']>StockL_df['EMA26-1'])
  StockL_df['EMA12_break_down'] = (StockL_df['close']<StockL_df['EMA12'])&(StockL_df['close-1']>StockL_df['EMA12-1'])
  StockL_df['EMA26_break_down'] = (StockL_df['close']<StockL_df['EMA26'])&(StockL_df['close-1']>StockL_df['EMA26-1'])
  StockL_df['EMA75_break_down'] = (StockL_df['close']<StockL_df['EMA75'])&(StockL_df['close-1']>StockL_df['EMA75-1'])
  StockL_df['EMA89_break_down'] = (StockL_df['close']<StockL_df['EMA89'])&(StockL_df['close-1']>StockL_df['EMA89-1'])


  StockL_df['heikin_ashi_check'] = (StockL_df['EMA3']<StockL_df['EMA12'])&(StockL_df['close-1']>StockL_df['EMA12-1'])
  StockL_df['1st green EMA10 heikin_ashi_check'] = (StockL_df['HA_Close'] > StockL_df['HA_Open']) & (StockL_df['HA_Close-1'] < StockL_df['HA_Open-1']) & (StockL_df['HA_Close'] > StockL_df['HA_Open-1'] ) &  (StockL_df['PMin60%-1'] > 2 )  &  (StockL_df['HA_Close'] > StockL_df['EMA10'])
  StockL_df['1st green_heikin_ashi_check'] = (StockL_df['HA_Close'] > StockL_df['HA_Open']) & (StockL_df['HA_Close-1'] < StockL_df['HA_Open-1']) & (StockL_df['HA_Close'] > StockL_df['HA_Open-1'] )
  StockL_df['2nd green_heikin_ashi_check'] = (StockL_df['HA_Close'] > StockL_df['HA_Open']) & (StockL_df['HA_Close-1'] > StockL_df['HA_Open-1']) & (StockL_df['HA_Close-2'] < StockL_df['HA_Open-2']) & (StockL_df['HA_Close'] > StockL_df['HA_Open'])
  StockL_df['1st green_heikin_ashi_check-1'] = StockL_df['1st green EMA10 heikin_ashi_check'].shift(1)
  StockL_df['1st green_heikin_ashi_check-2'] = StockL_df['1st green EMA10 heikin_ashi_check'].shift(2)
  StockL_df['2nd green_heikin_ashi_check-1'] = StockL_df['2nd green_heikin_ashi_check'].shift(1)
  StockL_df['2nd green_heikin_ashi_check-2'] = StockL_df['2nd green_heikin_ashi_check'].shift(2)



  StockL_df.sort_values (by=['Mcap'], ascending=False, inplace=True)
  StockL_df['rank Mcap'] = range(1, len(StockL_df) + 1)

  StockL_df.sort_values (by=['Values'], ascending=False, inplace=True)
  StockL_df['rank Values'] = range(1, len(StockL_df) + 1)


  StockL_df.sort_values (by=['retune_chg'], ascending=False, inplace=True)
  StockL_df['rank retune_chg'] = range(1, len(StockL_df) + 1)
  return table2

def addltabelCDC(StockL_df):
  df_CDC =  StockL_df[(StockL_df['CDC'] == 'TRUE')]

  return df_CDC

def addltabelzoneRSI(StockL_df):
  df_CDC =  StockL_df[(StockL_df['zoneRSI'] == 'TRUE')]

  return df_CDC


########################### Graph table section ###################################
# add daily data for graph
def addtablegraphma2560bb_d1(stcknr_df):
  stcknr_df['datetime_'] = stcknr_df.index.date
  for i in ['open', 'high', 'close', 'low']: # loop stock for change type
    stcknr_df[i] = stcknr_df[i].astype('float64')
  # cal indictor
  stcknr_df['MA25'] = stcknr_df['close'].rolling(window=25).mean()
  stcknr_df['MA60'] = stcknr_df['close'].rolling(window=60).mean()
  stcknr_df['MA25vol'] = stcknr_df['volume'].rolling(window=20).mean()
  stcknr_df['MA60vol'] = stcknr_df['volume'].rolling(window=60).mean()
  stcknr_df['rstd'] = stcknr_df['close'].rolling(window=25).std()

  stcknr_df['upper_band'] = stcknr_df['MA25'] + 2 * stcknr_df['rstd']
  stcknr_df['lower_band'] = stcknr_df['MA25'] - 2 * stcknr_df['rstd']

  stcknr_df['close-1'] = stcknr_df['close'].shift(1)
  # stcknr_df['datetime_'] = stcknr_df.index.date
  stcknr_df['chg%'] = ((stcknr_df['close'] - stcknr_df['close-1'])/stcknr_df['close-1'])*100

  stcknr_df['ADX'] = ta.trend.adx(stcknr_df['high'],stcknr_df['low'],stcknr_df["close"],14,False)
  stcknr_df['DI+'] = ta.trend.adx_pos(stcknr_df['high'],stcknr_df['low'],stcknr_df["close"],14,False)
  stcknr_df['DI-'] = ta.trend.adx_neg(stcknr_df['high'],stcknr_df['low'],stcknr_df["close"],14,False)
  stcknr_df['ADX_Hline1'] = 30
  stcknr_df['ADX_Hline2'] = 45


# add week data for graph
def addtablegraphma2560bb_w(stcknrw_df):
  stcknrw_df['datetime_'] = stcknrw_df.index.date

  for i in ['open', 'high', 'close', 'low']: # loop stock for change type
    stcknrw_df[i] = stcknrw_df[i].astype('float64')
  # # cal indictor
  stcknrw_df['MA5'] = stcknrw_df['close'].rolling(window=5).mean()
  stcknrw_df['MA15'] = stcknrw_df['close'].rolling(window=15).mean()
  stcknrw_df['MA5vol'] = stcknrw_df['volume'].rolling(window=5).mean()
  stcknrw_df['MA15vol'] = stcknrw_df['volume'].rolling(window=15).mean()

  stcknrw_df['close-1'] = stcknrw_df['close'].shift(1)
  # stcknr_df['datetime_'] = stcknr_df.index.date
  stcknrw_df['chg%'] = ((stcknrw_df['close'] - stcknrw_df['close-1'])/stcknrw_df['close-1'])*100

  lastw_row = stcknrw_df.tail(1)
  lStockw_df = lastw_row.append(lastw_row,ignore_index=True)

  lv_syb = lv_stocknameresult
  lv_chg = lStockw_df._get_value(0,'chg%')
  lv_chg = str(lv_chg)
  lv_dt = str(lStockw_df._get_value(0,'datetime_'))



########################### Graph section ###################################
def addgraphma2560bb_d1(stcknr_df):
  pio.templates.default = "plotly_white"
  fig = make_subplots(rows=3, cols=1, shared_xaxes=True,vertical_spacing=0.01,row_heights=[0.8, 0.15,0.15]  ) # make sub plot use x aexs shear and use heights by ratio

  # add OHLC trace
  fig1 = fig.add_trace(go.Candlestick(x=stcknr_df.index,
                              open=stcknr_df['open'],
                              high=stcknr_df['high'],
                              low=stcknr_df['low'],
                              close=stcknr_df['close'],
                              showlegend=False), row=1, col=1)
  # add moving average traces
  fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['MA60'],
                          opacity=0.7,
                          line=dict(color='blue', width=2),
                          name='MA60'), row=1, col=1)

  fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['MA25'],
                          opacity=0.7,
                          line=dict(color='orange', width=2),
                          name='MA 25'), row=1, col=1)



  fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                         y=stcknr_df['lower_band'],
                         name='Lower Band',
                         line_color='rgba(173,204,255,1)'
                        ))
  fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                         y=stcknr_df['upper_band'],
                         name='Upper Band',
                         fill='tonexty',
                         fillcolor='rgba(173,204,255,0.2)',
                         line_color='rgba(173,204,255,1)'
                        ))

  fig1.update_layout(width=1600, height=800)
  # Plot volume trace on 2nd row
  fig3 = fig.add_trace(go.Bar(x=stcknr_df.index,
                      y=stcknr_df['volume']
                      ), row=3, col=1)
  # add moving average traces
  fig3 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['MA60vol'],
                          opacity=0.7,
                          line=dict(color='red', width=2),
                          name='MA60vol'), row=3, col=1)
  fig3 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['MA25vol'],
                          opacity=0.7,
                          line=dict(color='green', width=2),
                          name='MA25vol'), row=3, col=1)




  fig3.update_layout(width=1600, height=400)

  # Plot ADX trace on 2nd row
  fig2 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['ADX'],
                          line=dict(color='Black', width=2),
                          name='ADX'), row=2, col=1)

  fig2 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['DI+'],
                          opacity=.5,
                          line=dict(color='Green', width=2),
                          name='DI+'), row=2, col=1)
  fig2 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['DI-'],
                          opacity=.5,
                          line=dict(color='Red', width=2),
                          name='DI-'), row=2, col=1)

  fig2 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['ADX_Hline2'],
                          opacity=.5,
                          line=dict(color='gray', width=2),
                          name='45'), row=2, col=1)

  fig2 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                          y=stcknr_df['ADX_Hline1'],
                          opacity=.5,
                          line=dict(color='gray', width=2),
                          name='25'), row=2, col=1)


  fig2.update_layout(width=1600, height=400)

  # remove rangeslider
  fig.update_layout(xaxis_rangeslider_visible=False)
  # add chart title
  lv_titel = lv_stocknameresult +" Date:"+lv_dt+"<br>"+ lv_chg +"%"+"<br>"+lv_cond
  fig.update_layout(title = lv_titel)
  fig.update_layout(width=1600, height=1024)

  # build complete timepline from start date to end date
  dt_all = pd.date_range(start=stcknr_df.index[0],end=stcknr_df.index[-1], freq="5T")
  # retrieve the dates that ARE in the original datset
  dt_obs = [d.strftime("%Y-%m-%d") for d in pd.to_datetime(stcknr_df['datetime_'])]
  # define dates with missing values
  dt_breaks = [d for d in dt_all.strftime("%Y-%m-%d").tolist() if not d in dt_obs]
  # hide dates with no values
  fig.update_xaxes(rangebreaks=[dict(values=dt_breaks)])

  fig.show()


def addgraphma2560bb_w1(stcknrw_df):
  figw = make_subplots(rows=2, cols=1, shared_xaxes=True,vertical_spacing=0.01,row_heights=[0.8, 0.2]  ) # make sub plot use x aexs shear and use heights by ratio

  # add OHLC trace
  figw1 = figw.add_trace(go.Candlestick(x=stcknrw_df.index,
                              open=stcknrw_df['open'],
                              high=stcknrw_df['high'],
                              low=stcknrw_df['low'],
                              close=stcknrw_df['close'],
                              showlegend=False), row=1, col=1)
  # add moving average traces
  figw1 = figw.add_trace(go.Scatter(x=stcknrw_df.index,
                          y=stcknrw_df['MA15'],
                          opacity=0.7,
                          line=dict(color='blue', width=2),
                          name='MA15'), row=1, col=1)
  figw1 = figw.add_trace(go.Scatter(x=stcknrw_df.index,
                          y=stcknrw_df['MA5'],
                          opacity=0.7,
                          line=dict(color='orange', width=2),
                          name='MA 5'), row=1, col=1)
  figw1.update_layout(width=1600, height=800)
  # Plot volume trace on 2nd row
  figw2 = figw.add_trace(go.Bar(x=stcknrw_df.index,
                      y=stcknr_df['volume']
                      ), row=2, col=1)
  # add moving average traces
  figw2 = figw.add_trace(go.Scatter(x=stcknrw_df.index,
                          y=stcknr_df['MA60vol'],
                          opacity=0.7,
                          line=dict(color='red', width=2),
                          name='MA60vol'), row=2, col=1)
  figw2 = figw.add_trace(go.Scatter(x=stcknrw_df.index,
                          y=stcknr_df['MA25vol'],
                          opacity=0.7,
                          line=dict(color='green', width=2),
                          name='MA25vol'), row=2, col=1)
  figw2.update_layout(width=1600, height=400)
  # remove rangeslider
  figw.update_layout(xaxis_rangeslider_visible=False)
  # add chart title
  lv_titel = lv_stocknameresult +" Week:"+lv_dt+"<br>"+ lv_chg +"%"+"<br>"+lv_cond
  figw.update_layout(title = lv_titel)
  figw.update_layout(width=1600, height=1024)

  figw.show()

def addgraphmadonc_d1(stcknr_df):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True,vertical_spacing=0.01,row_heights=[0.8, 0.2]  ) # make sub plot use x aexs shear and use heights by ratio

    # add OHLC trace
    fig1 = fig.add_trace(go.Candlestick(x=stcknr_df.index,
                                open=stcknr_df['open'],
                                high=stcknr_df['high'],
                                low=stcknr_df['low'],
                                close=stcknr_df['close'],
                                showlegend=False), row=1, col=1)
    # add moving average traces
    fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                            y=stcknr_df['uc'],
                            opacity=0.7,
                            line=dict(color='blue', width=2),
                            name='Hi'), row=1, col=1)

    fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                            y=stcknr_df['lc'],
                            opacity=0.7,
                            line=dict(color='blue', width=2),
                            name='Lo'), row=1, col=1)

    fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                            y=stcknr_df['mc'],
                            opacity=0.7,
                            line=dict(color='orange', width=2),
                            name='Mc'), row=1, col=1)

    fig1 = fig.add_trace(go.Scatter(x=stcknr_df.index,
                            y=stcknr_df['MA25'],
                            opacity=0.7,
                            line=dict(color='Black', width=2),
                            name='MA 25'), row=1, col=1)

    fig1.update_layout(width=1600, height=800)
    # Plot volume trace on 2nd row
    fig2 = fig.add_trace(go.Bar(x=stcknr_df['datetime_'],#x=stcknr_df.index,
                        y=stcknr_df['volume']
                        ), row=2, col=1)

    fig2.update_layout(width=1600, height=400)
    # remove rangeslider
    fig.update_layout(xaxis_rangeslider_visible=False)
    # add chart title
    lv_titel = lv_stocknameresult +" Date:"+lv_dt+"<br>"+ lv_chg +"%"+"<br>"+lv_cond
    fig.update_layout(title = lv_titel)
    fig.update_layout(width=1600, height=1024)

    # build complete timepline from start date to end date
    dt_all = pd.date_range(start=stcknr_df.index[0],end=stcknr_df.index[-1], freq="5T")
    # retrieve the dates that ARE in the original datset
    dt_obs = [d.strftime("%Y-%m-%d") for d in pd.to_datetime(stcknr_df['datetime_'])]
    # define dates with missing values
    dt_breaks = [d for d in dt_all.strftime("%Y-%m-%d").tolist() if not d in dt_obs]
    # hide dates with no values
    fig.update_xaxes(rangebreaks=[dict(values=dt_breaks)])

    fig.show()

def volume_profile(stcknr_df, return_raw=False):
    """
    create volume profile
    :param df: time-indexed HOLCV bar or time-indexed P-V tick
    :param price_pace: price bucket, default 5 cents
    :param return_raw: return raw data or figure
    :return: raw data or figure obj
    """
    cmin = min(stcknr_df.close)
    cmax = max(stcknr_df.close)
    if cmin < 2:
      price_pace = 0.01
    elif cmin >= 2 and cmin <5 :
        price_pace = 0.02
    elif cmin >= 5 and cmin <10 :
        price_pace = 0.05
    elif cmin >= 10 and cmin <25 :
        price_pace = 0.1
    elif cmin >= 25 and cmin <100 :
        price_pace = 0.25
    elif cmin >= 100 and cmin <200 :
        price_pace = 0.5
    elif cmin >= 200 and cmin <400 :
        price_pace = 1
    elif cmin >= 400  :
        price_pace = 2

    cmin_int = int(cmin / price_pace) * price_pace  # int(0.9) = 0
    cmax_int = int(cmax / price_pace) * price_pace
    if cmax_int < cmax:
        cmax_int += price_pace
    cmax_int += price_pace  # right bracket is not included in arrange

    price_buckets = np.arange(cmin_int, cmax_int, price_pace)
    price_coors = pd.Series(price_buckets).rolling(2).mean().dropna()
    vol_bars = np.histogram(stcknr_df.close, bins=price_buckets, weights=stcknr_df.volume)[0]

    if return_raw:
        return (price_coors.values, vol_bars)



    fig1 = go.Candlestick(
        x=stcknr_df.index,
        open=stcknr_df.open,
        high=stcknr_df.high,
        low=stcknr_df.low,
        close=stcknr_df.close,
        xaxis='x',
        yaxis='y2',
        visible=True,
        showlegend=False
    )

    fig2 = go.Bar(
        x=stcknr_df.index,
        y=stcknr_df.volume,
        yaxis='y',
        name='Volume',
        marker_color='red',
        showlegend=False
    )

    fig3 = go.Bar(
        x=vol_bars,
        y=price_coors.values,
        orientation='h',
        xaxis='x2',
        yaxis='y3',
        visible=True,
        showlegend=False,
        marker_color='blue',
        opacity=0.4
    )

    low = cmin_int
    high = cmax_int
    layout = go.Layout(
        title=go.layout.Title(text= Namestock + "_Volume Profile_" + date_formated),
        xaxis=go.layout.XAxis(
            side="bottom",
            title="Date",
            rangeslider=go.layout.xaxis.Rangeslider(visible=False)
        ),
        yaxis=go.layout.YAxis(
            side="right",
            title='Volume',
            showticklabels=False,
            domain=[0, 0.2]
        ),
        yaxis2=go.layout.YAxis(
            side="right",
            title='Price',
            range=[low, high],
            domain=[0.2, 1.0]
        ),
        xaxis2=go.layout.XAxis(
            side="top",
            showgrid=False,
            # volume bar on the right
            # unfortunately reversed is an auto-range
            # one solution is to add an invisible bar.
            # https://community.plotly.com/t/reversed-axis-with-range-specified/3806
            # autorange='reversed',
            ticks='',
            showticklabels=False,
            range=[0, int(vol_bars.max() * 5)],
            overlaying="x"
        ),
        yaxis3=go.layout.YAxis(
            side="left",
            range=[low, high],
            showticklabels=False,
            overlaying="y2"
        ),
    )




    fig = go.Figure(data=[fig1, fig2, fig3], layout=layout)

    # build complete timepline from start date to end date
    dt_all = pd.date_range(start=stcknr_df.index[0],end=stcknr_df.index[-1], freq="5T")
    # retrieve the dates that ARE in the original datset
    dt_obs = [d.strftime("%Y-%m-%d") for d in pd.to_datetime(stcknr_df['datetime_'])]
    # define dates with missing values
    dt_breaks = [d for d in dt_all.strftime("%Y-%m-%d").tolist() if not d in dt_obs]
    # hide dates with no values
    fig.update_xaxes(rangebreaks=[dict(values=dt_breaks)])
    fig.update_layout(width=1600, height=1024)
    fig.show()
    return fig


def addgrahehikenashi(Stock_df):

  # คำนวณ Heikin Ashi
  Stock_df['HA_Close'] = (Stock_df['Open'] + Stock_df['High'] + Stock_df['Low'] + Stock_df['Close']) / 4

  # สร้างคอลัมน์ HA_Open (ใช้ค่าเริ่มต้น)
  for i in range(Stock_df.shape[0]):
    if i > 0:
      Stock_df.loc[Stock_df.index[i],'HA_Open'] = (Stock_df['HA_Open'][i-1] + Stock_df['HA_Close'][i-1])/2
    elif i == 0:
      Stock_df.loc[Stock_df.index[0],'HA_Open'] = (Stock_df['Open'][0] + Stock_df['Close'][0])/2

  # คำนวณคอลัมน์ HA_High และ HA_Low
  Stock_df['HA_High'] = Stock_df[['High', 'HA_Open', 'HA_Close']].max(axis=1)
  Stock_df['HA_Low'] = Stock_df[['Low', 'HA_Open', 'HA_Close']].min(axis=1)

In [ ]:
Stock_df = pd.DataFrame()
Stock_df = pd.DataFrame()
StockL_df = pd.DataFrame()
table1 = pd.DataFrame()
table2 = pd.DataFrame()
n = int(25)

date_now = datetime.now()
date_formated = date_now.strftime("%Y-%m-%d")
date_csv = date_now.strftime("%Y%m%d")
date_lastyear = datetime.now() - relativedelta(years=1)
st_date_formated = date_lastyear.strftime("%Y-%m-%d")
# st_date_formated = '2024-05-20'

# date_now = date_now + relativedelta(day=1)
date_tomorrow = date_now + relativedelta(days=1)

date_600_days_ago = datetime.now() - relativedelta(days=1100)
# date_600_days_ago = datetime(2023, 1, 1)
date600_days_ago_formated = date_600_days_ago.strftime("%Y-%m-%d")

datestart1 ='2024-04-19'
dateclose1 = '2024-05-20'

datestart2 = '2024-01-05'
dateclose2 = '2024-04-19'

csvfile_intday = 'Result' + date_csv +'interday' + '.csv'
csvfile = 'Result' + date_csv + '.csv'

today = date_now
last10 = today + pd.DateOffset(day=10)


prev_month_last_day = today - pd.DateOffset(months=1, day=1)

date_formated
date_now
date_tomorrow
date600_days_ago_formated

lv_date = datetime.today().strftime('%Y%m%d')
lv_date

# username = 'gkeng3d@gmail.com'
# password = 'ZAQ!2wsx'

datestartst_manual = pd.to_datetime('2024-10-18 02:00:00')

tv = TvDatafeed()

Stock_df = StockL_df[0:0]

WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

In [ ]:
# thislist updated 2026-07-04 — 888 SET common stocks — sorted by market cap desc (preferred removed) (TradingView scanner)
# previous 791-symbol list: File > Revision history
thislist = ['DELTA','ADVANC','PTT','GULF','AOT','KTB','KBANK','PTTEP','SCB','TRUE','CPALL','BBL','BAY','BDMS','CPN','SCC','TTB','THAI','VAYU1','CPF','CPAXT','BH','OR','PTTGC','CRC','MINT','TLI','GPSC','IVL','SCGP','TOP','TISCO','BEM','CCET','KTC','KKP','HMPRO','AWC','WHA','MTC','RATCH','COM7','EGCO','TCAP','TFG','TFMAMA','BJC','MRDIYT','TIDLOR','BANPU','OSP','BCP','ITC','CENTEL','CBG','CPNREIT','KCE','LH','BGRIM','BLA','SCCC','TU','SPI','BTG','SAWAD','FTREIT','TTW','BA','BKIH','GLOBAL','WHART','GUNKUL','IRPC','BPP','BTS','SPRC','MEGA','CK','AMATA','AXTRART','TOA','HANA','STGT','SPALI','STECON','CREDIT','MBK','WHAUP','RCL','LHFG','SIRI','AEONTS','STA','BCH','AP','TVO','PLANB','BAM','EA','TASCO','PB','JTS','RAM','BCPG','PRM','M','CKP','STANLY','VGI','AURA','VIBHA','ICHI','SPC','CHG','EPG','IMPACT','SKR','JMT','AYUD','TPIPL','SJWD','FPT','ERW','BCT','LHHOTEL','QH','TPIPP','SAUCE','SGP','FORTH','PR9','JMART','DMT','TIPH','THG','AAV','UVAN','DCC','DOHOME','ACE','PTG','THCOM','MOSHI','ICC','PTL','LHSC','BAREIT','GFPT','PSL','SCAP','ROJNA','THANI','PSGC','SKY','DITTO','ALUCON','SAPPE','RBF','KAMART','STPI','MTI','DUSIT','SGC','INETREIT','SPCG','JAS','AIMIRT','SISB','TQM','MC','KGI','PSP','TTA','SA','COCOCO','TGH','AAI','WHAIR','SCGD','XO','SUC','NER','SINGER','SC','BLAND','ASTR','LANNA','TSTH','EASTW','SIS','MGC','PSH','SYNEX','ASK','ONEE','PRG','KTIS','SAV','PROSPECT','NSL','KSL','AIT','MEDEZE','TITLE','BAFS','SAT','TFM','SAK','ASW','PRINC','ILM','CPTREIT','AIRA','HTC','NEO','SNNP','GVREIT','SHR','METCO','PM','BBGI','KYE','TNL','NEX','ASIAN','PCE','SHANG','KLINIQ','SRICHA','TKN','SAMART','KCG','STELLA','SABINA','ROCTEC','MAJOR','UTP','TNH','VIH','TURTLE','ANI','CMR','FSMART','PIN','SSP','S&J','NYT','SMPC','BGC','XPG','FUTURERT','AH','PCSGH','ASP','ORI','SNP','TMAN','MST','SKN','ALLY','DRT','BEC','SPA','WPH','TPRIME','RJH','TURBO','FM','OHTL','EKH','HUMAN','BOL','LALIN','TMD','BOFFICE','ADVICE','TSC','LST','AU','BBIK','TSTE','KGEN','SPG','TRT','GGC','TACC','MEB','TKS','NCAP','MCS','BIZ','PLAT','SUPER','HENG','VNG','PCC','MCOT','DREIT','KBS','SMO','TOG','INSET','TEGH','S','NNCL','GJS','QHHRREIT','SCG','INOX','LOXLEY','SUPEREIF','PT','QHBREIT','ITEL','PHG','ASEFA','NTV','TVH','SMT','POLY','NTF','UNIQ','M-CHAI','TMT','III','BRR','GROREIT','TPAC','SNC','TIPCO','A','TEAM','GABLE','MONO','CMAN','SITHAI','RPH','IP','LPH','PYLON','CTW','HFT','AMATAR','MASTER','ILINK','RABBIT','ALPHAX','SYNTEC','DEMCO','ATLAS','MFEC','BEYOND','INET','TKC','TWPC','TRU','BYD','S11','SENA','TEAMG','NOBLE','A5','TGE','Q-CON','SCP','MFC','CSC','GRAMMY','NAM','SEAFCO','B-WORK','MAGURO','LPN','BLC','TL','TMW','AUCT','CGH','TTT','SFLEX','TNP','OKJ','SWC','SEAOIL','LEE','NETBAY','PIS','UPOIC','FPI','MALEE','SO','SUSCO','AMARIN','KISS','IRC','CPI','MSC','SYMC','AMATAV','IT','UBE','GC','TC','SPTX','TK','PRTR','AHC','AI','ITD','NKT','AMA','KTBSTMR','ALT','KCC','SAMTEL','WP','BRI','APURE','WACOAL','SPRIME','THIP','SMIT','SNPS','SUN','BR','SELIC','STOWER','WICE','AJ','SAFE','HYDROGEN','BTC','UAC','FTE','ASIA','EURO','ML','KWC','TSE','2S','BWG','PRIN','ZEN','KDH','UV','TNR','CNT','PAP','QTC','NVD','ETC','THRE','WORK','MODERN','YUASA','APCO','AMARC','DDD','ARROW','HL','BE8','CSR','SAAM','AIE','AGE','TRP','ASAP','TAE','LHRREIT','WASH','SVOA','ICN','PACO','CPW','SRIPANWA','KJL','SSSC','VRANDA','UMS','SSF','GYT','FSX','CHAYO','TTI','JR','LHK','AKR','TPS','SICT','ANAN','SECURE','JUBILE','WINNER','TPBI','LTMH','JPARK','MGI','SPVI','FE','PJW','TQR','DTCENT','CHAO','WHABT','MIDA','BJCHI','VCOM','KCAR','PQS','BKGI','HARN','BROCK','MDX','EAST','BKD','CSS','CH','JDF','ORN','SONIC','PSTC','STP','XBIO','HTECH','SIRIPRT','AS','TAN','UNIX','JCT','SORKON','SPREME','PREB','BEAUTY','ZAA','TPCS','TPL','UKEM','PRI','IROYAL','J','KIAT','CHOW','MII','TMILL','GPI','EP','STI','DCON','BIG','STARM','PROUD','AMC','ESTAR','TYCN','SUTHA','D','TRC','WIIK','FMT','PMTA','CFRESH','CHASE','PDG','VL','SINO','APCS','SVT','PPM','88TH','IFS','MICRO','CPT','MUD','SSTRT','PLUS','PATO','TRUBB','SENX','THE','SALEE','TFI','AMANAH','JSP','FTI','NDR','BM','UREKA','NTSC','CGD','STECH','WARRIX','NOVA','IHL','SIMAT','KUMWEL','PIMO','NEW','TWZ','TOPP','MK','UMI','MOONG','CIVIL','PL','PEACE','MITSIB','NKI','AJA','BIOTEC','IMH','MGT','FVC','MPJ','CCP','MATCH','NATION','APP','GAHREIT','BVG','RSP','SDC','ALLA','SCI','APO','CAZ','MTW','GBX','GTB','BSBM','UBA','ISSARA','SE-ED','ACC','WINDOW','ZIGA','PG','MASTEC','SLP','EASON','BIS','THREL','KOOL','INSURE','PHOL','SFT','LTS','BUI','CWT','PRAKIT','OCC','NAT','NUT','COLOR','CM','LEO','UP','PDJ','L&E','RML','AF','ATP30','GREEN','AQUA','MANRIN','SMART','TPCH','DPAINT','MATI','KUN','MENA','TNITY','NCH','SAMCO','EFORL','PLT','TEKA','GFC','ADD','PAF','CMC','XYZ','CPR','SST','DOD','MNIT2','PF','SCN','YONG','HANN','CHOTI','K','CFARM','ADB','TH','NEP','TPP','SANKO','WAVE','AIMCG','FLOYD','RPC','SPACK','SIAM','JCK','FN','CEN','WFX','ACG','RT','UEC','TRITN','TCC','THANA','WGE','TATG','CHIC','VPO','PLANET','DEXON','VARO','KWM','GTV','UBIS','KTMS','MADAME','LIT','PORT','JAK','PMC','MBAX','GENCO','PROEN','READY','TRV','NRF','TBN','ABM','ITTHI','MORE','KPNREIT','ONSENS','ITNS','NL','BC','TBSP','CI','I2','NV','PRAPAT','CMO','CITY','EVER','SE','ASIMAR','MOTHER','IVF','STC','TAKUNI','ETE','TMC','IND','CPH','CEYE','WINMED','TPA','RS','TMI','TNPC','MCA','CRANE','CPL','ARIN','TPLAS','SRS','SOLAR','TM','DHOUSE','TWP','GLORY','AKP','TCOAT','SEI','FNS','B52','NC','TERA','RICHY','CRD','TCMC','GEL','MJD','STX','PRIME','EMC','TCJ','TKT','KK','PTC','SMD100','PK','B','ETL','QTCG','SK','AE','AMR','PANEL','PPP','TIGER','TNDT','SQ','ARIP','ROCK','SR','BLESS','OGC','CHEWA','KASET','CHARAN','SKE','CSP','PLE','NCP','BPS','HYDRO','CPANEL','AFC','KCM','DIMET','VIBE','GRAND','FANCY','SGF','PERM','BTNC','TVT','ASN','PPPM','IIG','BSM','BKA','PPS','SVR','WIN','VS','UPF','SAWANG','LDC','QLT','RWI','M-PAT','TGPRO','GCAP','RP','NCL','THMUI','BGT','INGRS','SKIN','NPK','PRECHA','ECF','IDG','EMPIRE','TU-PF','YGG','TSI','SAF','IRCP','CIG','SCM','PEER','KC','PROS','MILL','META','TVDH','COMAN','SAM','HPT','TPOLY','BTW','AKS','QDC','CHO','MVP','SCL','MMM']

# --- DR ต่างประเทศ (foreign depositary receipts) — 418 ตัว, แยกต่างหาก ไม่รวมใน thislist ---
# NVDR (.R) ถูกตัดออกเพราะเป็นหุ้นไทยซ้ำ
list_DR = ['AAPL01','AAPL03','AAPL19','AAPL80','ABBV19','ABBV80','ABNB06','ADBE03','ADBE06','ADVANT19','ADVANT23','AFRM03','AIA06','AIA19','AIA23','AMAT01','AMAT23','AMD03','AMD23','AMD80','AMGN06','AMZN01','AMZN03','AMZN06','AMZN23','AMZN80','ANET23','ANET80','ANTA13','ANTA23','APLD03','APPL03','ASEMI23','ASEMI24','ASICS23','ASML01','ASTS01','ASTS03','AVGO23','AVGO80','AXP06','BABA01','BABA06','BABA13','BABA23','BABA80','BAC03','BDX06','BIDU01','BIDU06','BIDU23','BIDU80','BILIBILI01','BIREN23','BKNG03','BKNG80','BLK06','BOEING80','BONDAS19','BONDUS01','BRKB23','BRKB80','BYDCOM01','BYDCOM80','CAMBRI80','CATL01','CATL23','CATL80','CCJ23','CDNS23','CEG23','CHHONGQ19','CHMOBILE19','CHMOBILE23','CHNXT5023','CMBANK23','CME03','CN01','CN23','CNBIO24','CNEV24','CNRE80','CNROBOAI23','CNSEMI23','CNSTAR5023','CNTECH01','COHR23','COIN01','COIN23','COIN80','COSTCO19','CRDO23','CRM01','CRM06','CRM80','CRSP03','CRWD06','CRWD80','CRWV03','CSCO06','CYPC80','DASH03','DBS19','DDOG19','DELL19','DISCO24','DISNEY19','DUOL06','E1VFVN3001','EOSE03','ESTEE80','ETN23','EXPE06','FABRINET23','FANUC23','FCX23','FERRARI80','FPTVN11','FPTVN19','FUEVFVND01','GAC03','GANFENG23','GASVN11','GDS23','GEELY06','GEELY80','GEV23','GEV80','GIGA23','GOLD03','GOLD19','GOLDM01','GOLDUS03','GOLDUS19','GOLDUS80','GOOG23','GOOG80','GOOGL01','GOOGL03','GRAB80','GSEMI24','GSUS06','HAIERS19','HANSOH19','HERMES80','HIMS03','HITACHI24','HK01','HK13','HKCE01','HKEX23','HKTECH13','HONDA19','HOOD03','HOOD06','HOOD80','HORIZON23','HPG19','HSHD23','HUAHONG23','IBM06','ICBC06','ICBC19','IFLYTEK80','INDIA01','INDIAESG19','INTEL01','INTEL03','INTEL23','IONQ03','IONQ23','ISRG01','ISRG06','ISRG19','ITOCHU19','JAP03','JAPAN10001','JAPAN13','JD80','JDHEAL19','JEPI19','JGRO19','JLMAG80','JNJ03','JPANIME24','JPMUS06','JPMUS19','JPROBOAI24','JPSEMI24','JTEK19','KEYENCE23','KINGSOFT23','KIOXIA23','KLAC01','KLAC23','KO80','KONAMI24','KUAISH01','KUAISH06','KUAISH23','KUAISH80','LENOVO13','LITE01','LITE23','LLY23','LLY80','LOREAL80','LPGOLD13','LRCX01','LRCX23','LULU06','LVMH01','MA80','MAOGEP80','MEITUAN19','MEITUAN23','MEITUAN80','MELI06','MELI23','META01','META06','META23','META80','MICRON01','MICRON03','MICRON19','MICRON23','MICRON80','MIDEA80','MITSU19','MIXUE80','MNSO80','MNST06','MONTAGE80','MOUTAI80','MP23','MP80','MPWR23','MRVL06','MRVL23','MRVL80','MS06','MSFT01','MSFT03','MSFT06','MSFT19','MSFT23','MSFT80','MSN11','MSN19','MUFG19','MUFG23','MWG11','MWG19','NAURA23','NAURA80','NBIS01','NBIS03','NBIS23','NDAQ06','NDX01','NEE80','NEM06','NEM23','NET03','NETEASE80','NFLX06','NFLX80','NIKE80','NIKKEI80','NINTENDO19','NINTENDO23','NONGFU80','NOVOB80','NOW19','NVDA01','NVDA03','NVDA06','NVDA19','NVDA23','NVDA80','NVTS03','NVTS23','OIL03','OIL24','OKLO23','ON23','ONON03','ORCL01','ORCL06','ORCL19','PANW80','PEP80','PETROCN80','PFIZER19','PINGAN01','PINGAN80','PLTR01','PLTR03','PLTR06','PLTR23','POPMART23','POPMART80','PYPL06','QCOM06','QQQM19','RBLX06','REMX03','RGTI03','RKLB01','RKLB03','RKLB23','RKLB80','SANOFI80','SANRIO23','SANRIO80','SBUX80','SEAGATE23','SEMB19','SENSE23','SGX19','SHOP03','SHOP06','SIA19','SIL03','SINGTEL80','SINOBIO19','SMCI03','SMFG19','SMIC01','SMIC03','SMIC13','SMIC23','SNDK03','SNDK23','SNDK80','SNOW06','SNOW23','SOFI23','SOFTBANK23','SOFTBANK80','SONY80','SP50001','SP500US19','SP500US80','SPBOND80','SPCOM80','SPENGY80','SPFIN80','SPHLTH80','SPOT06','SPTECH80','STAR5001','STEG19','SUNNY19','SUNNY80','SUSHI23','SYM23','SYNP03','SYNP23','TAIWAN19','TAIWANAI13','TAIWANHD13','TEL23','TEL80','TENCENT01','TENCENT06','TENCENT13','TENCENT19','TENCENT23','TENCENT80','TER01','TER23','THAIBEV19','TME23','TOYOTA80','TRIPCOM23','TRIPCOM80','TRVUS06','TSEMI23','TSLA01','TSLA03','TSLA23','TSLA80','UBER06','UBTECH23','UNH19','UNIQLO80','UOB19','USTR24','VCB11','VCB19','VENTURE19','VHM19','VISA06','VISA80','VNFIN24','VNM19','VRT01','VRT23','VT03','WMT06','WORLD03','WORLDA01','WUXI06','WUXI13','WUXIAT80','XIAOMI01','XIAOMI13','XIAOMI19','XIAOMI23','XIAOMI80','XPENG03','ZAI23','ZIJIN13','ZIJIN23','ZIJIN80','ZJINNO80']

In [ ]:
# ============================================================
# Data dictionary — สร้างคำอธิบายทุกคอลัมน์อัตโนมัติ (เซลล์ export เรียกใช้ตอนเขียนไฟล์)
# ============================================================
def _nums(_s):
    _out, _cur = [], ''
    for _ch in str(_s):
        if _ch.isdigit():
            _cur += _ch
        elif _cur:
            _out.append(int(_cur)); _cur = ''
    if _cur:
        _out.append(int(_cur))
    return _out

def _split_lag(_c):
    if '-' in _c:
        _h, _t = _c.rsplit('-', 1)
        if _t.isdigit() and _h:
            return _h, int(_t)
    return _c, None

_META_EXACT = {
 'symbol': ('ข้อมูลหลัก', 'ชื่อย่อหุ้น รูปแบบ SET:XXX', 'ข้อความ'),
 'open': ('ราคา', 'ราคาเปิดของแท่งล่าสุด', 'บาท'),
 'high': ('ราคา', 'ราคาสูงสุดของแท่งล่าสุด', 'บาท'),
 'low': ('ราคา', 'ราคาต่ำสุดของแท่งล่าสุด', 'บาท'),
 'close': ('ราคา', 'ราคาปิดล่าสุด', 'บาท'),
 'volume': ('ปริมาณ', 'ปริมาณซื้อขายของแท่งล่าสุด', 'หุ้น'),
 'Values': ('ปริมาณ', 'มูลค่าซื้อขาย = volume x close', 'บาท'),
 'datetime_': ('ข้อมูลหลัก', 'วันที่ของแท่งล่าสุด', 'วันที่'),
 'Mcap': ('พื้นฐาน', 'มูลค่าตลาด', 'บาท'),
 'PE': ('พื้นฐาน', 'P/E — ค่าว่างคือไม่มีข้อมูล ติดลบคือขาดทุน (ไม่ใช้ -999 แล้ว)', 'เท่า'),
 'PB': ('พื้นฐาน', 'P/BV', 'เท่า'),
 'ROE': ('พื้นฐาน', 'ผลตอบแทนต่อส่วนผู้ถือหุ้น', '%'),
 'ROA': ('พื้นฐาน', 'ผลตอบแทนต่อสินทรัพย์', '%'),
 'D_E': ('พื้นฐาน', 'หนี้สินต่อทุน', 'เท่า'),
 'net_margin': ('พื้นฐาน', 'อัตรากำไรสุทธิ', '%'),
 'gross_margin': ('พื้นฐาน', 'อัตรากำไรขั้นต้น', '%'),
 'operating_margin': ('พื้นฐาน', 'อัตรากำไรจากการดำเนินงาน', '%'),
 'current_ratio': ('พื้นฐาน', 'อัตราส่วนสภาพคล่อง', 'เท่า'),
 'interest_coverage': ('พื้นฐาน', 'ความสามารถจ่ายดอกเบี้ย (TV มักไม่มีข้อมูลตัวนี้)', 'เท่า'),
 'EPS_growth_YoY': ('พื้นฐาน', 'การเติบโตกำไรต่อหุ้นเทียบปีก่อน', '%'),
 'Revenue_growth_YoY': ('พื้นฐาน', 'การเติบโตรายได้เทียบปีก่อน', '%'),
 'dividendYield': ('พื้นฐาน', 'อัตราปันผล เป็นสัดส่วน (0.05 = 5%)', 'สัดส่วน'),
 'payoutRatio': ('พื้นฐาน', 'สัดส่วนจ่ายปันผลต่อกำไร ค่าว่าง = ไม่มีข้อมูล', 'สัดส่วน'),
 'floatShares': ('พื้นฐาน', 'จำนวนหุ้นหมุนเวียนอิสระ', 'หุ้น'),
 'sharesOutstanding': ('พื้นฐาน', 'จำนวนหุ้นจดทะเบียน', 'หุ้น'),
 'freefloatShares%': ('พื้นฐาน', 'สัดส่วน free float', '%'),
 'enterpriseValue': ('พื้นฐาน', 'มูลค่ากิจการ', 'บาท'),
 'beta': ('ตลาด', 'เบต้าเทียบตลาด 1 ปี', 'เท่า'),
 'sector': ('จัดกลุ่ม', 'กลุ่มธุรกิจ ตามการจัดกลุ่มของ TradingView (ไม่ใช่ 8 industry ของ SET)', 'ข้อความ'),
 'industry': ('จัดกลุ่ม', 'อุตสาหกรรมย่อย (TradingView)', 'ข้อความ'),
 'SET_close': ('ตลาด', 'ระดับดัชนี SET ล่าสุด', 'จุด'),
 'SET_chg_20d': ('ตลาด', 'ผลตอบแทนดัชนี SET 20 วัน', '%'),
 'ATR14': ('ความผันผวน', 'Average True Range 14 วัน = ระยะแกว่งเฉลี่ยต่อวัน', 'บาท'),
 'ATR%': ('ความผันผวน', 'ATR14 คิดเป็น % ของราคาปิด', '%'),
 'close_minus_2ATR': ('ความผันผวน', 'ระดับ Stop Loss ที่ 2 เท่า ATR ใต้ราคาปิด', 'บาท'),
 'MACD': ('โมเมนตัม', 'MACD = EMA12 ลบ EMA26', 'บาท'),
 'MACD_signal': ('โมเมนตัม', 'เส้น signal = EMA 9 ของ MACD', 'บาท'),
 'MACD_hist': ('โมเมนตัม', 'MACD ลบ signal — บวกคือโมเมนตัมขึ้น', 'บาท'),
 'MACD_above0': ('โมเมนตัม', 'MACD มากกว่า 0', 'True/False'),
 'MACD_cross_up': ('โมเมนตัม', 'MACD เพิ่งตัดขึ้นเหนือ signal ในแท่งล่าสุด', 'True/False'),
 'MACD_hist_rising': ('โมเมนตัม', 'histogram สูงขึ้นจากแท่งก่อน', 'True/False'),
 'CDC': ('เทรนด์', 'EMA12 อยู่เหนือ EMA26 (CDC เขียว)', 'True/False'),
 'CDC_last': ('เทรนด์', 'แท่งก่อนหน้า EMA12 อยู่ใต้ EMA26', 'True/False'),
 'CDC_break': ('เทรนด์', 'เพิ่งตัดขึ้นเป็นเขียวในแท่งล่าสุด', 'True/False'),
 'CDC_break_down': ('เทรนด์', 'เพิ่งตัดลงเป็นแดง', 'True/False'),
 'bars_since_CDC_green': ('อายุสัญญาณ', 'กี่แท่งแล้วตั้งแต่ CDC เป็นเขียว — ค่าว่าง = ตอนนี้ไม่เขียว', 'แท่ง'),
 'bars_since_EMA26_break': ('อายุสัญญาณ', 'กี่แท่งแล้วตั้งแต่ราคายืนเหนือ EMA26 — ค่าว่าง = ตอนนี้อยู่ใต้', 'แท่ง'),
 'bars_since_MACD_cross': ('อายุสัญญาณ', 'กี่แท่งแล้วตั้งแต่ MACD ตัดขึ้นเหนือ signal', 'แท่ง'),
 'RSI_div_bull': ('สัญญาณเตือน', 'ขัดแย้งขาขึ้น: ราคาทำ low ใหม่แต่ RSI ไม่ทำ (ดู 60 แท่ง)', 'True/False'),
 'RSI_div_bear': ('สัญญาณเตือน', 'ขัดแย้งขาลง: ราคาทำ high ใหม่แต่ RSI ไม่ทำ (ดู 60 แท่ง)', 'True/False'),
 'RSIzone': ('โมเมนตัม', 'โซนจาก RSI วัน+สัปดาห์ (zone1 อ่อนสุด ถึง zone3 แข็งสุด)', 'ข้อความ'),
 'RSIzoneMove': ('โมเมนตัม', 'การย้ายโซนเทียบแท่งก่อน', 'ข้อความ'),
 'bars_stale': ('คุณภาพข้อมูล', 'จำนวนแท่งท้ายสุดที่ volume = 0 ติดกัน', 'แท่ง'),
 'data_quality_ok': ('คุณภาพข้อมูล', 'ผ่านครบ: มี Mcap + มี free float + ไม่มีข้อมูลค้าง + ข้อมูลอย่างน้อย 60 แท่ง', 'True/False'),
 'screened_out': ('คุณภาพข้อมูล', 'True = ถูก funnel กรองออก มีแค่ราคา/พื้นฐาน ไม่มี indicator', 'True/False'),
 'avg_turnover_10d': ('ปริมาณ', 'มูลค่าซื้อขายเฉลี่ย 10 วัน — ตัวที่ใช้เป็นเกณฑ์ funnel', 'บาท'),
 'next_earnings': ('ปฏิทิน', 'วันประกาศงบครั้งถัดไป', 'วันที่'),
 'days_to_earnings': ('ปฏิทิน', 'เหลืออีกกี่วันถึงวันประกาศงบ (ติดลบ = ผ่านไปแล้ว)', 'วัน'),
 'SCORE': ('สรุป', 'คะแนนรวม 0-100 จาก 8 เงื่อนไข (สูตรอยู่ในเซลล์ export) ค่าว่าง = คำนวณไม่ได้', 'คะแนน'),
 '%Mcapturnover': ('ปริมาณ', 'มูลค่าซื้อขายวันนี้ต่อมูลค่าตลาด', '%'),
}
print('metadata helper พร้อมใช้งาน:', len(_META_EXACT), 'คอลัมน์ที่อธิบายไว้ตรงตัว')

metadata helper พร้อมใช้งาน: 60 คอลัมน์ที่อธิบายไว้ตรงตัว

In [ ]:
# --- กฎอธิบายคอลัมน์ตามรูปแบบชื่อ (ต่อจากเซลล์ก่อนหน้า) ---
def _meta_rule(_h):
    _n = _nums(_h)
    _w = _n[0] if _n else ''
    _p = str(_w)
    if _h.startswith('RSI') and 'W' in _h:
        return ('โมเมนตัม รายสัปดาห์', 'RSI ' + _p + ' คำนวณจากแท่งรายสัปดาห์ (ปั้นจาก daily)', 'ค่า 0-100')
    if _h.startswith('RSI'):
        return ('โมเมนตัม', 'RSI ' + _p + ' วัน', 'ค่า 0-100')
    if _h.startswith('EMA') and _h.endswith('_break_down'):
        return ('เทรนด์', 'ราคาเพิ่งตัดลงใต้ EMA ' + _p, 'True/False')
    if _h.startswith('EMA') and '_break' in _h:
        return ('เทรนด์', 'ราคาเพิ่งตัดขึ้นเหนือ EMA ' + _p, 'True/False')
    if _h.startswith('EMA') and '%C' in _h:
        return ('เทรนด์', 'ระยะห่างราคาปิดจาก EMA ' + _p + ' เป็น %', '%')
    if _h.startswith('STD_EMA'):
        return ('ความผันผวน', 'ส่วนเบี่ยงเบนมาตรฐานรอบ EMA ' + _p, 'บาท')
    if _h.startswith('SD/EMA') or _h.startswith('MA/SD'):
        return ('ความผันผวน', 'อัตราส่วนความผันผวนเทียบเส้นค่าเฉลี่ย ' + _p, 'เท่า')
    if _h.startswith('EMA'):
        return ('เทรนด์', 'เส้นค่าเฉลี่ยแบบ exponential ' + _p + ' วัน', 'บาท')
    if _h.startswith('std MA'):
        return ('ความผันผวน', 'ส่วนเบี่ยงเบนมาตรฐานของ MA ' + _p, 'บาท')
    if _h.startswith('MA') and _h.endswith('TF'):
        return ('เทรนด์', 'ธงเงื่อนไขเส้นค่าเฉลี่ย ' + '/'.join(str(x) for x in _n), 'True/False')
    if _h.startswith('MA'):
        return ('เทรนด์', 'เส้นค่าเฉลี่ยอย่างง่าย ' + _p + ' วัน', 'บาท')
    if _h.startswith('VolMA'):
        return ('ปริมาณ', 'ปริมาณซื้อขายเฉลี่ย ' + _p + ' วัน', 'หุ้น')
    if _h.startswith('VolMax') or _h.startswith('volmax'):
        return ('ปริมาณ', 'ปริมาณซื้อขายสูงสุดในรอบ ' + _p + ' วัน' + (' (ธง)' if 'TF' in _h else ''), 'True/False' if 'TF' in _h else 'หุ้น')
    if _h.startswith('OverVolMAx'):
        return ('ปริมาณ', 'ปริมาณวันนี้เกินค่าเฉลี่ยกี่เท่า (เกณฑ์ ' + _p + ')', 'True/False')
    if _h.startswith('ValMA'):
        return ('ปริมาณ', 'มูลค่าซื้อขายเฉลี่ย ' + _p + ' วัน', 'บาท')
    if _h.startswith('BreakPMin') or _h.startswith('BreakPMax') or _h.startswith('BreakMA') or _h.startswith('BreakMaxclose'):
        return ('จุดทะลุ', 'ราคาทะลุระดับอ้างอิงรอบ ' + _p + ' วัน', 'True/False')
    if 'fibo' in _h:
        return ('Fibonacci', 'ระดับ/โซน Fibonacci จากช่วงราคา ' + _p + ' วัน', 'บาท' if _h.startswith('P_') else 'ข้อความ')
    if _h.startswith('P_as_of'):
        return ('ราคาอ้างอิง', 'ราคาปิด ณ ' + _p + ' วันก่อน', 'บาท')
    if _h.startswith('PRangeMaxMin'):
        return ('ช่วงราคา', 'ช่วงกว้างสูงสุด-ต่ำสุดรอบ ' + _p + ' วัน', '%' if '%' in _h else 'บาท')
    if _h.startswith('PMin') or _h.startswith('PLow'):
        return ('ช่วงราคา', 'ราคาต่ำสุดรอบ ' + _p + ' วัน' + (' (ระยะห่างเป็น %)' if '%' in _h else ''), '%' if '%' in _h else 'บาท')
    if _h.startswith('PMax') or _h.startswith('PHIGH'):
        return ('ช่วงราคา', 'ราคาสูงสุดรอบ ' + _p + ' วัน' + (' (ระยะห่างเป็น %)' if '%' in _h else ''), '%' if '%' in _h else 'บาท')
    if _h.startswith('Volatility%'):
        return ('ความผันผวน', 'ความผันผวนย้อนหลัง ' + _p + ' วัน', '%')
    if _h.startswith('retune_chg'):
        return ('ผลตอบแทน', 'อัตราการเปลี่ยนแปลงราคา และค่าสถิติของมัน (หน้าต่าง ' + _p + ')', '%')
    if _h.startswith('HA_'):
        return ('แท่งเทียน', 'ราคาแบบ Heikin Ashi', 'บาท')
    if 'heikin_ashi' in _h:
        return ('แท่งเทียน', 'เงื่อนไขแท่ง Heikin Ashi เขียวต่อเนื่อง', 'True/False')
    if _h.startswith('candle') or _h.startswith('%candle'):
        return ('แท่งเทียน', 'รูปแบบ/สัดส่วนแท่งเทียน: ' + _h, '%' if _h.startswith('%') else 'True/False')
    if _h.startswith('MCDX'):
        return ('แรงซื้อขาย', 'MCDX แถบ ' + _h.split('_')[-1] + ' (ประมาณแรงรายใหญ่/รายย่อย)', 'ค่า 0-100')
    if _h.startswith('ADX') or _h.startswith('DI'):
        return ('ความแรงเทรนด์', 'ADX / Directional Indicator', 'ค่า 0-100')
    if _h[:2] in ('hi', 'lo', 'uc', 'lc', 'mc') and _n:
        return ('ช่องราคา', 'ขอบช่องราคา (Donchian/Bollinger) รอบ ' + _p, 'บาท')
    if _h.startswith('ret_'):
        return ('ผลตอบแทน', 'ผลตอบแทนราคา ' + _p + ' วัน', '%')
    if _h.startswith('RS_vs_SET'):
        return ('ตลาด', 'ผลตอบแทนหุ้น ลบ ผลตอบแทนดัชนี SET ' + _p + ' วัน — บวก = ชนะตลาด', '%')
    if _h.startswith('RS_rank'):
        return ('ตลาด', 'อันดับเปอร์เซ็นไทล์ของ RS ' + _p + ' วัน เทียบหุ้นทุกตัวในไฟล์ (100 = ดีสุด)', 'เปอร์เซ็นไทล์')
    if _h.startswith('Jump'):
        return ('ช่องว่างราคา', 'ราคากระโดดขึ้น/ลงผิดปกติ', 'True/False')
    if _h.startswith('Stock_dfGap%'):
        return ('ช่องว่างราคา', 'ช่องว่างราคาเปิดเทียบปิดก่อนหน้า', '%')
    if _h.endswith('THB'):
        return ('เกณฑ์ราคา', 'ธงระดับราคา ' + _p + ' บาท', 'True/False')
    if _h.startswith('BB') or 'bb' in _h:
        return ('ช่องราคา', 'Bollinger Band', 'บาท')
    if _h.endswith('TF'):
        return ('ธงเงื่อนไข', 'ธง True/False จากเงื่อนไขในสูตรเดิม: ' + _h, 'True/False')
    if _h.startswith('close') or _h.startswith('open') or _h.startswith('high') or _h.startswith('low'):
        return ('ราคา', 'ราคาย้อนหลัง', 'บาท')
    if _h.startswith('volume'):
        return ('ปริมาณ', 'ปริมาณซื้อขายย้อนหลัง', 'หุ้น')
    return ('อื่นๆ', 'คอลัมน์จากสูตรเดิมของ notebook — ยังไม่ได้ใส่คำอธิบาย', '')
print('rule engine พร้อม')

rule engine พร้อม

In [ ]:
# --- ประกอบตาราง metadata จากคอลัมน์จริงในไฟล์ ---
def _build_metadata(_df):
    _recs = []
    for _k, _c in enumerate(_df.columns):
        _cs = str(_c)
        _head, _lag = _split_lag(_cs)
        if _cs in _META_EXACT:
            _grp, _desc, _unit = _META_EXACT[_cs]
        elif _head in _META_EXACT:
            _grp, _desc, _unit = _META_EXACT[_head]
        else:
            _grp, _desc, _unit = _meta_rule(_head)
        if _lag is not None:
            _desc = _desc + ' | ค่าของ ' + str(_lag) + ' แท่งก่อนหน้า'
        _s = _df[_c]
        _nn = int(_s.notna().sum())
        _lo = _hi = None
        try:
            _num = pd.to_numeric(_s, errors='coerce')
            if _num.notna().any():
                _lo = float(_num.min()); _hi = float(_num.max())
        except Exception:
            pass
        _ex = _s.dropna()
        _ex = str(_ex.iloc[0])[:40] if len(_ex) else ''
        _recs.append({'ลำดับ': _k + 1, 'column': _cs, 'กลุ่ม': _grp, 'คำอธิบาย': _desc, 'หน่วย': _unit,
                      'ย้อนหลัง(แท่ง)': _lag, 'ชนิดข้อมูล': str(_s.dtype), 'มีค่า(แถว)': _nn,
                      'มีค่า(%)': round(100.0 * _nn / max(len(_df), 1), 1),
                      'ค่าต่ำสุด': _lo, 'ค่าสูงสุด': _hi, 'ตัวอย่าง': _ex})
    return pd.DataFrame(_recs)
print('_build_metadata พร้อมใช้งาน')

_build_metadata พร้อมใช้งาน

In [ ]:
batch_size = 30  # จำนวนหุ้นต่อหนึ่งรอบ

In [ ]:
# ============================================================
# CONFIG — ปรับ 5 ค่านี้พอ  (แก้ 2026-07-25: funnel + parallel fetch + weekly resample + n_bars + indicators ชุดใหม่)
# ============================================================
_MIN_TURNOVER = 0           # [1] 0 = ปิด funnel รันครบทุกตัวทุกวัน (ตั้งเป็นตัวเลขบาท/วัน ถ้าอยากกรองเพื่อความเร็ว)
_MIN_PRICE    = 0.07        # [1] ราคาขั้นต่ำ (ให้ตรงกับตัวกรองท้าย notebook)
_WORKERS      = 3           # [2] ดึงข้อมูลขนานกี่เส้น — อย่าเกิน 4 และอย่ารัน 2 notebook พร้อมกัน (TV throttle)
_FETCH_BARS   = 750         # [3] ดึง daily กี่แท่ง (ใช้ปั้น weekly ด้วย) — latency-bound ดึงเยอะไม่ช้าลง
_N_BARS       = 300         # [4] คำนวณ indicator จากกี่แท่งล่าสุด (300 = เร็วสุด / 700 = ได้ค่าเดิมครบทุกคอลัมน์)

import warnings as _wn
_wn.filterwarnings('ignore')   # ปิด PerformanceWarning: วัดแล้วการเขียน warning ลง output ช้ากว่าการคำนวณหลายเท่า (18 วิ/ตัว -> 2.3 วิ/ตัว)
import os as _os, threading as _th
import requests as _rq
from concurrent.futures import ThreadPoolExecutor as _TPE

# --- Plan A: bulk fundamentals จาก TradingView (1 request) — อ่านด้วยชื่อคอลัมน์ ไม่ใช่ index ---
_FCOLS = ['name','market_cap_basic','price_earnings_ttm','dividend_payout_ratio_ttm','dividends_yield_current',
          'float_shares_outstanding','total_shares_outstanding','enterprise_value_fq','close','average_volume_10d_calc',
          'sector','industry','return_on_equity','return_on_assets','debt_to_equity','net_margin','gross_margin',
          'operating_margin','current_ratio','interest_coverage','price_book_fq',
          'earnings_per_share_diluted_yoy_growth_ttm','total_revenue_yoy_growth_ttm','beta_1_year','earnings_release_next_date']

def _build_fund():
    _body = {'filter':[{'left':'type','operation':'in_range','right':['stock','dr']}], 'columns':_FCOLS, 'range':[0,6000]}
    _r = _rq.post('https://scanner.tradingview.com/thailand/scan', json=_body, headers={'User-Agent':'Mozilla/5.0'}, timeout=60)
    _d = {}
    for _row in _r.json().get('data', []):
        _v = dict(zip(_FCOLS, _row['d']))
        _y = _v['dividends_yield_current']
        _p = _v['dividend_payout_ratio_ttm']
        _y = (_y/100) if _y is not None else None
        _p = (_p/100) if _p is not None else None
        if _p == 0 and not _y:          # payout 0 ทั้งที่ไม่มีข้อมูลปันผล -> ถือว่าไม่มีข้อมูล (อย่าใส่ 0)
            _p = None
        _d[_v['name']] = {
            'marketCap':_v['market_cap_basic'], 'trailingPE':_v['price_earnings_ttm'],
            'payoutRatio':_p, 'dividendYield':_y,
            'floatShares':_v['float_shares_outstanding'], 'sharesOutstanding':_v['total_shares_outstanding'],
            'enterpriseValue':_v['enterprise_value_fq'], '_close':_v['close'], '_avgvol10':_v['average_volume_10d_calc'],
            'sector':_v['sector'], 'industry':_v['industry'], 'roe':_v['return_on_equity'], 'roa':_v['return_on_assets'],
            'de':_v['debt_to_equity'], 'netMargin':_v['net_margin'], 'grossMargin':_v['gross_margin'],
            'opMargin':_v['operating_margin'], 'currentRatio':_v['current_ratio'], 'interestCov':_v['interest_coverage'],
            'pb':_v['price_book_fq'], 'epsGrowth':_v['earnings_per_share_diluted_yoy_growth_ttm'],
            'revGrowth':_v['total_revenue_yoy_growth_ttm'], 'beta':_v['beta_1_year'],
            'nextEarnings':_v['earnings_release_next_date']}
    return _d

try:
    FUND = _build_fund(); print('FUND loaded:', len(FUND), 'symbols |', len(_FCOLS), 'fields')
except Exception as _e:
    FUND = {}; print('FUND load failed:', repr(_e))

# --- [1] Funnel: คัดเฉพาะตัวที่มีสภาพคล่องพอ ก่อนเข้า loop หนัก ---
_runlist = list(thislist)
_dropped = []
if _MIN_TURNOVER > 0 and FUND:
    _runlist, _dropped = [], []
    for _s in thislist:
        _f = FUND.get(_s)
        if not _f:                      # ไม่มีใน scanner -> ไม่ตัดทิ้ง ปล่อยไปลองดึงจริง
            _runlist.append(_s); continue
        _c = _f.get('_close') or 0
        _t = _c * (_f.get('_avgvol10') or 0)
        (_runlist if (_c >= _MIN_PRICE and _t >= _MIN_TURNOVER) else _dropped).append(_s)
print('FUNNEL:', len(thislist), '->', len(_runlist), 'ตัวที่จะรัน |', len(_dropped), 'ตัวถูกกรองออก (สภาพคล่องต่ำ)')

# --- [2]+[3] parquet cache + ดึงขนาน (เก็บเฉพาะ daily, weekly ปั้นเอาจาก daily) ---
if _os.path.isdir('/content/drive/MyDrive'):
    _CACHE_DIR = '/content/drive/MyDrive/SET_cache'   # Drive mounted -> cache อยู่ข้าม session
else:
    _CACHE_DIR = '/content/SET_cache'                 # VM disk -> อยู่แค่ runtime นี้ (mount Drive เพื่อเก็บถาวร)
_os.makedirs(_CACHE_DIR, exist_ok=True)
_pq_d = _CACHE_DIR + '/daily_' + lv_date + '.parquet'

_ALL_D = pd.read_parquet(_pq_d) if _os.path.exists(_pq_d) else pd.DataFrame()
_have = set(_ALL_D['sym'].unique()) if len(_ALL_D) else set()
_need = [s for s in _runlist if s not in _have]
print('CACHE:', _pq_d, '| มีแล้ว', len(_have), 'ตัว | ต้องดึงเพิ่ม', len(_need), 'ตัว')

_fetch_fail = []
if _need:
    _tl = _th.local()
    def _tv_local():
        if not hasattr(_tl, 'h'):
            _tl.h = TvDatafeed()        # 1 connection ต่อ 1 thread
        return _tl.h
    def _fetch_one(_s):
        try:
            _d = _tv_local().get_hist(symbol=_s, exchange='SET', interval=Interval.in_daily, n_bars=_FETCH_BARS)
            if _d is None or len(_d) == 0:
                return (_s, None, 'empty')
            _d = _d.copy(); _d['sym'] = _s
            return (_s, _d, None)
        except Exception as _e:
            return (_s, None, repr(_e)[:100])
    _fd = []
    with _TPE(max_workers=_WORKERS) as _ex:
        for _s, _d, _err in _ex.map(_fetch_one, _need):
            if _d is not None:
                _fd.append(_d)
            else:
                _fetch_fail.append((_s, _err))
    if _fetch_fail:                    # ลองซ้ำทีละตัว — กัน empty ชั่วคราวจากการดึงขนาน
        _retry, _fetch_fail = _fetch_fail, []
        for _s, _err in _retry:
            _s2, _d2, _e2 = _fetch_one(_s)
            if _d2 is not None:
                _fd.append(_d2)
            else:
                _fetch_fail.append((_s2, _e2))
        print('RETRY:', len(_retry), 'ตัว ->', len(_fetch_fail), 'ยังไม่ได้')
    if _fd:
        _ALL_D = pd.concat([_ALL_D] + _fd) if len(_ALL_D) else pd.concat(_fd)
        _ALL_D.to_parquet(_pq_d)
    print('FETCHED+CACHED:', (_ALL_D['sym'].nunique() if len(_ALL_D) else 0), 'symbols | fetch failures:', len(_fetch_fail), _fetch_fail[:5])
if len(_ALL_D) == 0:
    raise RuntimeError('ไม่มีข้อมูลเลย — ดึงไม่สำเร็จทั้งหมด (ดู _fetch_fail)')

# --- [3] weekly ปั้นจาก daily (เลิกยิง get_hist รอบ weekly = ตัดเวลา fetch ไปครึ่งหนึ่ง) ---
def _to_weekly(_df):
    _w = _df.resample('W').agg({'open':'first','high':'max','low':'min','close':'last','volume':'sum'})
    return _w.dropna(subset=['close'])

# --- [Tier1-3] ดัชนี SET สำหรับ Relative Strength ---
_SET_RET, _SET_LAST = {}, np.nan
try:
    _setdf = tv.get_hist(symbol='SET', exchange='SET', interval=Interval.in_daily, n_bars=_FETCH_BARS)
    _setc = _setdf['close']
    _SET_LAST = float(_setc.iloc[-1])
    for _n in (1, 5, 20, 60):
        if len(_setc) > _n:
            _SET_RET[_n] = float(_setc.iloc[-1] / _setc.iloc[-1-_n] - 1) * 100
    print('SET INDEX:', round(_SET_LAST, 2), '| chg 1/5/20/60d:', {k: round(v, 2) for k, v in _SET_RET.items()})
except Exception as _e:
    print('SET INDEX load failed:', repr(_e)[:120])

# --- helper: นับแท่งตั้งแต่สัญญาณล่าสุดเกิด (None ถ้าตอนนี้สัญญาณไม่ติด) ---
def _bars_since_cross_up(_flag):
    _f = _flag.fillna(False).astype(bool)
    if len(_f) == 0 or not bool(_f.iloc[-1]):
        return np.nan
    _cross = _f & (~_f.shift(1).fillna(False))
    _pos = np.flatnonzero(_cross.values)
    return float(len(_f) - 1 - _pos[-1]) if len(_pos) else np.nan

def _ret_n(_s, _n):
    if len(_s) <= _n:
        return np.nan
    _base = _s.iloc[-1-_n]
    return float(_s.iloc[-1] / _base - 1) * 100 if _base else np.nan

# --- indicator ชุดใหม่: ATR / MACD / อายุสัญญาณ / RS vs SET / พื้นฐาน / คุณภาพข้อมูล ---
def _extra_lastrow(Stock_df):
    # คำนวณบน Series (ถูก) แล้วเก็บเฉพาะค่าแท่งสุดท้าย — ไม่แทรกคอลัมน์เข้า DataFrame 1,600 คอลัมน์
    _c = Stock_df['close']
    _px = float(_c.iloc[-1])
    _o = {}

    _atr = ta.volatility.average_true_range(Stock_df['high'], Stock_df['low'], _c, window=14)
    _a = float(_atr.iloc[-1]) if _atr.notna().any() else np.nan
    _o['ATR14'] = _a
    _o['ATR%'] = (_a / _px * 100) if (_a == _a and _px) else np.nan
    _o['close_minus_2ATR'] = (_px - 2 * _a) if _a == _a else np.nan

    _m = ta.trend.MACD(_c, window_slow=26, window_fast=12, window_sign=9)
    _mac, _sig, _his = _m.macd(), _m.macd_signal(), _m.macd_diff()
    _o['MACD'] = float(_mac.iloc[-1]) if _mac.notna().any() else np.nan
    _o['MACD_signal'] = float(_sig.iloc[-1]) if _sig.notna().any() else np.nan
    _o['MACD_hist'] = float(_his.iloc[-1]) if _his.notna().any() else np.nan
    _o['MACD_above0'] = bool(_o['MACD'] > 0) if _o['MACD'] == _o['MACD'] else False
    _o['MACD_cross_up'] = bool(_mac.iloc[-1] > _sig.iloc[-1] and _mac.iloc[-2] <= _sig.iloc[-2]) if len(_mac) > 1 else False
    _o['MACD_hist_rising'] = bool(_his.iloc[-1] > _his.iloc[-2]) if len(_his) > 1 else False

    _o['bars_since_CDC_green'] = _bars_since_cross_up(Stock_df['EMA12'] > Stock_df['EMA26'])
    _o['bars_since_EMA26_break'] = _bars_since_cross_up(_c > Stock_df['EMA26'])
    _o['bars_since_MACD_cross'] = _bars_since_cross_up(_mac > _sig)

    for _n in (1, 5, 20, 60):
        _sr = _ret_n(_c, _n)
        _o['ret_' + str(_n) + 'd'] = _sr
        _o['RS_vs_SET_' + str(_n) + 'd'] = (_sr - _SET_RET[_n]) if (_sr == _sr and _n in _SET_RET) else np.nan
    _o['SET_close'] = _SET_LAST
    _o['SET_chg_20d'] = _SET_RET.get(20, np.nan)

    if 'RSI14' in Stock_df.columns and len(Stock_df) > 60:
        _c1 = _c.iloc[-60:]; _r1 = Stock_df['RSI14'].iloc[-60:]
        _o['RSI_div_bear'] = bool(_c1.iloc[30:].max() >= _c1.iloc[:30].max() and _r1.iloc[30:].max() < _r1.iloc[:30].max())
        _o['RSI_div_bull'] = bool(_c1.iloc[30:].min() <= _c1.iloc[:30].min() and _r1.iloc[30:].min() > _r1.iloc[:30].min())
    else:
        _o['RSI_div_bear'] = np.nan
        _o['RSI_div_bull'] = np.nan

    _v = Stock_df['volume'].fillna(0).values
    _k = 0
    for _x in _v[::-1]:
        if _x == 0:
            _k += 1
        else:
            break
    _o['bars_stale'] = _k

    _i = FUND.get(lv_syml, {})
    for _dst, _src in (('sector','sector'), ('industry','industry'), ('ROE','roe'), ('ROA','roa'), ('D_E','de'),
                       ('net_margin','netMargin'), ('gross_margin','grossMargin'), ('operating_margin','opMargin'),
                       ('current_ratio','currentRatio'), ('interest_coverage','interestCov'), ('PB','pb'),
                       ('EPS_growth_YoY','epsGrowth'), ('Revenue_growth_YoY','revGrowth'), ('beta','beta')):
        _o[_dst] = _i.get(_src)
    _ne = _i.get('nextEarnings')
    if _ne:
        _nd = pd.to_datetime(_ne, unit='s')
        _o['next_earnings'] = _nd.strftime('%Y-%m-%d')
        _o['days_to_earnings'] = int((_nd.normalize() - pd.Timestamp.today().normalize()).days)
    else:
        _o['next_earnings'] = None
        _o['days_to_earnings'] = np.nan
    _o['data_quality_ok'] = bool(_i.get('marketCap') is not None and _i.get('floatShares') is not None
                                 and _k == 0 and len(Stock_df) >= 60)
    return _o

import gc as _gc
_gc.disable()   # loop สะสม DataFrame 1,666 คอลัมน์หลายร้อยก้อน -> cyclic GC แพงขึ้นเรื่อยๆ (ยังไม่ได้พิสูจน์เต็มสเกล)
_skipped = []
_rows = []
# หมายเหตุ: ถ้า _N_BARS < 600 คอลัมน์ตระกูล 600 (และ 500) จะออกมาเป็น NaN เพราะแท่งไม่พอ
for i in range(0, len(_runlist), batch_size):
    batch = _runlist[i:i+batch_size]
    for lv_syml in batch:
      try:
        A = lv_syml + '.BK'

        _full = _ALL_D[_ALL_D['sym'] == lv_syml].drop(columns='sym')
        if len(_full) == 0:
            raise ValueError('no data in cache for ' + lv_syml)
        StockW_df = _to_weekly(_full)
        Stock_df = _full.tail(_N_BARS).copy()
        addtable1_rsiweekly(StockW_df)
        # Stock_df30m = tv.get_hist(symbol=lv_syml,exchange='SET',interval=Interval.in_30_minute,n_bars=20)
        # Stock_df1h = tv.get_hist(symbol=lv_syml,exchange='SET',interval=Interval.in_1_hour,n_bars=20)
        # Stock_df4h = tv.get_hist(symbol=lv_syml,exchange='SET',interval=Interval.in_4_hour,n_bars=20)
        # Stock_dfw = tv.get_hist(symbol=lv_syml,exchange='SET',interval=Interval.in_weekly,n_bars=20)
        # Stock_dfm = tv.get_hist(symbol=lv_syml,exchange='SET',interval=Interval.in_monthly,n_bars=20)

        # Stock_df = yf.download(A,start = date600_days_ago_formated , end= date_tomorrow,progress=False)

        # A.history(period="max")
        # Stock_df = Stock_df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close', 'Volume': 'volume'})
        #หาlastปีก่อน
        # ytd_df = Stock_df[Stock_df.index.year == 2023]
        ytd_df_pf = Stock_df[Stock_df.index.year == date_now.year]
        # lastY_row_index = ytd_df.shape[0] - 1
        Y_row_index = ytd_df_pf.shape[0] - 1
        YTDx = Y_row_index + 2


        addtable1info(Stock_df)

        # #หาytd
        # Stock_df['return_ytd'] = 100 * ((Stock_df['close'] - Stock_df['close'].iloc[-YTDx]) / Stock_df['close'].iloc[-YTDx])

        addtable1(Stock_df)
        addtablecandlestick(Stock_df)
        addtablehikenashi(Stock_df)
        addtableMA(Stock_df)
        addtableVol(Stock_df)
        Stock_df = Stock_df.copy()  # defrag
        addtableVal(Stock_df)
        addtableMin(Stock_df)
        addtableMax(Stock_df)
        addtablelow(Stock_df)
        addtablehigh(Stock_df)
        addtableMinMaxptc(Stock_df)
        addtablehighlowptc(Stock_df)
        addtablebreakHL(Stock_df)
        addtableEMA(Stock_df)
        Stock_df = Stock_df.copy()  # defrag
        addtableCal(Stock_df)
        addtablefibonacci_ptc(Stock_df)
        addtablereturn(Stock_df)


        addtableCalinfo(Stock_df)

        addtableADX(Stock_df)
        addtable1_bb(Stock_df)
        addtable1_donc_c(Stock_df)
        addtable1_donc_25(Stock_df)
        addtable1_donc_60(Stock_df)
        addtable1_donc_200(Stock_df)
        Stock_df = Stock_df.copy()  # defrag
        addtable1_rsi(Stock_df)
        # addtable_vp25(Stock_df)
        # addtable_vp60(Stock_df)
        # addtable_vp200(Stock_df)
        # addtable_vp600(Stock_df)
        addtable_downtrend(Stock_df)
        addtable_Volatility(Stock_df)

        addtable1_MCDX(Stock_df)
        Stock_df = Stock_df.copy()  # defrag




        # grouped = Stock_df.groupby("close")
        # dfgroup = grouped[["volume"]].aggregate(np.sum)
        # dfgroup = dfgroup.sort_values(by='volume')
        # dfgroup['close_vp'] = dfgroup.index
        # last_row_vp600 = dfgroup.tail(1)
        # last_row_vp600 = last_row_vp600[['close_vp']]
        # vp600 = last_row_vp600.iloc[[0],[0]]

        # for i in last_row_vp600['close_vp']:
        #     Stock_df['VP600']  = i

        #   #หาช่วงเวลา ที่ต้องการ
        # # Convert datetime column to datetime type
        # Stock_df['datetime_'] = pd.to_datetime(Stock_df['datetime_'])


        # # Filter the DataFrame for the dates 2021-08-10 and 2021-08-16
        # df_filtered1 = Stock_df[(Stock_df['datetime_'] ==  pd.to_datetime(dateclose1)) | (Stock_df['datetime_'] == pd.to_datetime(datestart1) )]

        # # Calculate percentage change in closing prices between the two dates
        # df_filtered1.set_index('datetime_', inplace=True)
        # close_pct_change1 = df_filtered1['close'].pct_change() * 100

        # # Extracting the percentage change value between the specified dates
        # percentage_change_time1 = close_pct_change1['2024-05-20']

        # Stock_df['pct_change_time1'] = percentage_change_time1

        #   #หาช่วงเวลา ที่ต้องการ2

        # # Filter the DataFrame for the dates 2021-08-10 and 2021-08-16
        # df_filtered2 = Stock_df[(Stock_df['datetime_'] == pd.to_datetime(dateclose2)) | (Stock_df['datetime_'] == pd.to_datetime(dateclose2))]

        # # Calculate percentage change in closing prices between the two dates
        # df_filtered2.set_index('datetime_', inplace=True)
        # close_pct_change2 = df_filtered2['close'].pct_change() * 100

        # # Extracting the percentage change value between the specified dates
        # percentage_change_time2 = close_pct_change2['2024-04-19']

        # Stock_df['pct_change_time2'] = percentage_change_time2

        # Stock_df30m['EMA10_30m'] = Stock_df30m['close'].ewm(span=10).mean()
        # Stock_df1h['EMA10_1h'] = Stock_df1h['close'].ewm(span=10).mean()
        # Stock_df4h['EMA10_4h'] = Stock_df4h['close'].ewm(span=10).mean()
        # Stock_dfw['EMA10_w'] = Stock_dfw['close'].ewm(span=10).mean()
        # Stock_dfm['EMA10_m'] = Stock_dfm['close'].ewm(span=10).mean()
        last_row = Stock_df.tail(1)
        last_roww = StockW_df.tail(1)
        # สมมติ last_roww มี index เป็น datetime หรือจะ reset index แล้วใช้คอลัมน์ก็ได้
        RSI_cols = [col for col in last_roww.columns if 'RSI' in col]  # เลือกคอลัมน์ที่มี 'RSI'
        last_roww_rsi = last_roww[RSI_cols]



        # last_row30m = Stock_df30m.tail(1)
        # last_row1h = Stock_df1h.tail(1)
        # last_row4h = Stock_df4h.tail(1)
        # last_roww = Stock_dfw.tail(1)
        # last_rowm = Stock_dfm.tail(1)

        last_result = pd.concat([
            last_row.reset_index(drop=True),
            last_roww_rsi.reset_index(drop=True),
            pd.DataFrame([_extra_lastrow(Stock_df)])   # indicator ชุดใหม่ เฉพาะแถวสุดท้าย
        ], axis=1)

        _rows.append(last_result)


        # StockL_df = pd.concat([last_row, last_roww_rsi], axis=1)
        # StockL_df = pd.concat([StockL_df, last_row30m], ignore_index=True)
        # StockL_df = pd.concat([StockL_df, last_row1h], ignore_index=True)
        # StockL_df = pd.concat([StockL_df, last_row4h], ignore_index=True)
        # StockL_df = pd.concat([StockL_df, last_roww], ignore_index=True)
        # StockL_df = pd.concat([StockL_df, last_rowm], ignore_index=True)



        Stock_df = Stock_df[0:0]
        StockW_df = StockW_df[0:0]
      except Exception as _e:
        globals().setdefault("_skipped", []).append((lv_syml, repr(_e)[:140]))
        continue

_gc.enable()
if _rows:
    StockL_df = pd.concat([StockL_df] + _rows, ignore_index=True)
    for _rc in ('RS_vs_SET_20d','RS_vs_SET_60d'):
        if _rc in StockL_df.columns:
            StockL_df[_rc.replace('RS_vs_SET_','RS_rank_')] = StockL_df[_rc].rank(pct=True).mul(100).round(1)
print('DONE: rows', len(StockL_df), '| skipped', len(_skipped), '| fetch fail', len(_fetch_fail))
if _skipped:
    print('SKIPPED:', _skipped[:20])
if _dropped:
    print('FUNNEL dropped (สภาพคล่องต่ำ ไม่อยู่ในไฟล์):', len(_dropped), _dropped[:15])

WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited
WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited
WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

FUND loaded: 2212 symbols | 25 fields
FUNNEL: 888 -> 888 ตัวที่จะรัน | 0 ตัวถูกกรองออก (สภาพคล่องต่ำ)
CACHE: /content/SET_cache/daily_20260731.parquet | มีแล้ว 0 ตัว | ต้องดึงเพิ่ม 888 ตัว

ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection to remote host was lost.
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection to remote host was lost.
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol
ERROR:tvDatafeed.main:Connection timed out
ERROR:tvDatafeed.main:no data, please check the exchange and symbol

RETRY: 8 ตัว -> 2 ยังไม่ได้
FETCHED+CACHED: 886 symbols | fetch failures: 2 [('BANPU', 'empty'), ('PSTC', 'empty')]
SET INDEX: 1623.64 | chg 1/5/20/60d: {1: 1.6, 5: -0.96, 20: 2.23, 60: 8.7}
DONE: rows 884 | skipped 4 | fetch fail 2
SKIPPED: [('BANPU', "ValueError('no data in cache for BANPU')"), ('SPTX', "IndexError('single positional indexer is out-of-bounds')"), ('PSTC', "ValueError('no data in cache for PSTC')"), ('UNIX', "IndexError('single positional indexer is out-of-bounds')")]

In [ ]:
import time

start_time = time.time()

# วัดเวลาดึงข้อมูลพื้นฐาน
fund_start = time.time()
try:
    FUND = _build_fund()
    print(f"FUND loaded: {len(FUND)} symbols (Time: {time.time() - fund_start:.2f}s)")
except:
    print("FUND load failed")

# วัดเวลาดึงข้อมูลกราฟ/Cache
fetch_start = time.time()
# ... (Logic การดึงข้อมูลเดิมจากเซลล์ก่อนหน้า) ...
print(f"Data Fetching/Cache Time: {time.time() - fetch_start:.2f}s")

# วัดเวลาการคำนวณ Indicator รายตัว
proc_start = time.time()
# ... (Loop ประมวลผลหุ้นเดิม) ...
print(f"Processing Loop Time: {time.time() - proc_start:.2f}s")

print(f"--- Total Execution Time: {time.time() - start_time:.2f} seconds ---")

FUND loaded: 2212 symbols (Time: 0.37s)
Data Fetching/Cache Time: 0.00s
Processing Loop Time: 0.00s
--- Total Execution Time: 0.37 seconds ---

In [ ]:
# (ปิดใช้งาน 2026-07-05: เซลล์ debug เก่าเคยทับ thislist ด้วยลิสต์ 318 ตัวหลังรันลูป — ต้นฉบับดูใน Revision history)

In [ ]:
print('THISLIST len=', len(thislist), '| has PTECH:', 'PTECH' in thislist, '| head=', thislist[:3], '| tail=', thislist[-3:])

THISLIST len= 888 | has PTECH: False | head= ['DELTA', 'ADVANC', 'PTT'] | tail= ['MVP', 'SCL', 'MMM']

In [ ]:
print('FAILED lv_syml =', repr(lv_syml), '| A =', repr(A)); print('StockW_df is None:', StockW_df is None); print('Stock_df is None:', Stock_df is None)

FAILED lv_syml = 'MMM' | A = 'MMM.BK'
StockW_df is None: False
Stock_df is None: False

In [ ]:
StockL_df

,symbol,open,high,low,close,volume,Mcap,PE,payoutRatio,dividendYield,...,interest_coverage,PB,EPS_growth_YoY,Revenue_growth_YoY,beta,next_earnings,days_to_earnings,data_quality_ok,RS_rank_20d,RS_rank_60d
0,SET:DELTA,276.00,281.00,274.00,278.00,22743747.0,3.293088e+12,116.162460,0.0,0.002273,...,None,32.895360,64.176442,37.926010,1.991918,2026-10-27,88.0,True,1.9,10.0
1,SET:ADVANC,378.00,382.00,377.00,380.00,8489031.0,1.124251e+12,22.247332,0.0,0.040476,...,None,9.380713,36.525458,5.338779,0.639730,2026-08-07,7.0,True,63.0,66.2
2,SET:PTT,38.50,38.75,38.25,38.50,69669533.0,1.099675e+12,11.862213,0.0,0.054545,...,None,0.928621,9.916012,-10.894397,0.798900,2026-08-13,13.0,True,75.1,60.6
3,SET:GULF,65.75,67.25,65.50,66.75,63815355.0,9.822943e+11,11.190652,0.0,0.015970,...,None,2.878843,NaN,NaN,1.450192,2026-08-07,7.0,True,77.7,73.5
4,SET:AOT,63.50,64.00,63.25,63.75,21442821.0,9.071420e+11,50.319678,0.0,0.012756,...,None,7.023927,-5.897645,-3.410447,0.693466,2026-08-06,6.0,True,19.6,83.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,SET:QDC,0.07,0.07,0.06,0.07,393416.0,2.603312e+07,NaN,NaN,0.000000,...,None,0.152818,65.309112,-68.731857,3.761737,None,NaN,True,30.8,1.5
880,SET:CHO,0.02,0.03,0.02,0.02,7079386.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,False,0.5,0.6
881,SET:MVP,0.04,0.06,0.04,0.06,17360638.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,False,99.2,0.5
882,SET:SCL,1.66,1.66,1.61,1.65,214505.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,0.258610,None,NaN,False,76.0,89.0
883,SET:MMM,2.76,2.78,2.74,2.78,142908.0,NaN,NaN,NaN,0.046413,...,None,1.810839,NaN,NaN,0.495760,None,NaN,False,20.3,44.7

In [ ]:
StockW_df

Empty DataFrame
Columns: [open, high, low, close, volume, RSI14W, RSI14W-1, RSI14W-2, RSI14W-3, RSI14W-4, RSI14W-5, RSI14W-10, RSI14W-12, RSI14W-14, RSI14W-26, RSI14W-40, RSI14W-75, RSI14W-89]
Index: []

In [ ]:
StockL_df

,symbol,open,high,low,close,volume,Mcap,PE,payoutRatio,dividendYield,...,interest_coverage,PB,EPS_growth_YoY,Revenue_growth_YoY,beta,next_earnings,days_to_earnings,data_quality_ok,RS_rank_20d,RS_rank_60d
0,SET:DELTA,276.00,281.00,274.00,278.00,22743747.0,3.293088e+12,116.162460,0.0,0.002273,...,None,32.895360,64.176442,37.926010,1.991918,2026-10-27,88.0,True,1.9,10.0
1,SET:ADVANC,378.00,382.00,377.00,380.00,8489031.0,1.124251e+12,22.247332,0.0,0.040476,...,None,9.380713,36.525458,5.338779,0.639730,2026-08-07,7.0,True,63.0,66.2
2,SET:PTT,38.50,38.75,38.25,38.50,69669533.0,1.099675e+12,11.862213,0.0,0.054545,...,None,0.928621,9.916012,-10.894397,0.798900,2026-08-13,13.0,True,75.1,60.6
3,SET:GULF,65.75,67.25,65.50,66.75,63815355.0,9.822943e+11,11.190652,0.0,0.015970,...,None,2.878843,NaN,NaN,1.450192,2026-08-07,7.0,True,77.7,73.5
4,SET:AOT,63.50,64.00,63.25,63.75,21442821.0,9.071420e+11,50.319678,0.0,0.012756,...,None,7.023927,-5.897645,-3.410447,0.693466,2026-08-06,6.0,True,19.6,83.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,SET:QDC,0.07,0.07,0.06,0.07,393416.0,2.603312e+07,NaN,NaN,0.000000,...,None,0.152818,65.309112,-68.731857,3.761737,None,NaN,True,30.8,1.5
880,SET:CHO,0.02,0.03,0.02,0.02,7079386.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,False,0.5,0.6
881,SET:MVP,0.04,0.06,0.04,0.06,17360638.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,NaN,None,NaN,False,99.2,0.5
882,SET:SCL,1.66,1.66,1.61,1.65,214505.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,0.258610,None,NaN,False,76.0,89.0
883,SET:MMM,2.76,2.78,2.74,2.78,142908.0,NaN,NaN,NaN,0.046413,...,None,1.810839,NaN,NaN,0.495760,None,NaN,False,20.3,44.7

In [ ]:
# StockL_df =   StockL_df[(StockL_df["datetime_"] == StockL_df["datetime_"].max())]
StockL_df["datetime_"] = pd.to_datetime(StockL_df["datetime_"], errors='coerce')
StockL_df = StockL_df[StockL_df["datetime_"] == StockL_df["datetime_"].max()]

StockL_df =   StockL_df[(StockL_df["volume"] > 0 )]
StockL_df

,symbol,open,high,low,close,volume,Mcap,PE,payoutRatio,dividendYield,...,interest_coverage,PB,EPS_growth_YoY,Revenue_growth_YoY,beta,next_earnings,days_to_earnings,data_quality_ok,RS_rank_20d,RS_rank_60d
0,SET:DELTA,276.00,281.00,274.00,278.00,22743747.0,3.293088e+12,116.162460,0.0,0.002273,...,None,32.895360,64.176442,37.926010,1.991918,2026-10-27,88.0,True,1.9,10.0
1,SET:ADVANC,378.00,382.00,377.00,380.00,8489031.0,1.124251e+12,22.247332,0.0,0.040476,...,None,9.380713,36.525458,5.338779,0.639730,2026-08-07,7.0,True,63.0,66.2
2,SET:PTT,38.50,38.75,38.25,38.50,69669533.0,1.099675e+12,11.862213,0.0,0.054545,...,None,0.928621,9.916012,-10.894397,0.798900,2026-08-13,13.0,True,75.1,60.6
3,SET:GULF,65.75,67.25,65.50,66.75,63815355.0,9.822943e+11,11.190652,0.0,0.015970,...,None,2.878843,NaN,NaN,1.450192,2026-08-07,7.0,True,77.7,73.5
4,SET:AOT,63.50,64.00,63.25,63.75,21442821.0,9.071420e+11,50.319678,0.0,0.012756,...,None,7.023927,-5.897645,-3.410447,0.693466,2026-08-06,6.0,True,19.6,83.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,SET:TPOLY,0.09,0.11,0.09,0.10,158101.0,5.727595e+07,NaN,NaN,0.000000,...,None,0.400962,-620.386473,-1.609426,1.736496,None,NaN,True,30.8,1.8
877,SET:BTW,0.07,0.08,0.07,0.08,28002.0,6.048000e+07,NaN,NaN,0.000000,...,None,0.530610,-260.294118,14.701415,0.044747,None,NaN,True,88.1,10.8
879,SET:QDC,0.07,0.07,0.06,0.07,393416.0,2.603312e+07,NaN,NaN,0.000000,...,None,0.152818,65.309112,-68.731857,3.761737,None,NaN,True,30.8,1.5
882,SET:SCL,1.66,1.66,1.61,1.65,214505.0,NaN,NaN,NaN,NaN,...,None,NaN,NaN,NaN,0.258610,None,NaN,False,76.0,89.0
883,SET:MMM,2.76,2.78,2.74,2.78,142908.0,NaN,NaN,NaN,0.046413,...,None,1.810839,NaN,NaN,0.495760,None,NaN,False,20.3,44.7

In [ ]:
addlaststocktable(StockL_df)
addltabelCDC(StockL_df)

#StockL_df = StockL_df[StockL_df['Mcap'].fillna(0)]
# แก้ 2026-07-25: เอาตัวกรอง volume > 0 และ close > 0.07 ออก — ต้องการทุกตัวครบทุกวัน
# แก้ 2026-07-25: เลิกใช้ sentinel — ไม่มีข้อมูลต้องเป็น NaN ไม่งั้นเรียง 'PE ต่ำสุด' จะได้หุ้นไม่มีข้อมูลขึ้นบนเงียบๆ
StockL_df['Mcap'] = pd.to_numeric(StockL_df['Mcap'], errors='coerce')
StockL_df['PE'] = pd.to_numeric(StockL_df['PE'].replace(['Infinity','-Infinity','inf','-inf'], np.nan), errors='coerce')
# หมายเหตุ: PE ติดลบคือขาดทุนจริง ไม่ใช่ค่าเสีย — กรองด้วย PE > 0 หรือ data_quality_ok เอาตอนใช้งาน

# # Define conditions
# cond1 = (StockL_df['RSI14'] < 50) & (StockL_df['RSI14W'] < 50)
# cond2 = (StockL_df['RSI14'] >= 50) & (StockL_df['RSI14W'] < 50)
# cond3 = (StockL_df['RSI14'] >= 50) & (StockL_df['RSI14W'] >= 50)
# cond4 = (StockL_df['RSI14'] < 50) & (StockL_df['RSI14W'] >= 50)

# # Create zone column
# StockL_df['RSIzone'] = np.select(
#     [cond1, cond2, cond3, cond4],
#     ['zone1', 'zone2', 'zone3', 'zone4'],
#     default='unknown'
# )

# # Define conditions
# cond1_1 = (StockL_df['RSI14-1'] < 50) & (StockL_df['RSI14W-1'] < 50)
# cond2_1 = (StockL_df['RSI14-1'] >= 50) & (StockL_df['RSI14W-1'] < 50)
# cond3_1 = (StockL_df['RSI14-1'] >= 50) & (StockL_df['RSI14W-1'] >= 50)
# cond4_1 = (StockL_df['RSI14-1'] < 50) & (StockL_df['RSI14W-1'] >= 50)

# # Create zone column
# StockL_df['RSIzone-1'] = np.select(
#     [cond1_1, cond2_1, cond3_1, cond4_1],
#     ['zone1', 'zone2', 'zone3', 'zone4'],
#     default='unknown'
# )

# # Create RSIzoneMove column
# StockL_df['RSIzoneMove'] = np.where(
#     StockL_df['RSIzone'] == StockL_df['RSIzone-1'],
#     'Not move',
#     f"z{StockL_df.index[-1]+1} -> {StockL_df['RSIzone']}"
# )

StockL_df['MCDX_red1st_TF'] = ((StockL_df['MCDX_red'] > 0) & (StockL_df['MCDX_red-1'] <= 0))
StockL_df['MCDX_red2nd_TF'] = ((StockL_df['MCDX_red-1'] > 0) & (StockL_df['MCDX_red-2'] <= 0))
StockL_df['MCDX_max_red_TF'] = ((StockL_df['MCDX_red'] > 0) & (StockL_df['MCDX_max_red'] == StockL_df['MCDX_red']))

# Define conditions for current RSIzone
cond1 = (StockL_df['RSI14'] < 50) & (StockL_df['RSI14W'] < 50)
cond2 = (StockL_df['RSI14'] >= 50) & (StockL_df['RSI14W'] < 50)
cond3 = (StockL_df['RSI14'] >= 50) & (StockL_df['RSI14W'] >= 50)
cond4 = (StockL_df['RSI14'] < 50) & (StockL_df['RSI14W'] >= 50)

# Create current RSIzone column
StockL_df['RSIzone'] = np.select(
    [cond1, cond2, cond3, cond4],
    ['zone1', 'zone2', 'zone3', 'zone4'],
    default='unknown'
)

# Define conditions for previous RSIzone
cond1_1 = (StockL_df['RSI14-1'] < 50) & (StockL_df['RSI14W-1'] < 50)
cond2_1 = (StockL_df['RSI14-1'] >= 50) & (StockL_df['RSI14W-1'] < 50)
cond3_1 = (StockL_df['RSI14-1'] >= 50) & (StockL_df['RSI14W-1'] >= 50)
cond4_1 = (StockL_df['RSI14-1'] < 50) & (StockL_df['RSI14W-1'] >= 50)

# Create previous RSIzone column
StockL_df['RSIzone-1'] = np.select(
    [cond1_1, cond2_1, cond3_1, cond4_1],
    ['zone1', 'zone2', 'zone3', 'zone4'],
    default='unknown'
)

# Create RSIzoneMove column
# Correctly create RSIzoneMove column using apply
StockL_df['RSIzoneMove'] = StockL_df.apply(
    lambda row: 'Not move' if row['RSIzone'] == row['RSIzone-1'] else f"{row['RSIzone-1']} -> {row['RSIzone']}",
    axis=1
)

StockL_df = StockL_df.sort_values('Mcap', ascending=False)

StockL_df = StockL_df.reset_index(drop=True)

In [ ]:
# ============================================================
# 4 กลยุทธ์ใหม่ (เพิ่ม 2026-08-01): SuperTrend / Squeeze Momentum (LazyBear) /
# Smart Money Concepts (โครงสร้างราคาแบบพื้นฐาน: BOS-CHoCH-FVG-Order Block) /
# Cumulative Volume Delta (CVD)
# - รันหลัง main loop: อ่านแท่งจาก _ALL_D (cache) แล้ว merge เข้า StockL_df ด้วยคอลัมน์ Name
# - ไม่แตะเซลล์เดิม รันซ้ำได้ (ลบคอลัมน์ชุดนี้ทิ้งก่อน merge ทุกครั้ง)
# - หมายเหตุ CVD: แท่งรายวันไม่มีข้อมูล bid/ask จึงประมาณ delta จากตำแหน่งปิดในแท่ง
#   delta = volume x ((close-low)-(high-close))/(high-low) — เป็นค่าประมาณ ไม่เท่า CVD จาก tick จริง
# ============================================================
_S4_BARS = 400            # ใช้กี่แท่งล่าสุดต่อหุ้น
_S4_SWING = 5             # SMC: ยืนยัน swing ด้วยแท่งซ้าย/ขวาข้างละกี่แท่ง
_S4_ST_P, _S4_ST_M = 10, 3.0     # SuperTrend: ATR period / multiplier (ค่ามาตรฐาน TradingView)
_S4_FIRE_BARS = 5         # Squeeze: นับว่า "เพิ่งคลายตัว" ภายในกี่แท่ง
_S4_EVENT_BARS = 10       # SMC: นับว่า "เพิ่งเกิด BOS/CHoCH" ภายในกี่แท่ง

def _s4_tr(_df):
  _pc = _df['close'].shift(1)
  return pd.concat([_df['high'] - _df['low'], (_df['high'] - _pc).abs(), (_df['low'] - _pc).abs()], axis=1).max(axis=1)

def s4_supertrend(_df, _period=_S4_ST_P, _mult=_S4_ST_M):
  # คืน (เส้น SuperTrend, ทิศทาง 1/-1) — สูตรมาตรฐาน: เทียบ close กับ final band แท่งก่อนหน้า
  _atr = _s4_tr(_df).ewm(alpha=1.0/_period, adjust=False, min_periods=_period).mean().values
  _hl2 = ((_df['high'] + _df['low']) / 2).values
  _c = _df['close'].values
  _n = len(_c)
  _st = np.full(_n, np.nan)
  _dir = np.zeros(_n)
  _fu = _fl = np.nan          # final upper / lower band
  _d = 1
  for _i in range(_n):
    if _atr[_i] != _atr[_i]:
      continue
    _ub = _hl2[_i] + _mult * _atr[_i]
    _lb = _hl2[_i] - _mult * _atr[_i]
    if _fu != _fu:            # แท่งแรกที่ ATR ใช้ได้
      _fu, _fl = _ub, _lb
    else:
      _fu = _ub if (_ub < _fu or _c[_i-1] > _fu) else _fu
      _fl = _lb if (_lb > _fl or _c[_i-1] < _fl) else _fl
      if _c[_i] > _fu:
        _d = 1
      elif _c[_i] < _fl:
        _d = -1
    _dir[_i] = _d
    _st[_i] = _fl if _d == 1 else _fu
  return pd.Series(_st, index=_df.index), pd.Series(_dir, index=_df.index)

def s4_squeeze(_df, _bb_len=20, _bb_mult=2.0, _kc_len=20, _kc_mult=1.5, _mom_len=20):
  # LazyBear Squeeze Momentum: บีบเมื่อ Bollinger ทั้งเส้นเข้าไปอยู่ใน Keltner
  _cl = _df['close']
  _basis = _cl.rolling(_bb_len).mean()
  _dev = _bb_mult * _cl.rolling(_bb_len).std(ddof=0)        # ddof=0 ให้ตรง stdev ของ TradingView
  _ma = _cl.rolling(_kc_len).mean()
  _rng = _s4_tr(_df).rolling(_kc_len).mean() * _kc_mult
  _sqz_on = ((_basis - _dev) > (_ma - _rng)) & ((_basis + _dev) < (_ma + _rng))
  _hh = _df['high'].rolling(_mom_len).max()
  _ll = _df['low'].rolling(_mom_len).min()
  _mid = ((_hh + _ll) / 2 + _cl.rolling(_mom_len).mean()) / 2
  _src = _cl - _mid
  _x = np.arange(_mom_len)
  _xm = _x.mean()
  _den = ((_x - _xm) ** 2).sum()
  def _lr_last(_y):            # ค่าเส้น linear regression ณ จุดสุดท้ายของหน้าต่าง
    _b = ((_x - _xm) * (_y - _y.mean())).sum() / _den
    return _y.mean() + _b * (_mom_len - 1 - _xm)
  _mom = _src.rolling(_mom_len).apply(_lr_last, raw=True)
  return _sqz_on.fillna(False), _mom

def s4_cvd(_df):
  # delta ประมาณจากตำแหน่งราคาปิดในแท่ง แล้วสะสมเป็น CVD
  _rng = (_df['high'] - _df['low'])
  _delta = _df['volume'] * np.where(_rng > 0, ((_df['close'] - _df['low']) - (_df['high'] - _df['close'])) / _rng, 0.0)
  _delta = pd.Series(_delta, index=_df.index)
  return _delta, _delta.cumsum()

def s4_smc(_df, _sw=_S4_SWING):
  # โครงสร้างราคาแบบพื้นฐาน ไม่มองอนาคต: swing ยืนยันหลังผ่านไป _sw แท่ง แล้วดูการทะลุด้วยราคาปิด
  _h = _df['high'].values; _l = _df['low'].values
  _c = _df['close'].values; _o = _df['open'].values
  _n = len(_c)
  _events = []                    # (ตำแหน่งแท่ง, ชนิด, ระดับที่ทะลุ)
  _fvg_bull = []; _fvg_bear = []  # [top, bottom, แท่งที่เกิด, ถูกปิดแล้วหรือยัง]
  _ob_bull = None; _ob_bear = None       # [top, bottom, แท่งที่เกิด]
  _trend = 0
  _bk_sh = np.nan; _bk_sl = np.nan       # ระดับ swing ที่ "รอทะลุ" (ใช้แล้วทิ้ง รอ swing ใหม่)
  _sh_lv = np.nan; _sl_lv = np.nan       # swing ยืนยันล่าสุด (ไว้ดูแนวรับ/ต้านโครงสร้าง)
  for _i in range(_n):
    _j = _i - _sw                        # pivot ที่เพิ่งยืนยันได้ ณ แท่ง _i
    if _j >= _sw:
      if _h[_j] >= _h[_j-_sw:_j+_sw+1].max():
        _bk_sh = _sh_lv = _h[_j]
      if _l[_j] <= _l[_j-_sw:_j+_sw+1].min():
        _bk_sl = _sl_lv = _l[_j]
    if _i >= 2:                          # Fair Value Gap (ช่องว่าง 3 แท่ง)
      if _l[_i] > _h[_i-2]:
        _fvg_bull.append([_l[_i], _h[_i-2], _i, False])
      if _h[_i] < _l[_i-2]:
        _fvg_bear.append([_l[_i-2], _h[_i], _i, False])
    for _z in _fvg_bull:                 # ราคาย้อนลงมาปิดช่อง = ใช้ไปแล้ว
      if not _z[3] and _z[2] < _i and _l[_i] <= _z[1]:
        _z[3] = True
    for _z in _fvg_bear:
      if not _z[3] and _z[2] < _i and _h[_i] >= _z[0]:
        _z[3] = True
    if _bk_sh == _bk_sh and _c[_i] > _bk_sh:      # ทะลุ swing high
      _events.append((_i, 'CHoCH_up' if _trend == -1 else 'BOS_up', _bk_sh))
      _trend = 1
      for _k in range(_i-1, max(_i-15, -1), -1):  # Order Block = แท่งแดงสุดท้ายก่อนแท่งทะลุ
        if _c[_k] < _o[_k]:
          _ob_bull = [_h[_k], _l[_k], _k]
          break
      _bk_sh = np.nan
    if _bk_sl == _bk_sl and _c[_i] < _bk_sl:      # ทะลุ swing low
      _events.append((_i, 'CHoCH_down' if _trend == 1 else 'BOS_down', _bk_sl))
      _trend = -1
      for _k in range(_i-1, max(_i-15, -1), -1):
        if _c[_k] > _o[_k]:
          _ob_bear = [_h[_k], _l[_k], _k]
          break
      _bk_sl = np.nan
    if _ob_bull is not None and _c[_i] < _ob_bull[1]:   # ปิดหลุดโซน = OB เสีย
      _ob_bull = None
    if _ob_bear is not None and _c[_i] > _ob_bear[0]:
      _ob_bear = None
  return {'trend': _trend, 'events': _events, 'fvg_bull': _fvg_bull, 'fvg_bear': _fvg_bear,
          'ob_bull': _ob_bull, 'ob_bear': _ob_bear, 'swing_high': _sh_lv, 'swing_low': _sl_lv}

def s4_lastrow(_df):
  # สรุปค่าแท่งสุดท้ายของทั้ง 4 กลยุทธ์เป็น dict (แนวเดียวกับ _extra_lastrow)
  _o = {}
  _n = len(_df)
  _px = float(_df['close'].iloc[-1])

  _st, _dir = s4_supertrend(_df)
  _o['ST_dir'] = float(_dir.iloc[-1])
  _o['ST_line'] = float(_st.iloc[-1]) if _st.iloc[-1] == _st.iloc[-1] else np.nan
  _o['ST_gap%'] = ((_px - _o['ST_line']) / _px * 100) if _o['ST_line'] == _o['ST_line'] else np.nan
  _o['ST_flip_up_TF'] = bool(_n > 1 and _dir.iloc[-1] == 1 and _dir.iloc[-2] == -1)
  _o['ST_flip_down_TF'] = bool(_n > 1 and _dir.iloc[-1] == -1 and _dir.iloc[-2] == 1)
  _chg = np.flatnonzero(_dir.values[1:] != _dir.values[:-1])
  _o['ST_bars_in_trend'] = float(_n - 2 - _chg[-1]) if len(_chg) else np.nan

  _sqz_on, _mom = s4_squeeze(_df)
  _o['SQZ_on_TF'] = bool(_sqz_on.iloc[-1])
  _k = 0
  for _x in _sqz_on.values[::-1]:
    if _x:
      _k += 1
    else:
      break
  _o['SQZ_bars_on'] = _k
  _off = ~_sqz_on
  _fired = _off & _sqz_on.shift(1).fillna(False)        # แท่งแรกที่หลุดจากสภาพบีบ
  _pos = np.flatnonzero(_fired.values)
  _since = (_n - 1 - _pos[-1]) if len(_pos) else np.nan
  _o['SQZ_bars_since_fire'] = float(_since) if _since == _since else np.nan
  _o['SQZ_fired_TF'] = bool(_since == _since and _since < _S4_FIRE_BARS)
  _o['SQZ_mom'] = float(_mom.iloc[-1]) if _mom.notna().any() else np.nan
  _o['SQZ_mom_rising_TF'] = bool(_n > 1 and _mom.iloc[-1] == _mom.iloc[-1] and _mom.iloc[-2] == _mom.iloc[-2] and _mom.iloc[-1] > _mom.iloc[-2])
  _o['SQZ_fired_up_TF'] = bool(_o['SQZ_fired_TF'] and _o['SQZ_mom'] == _o['SQZ_mom'] and _o['SQZ_mom'] > 0)

  _smc = s4_smc(_df)
  _o['SMC_trend'] = _smc['trend']
  if _smc['events']:
    _ei, _en, _el = _smc['events'][-1]
    _o['SMC_event'] = _en
    _o['SMC_event_level'] = float(_el)
    _o['SMC_bars_since_event'] = float(_n - 1 - _ei)
  else:
    _o['SMC_event'] = ''
    _o['SMC_event_level'] = np.nan
    _o['SMC_bars_since_event'] = np.nan
  _recent = [_e[1] for _e in _smc['events'] if _e[0] >= _n - _S4_EVENT_BARS]
  _o['SMC_BOS_up_TF'] = 'BOS_up' in _recent
  _o['SMC_CHoCH_up_TF'] = 'CHoCH_up' in _recent
  _o['SMC_BOS_down_TF'] = 'BOS_down' in _recent
  _o['SMC_CHoCH_down_TF'] = 'CHoCH_down' in _recent
  _o['SMC_swing_high'] = _smc['swing_high']
  _o['SMC_swing_low'] = _smc['swing_low']
  _zb = [_z for _z in _smc['fvg_bull'] if not _z[3]]
  _o['SMC_FVG_bull_top'] = float(_zb[-1][0]) if _zb else np.nan
  _o['SMC_FVG_bull_bottom'] = float(_zb[-1][1]) if _zb else np.nan
  _o['SMC_in_FVG_bull_TF'] = bool(_zb and _zb[-1][1] <= _px <= _zb[-1][0])
  _ob = _smc['ob_bull']
  _o['SMC_OB_bull_top'] = float(_ob[0]) if _ob else np.nan
  _o['SMC_OB_bull_bottom'] = float(_ob[1]) if _ob else np.nan
  _o['SMC_in_OB_bull_TF'] = bool(_ob and _ob[1] <= _px <= _ob[0])

  _delta, _cvd = s4_cvd(_df)
  _o['CVD_delta'] = float(_delta.iloc[-1])
  _v20 = float(_df['volume'].tail(20).sum())
  _o['CVD_delta_ratio20'] = (float(_delta.tail(20).sum()) / _v20) if _v20 > 0 else np.nan
  _av = float(_df['volume'].tail(20).mean())
  _o['CVD_slope20'] = ((float(_cvd.iloc[-1]) - float(_cvd.iloc[-21])) / 20 / _av) if (_n > 21 and _av > 0) else np.nan
  _o['CVD_up_TF'] = bool(_o['CVD_slope20'] == _o['CVD_slope20'] and _o['CVD_slope20'] > 0)
  if _n > 40:                    # divergence 40 แท่ง: แบ่งครึ่งเทียบ (แนวเดียวกับ RSI_div เดิม)
    _c1 = _df['close'].iloc[-40:]; _d1 = _cvd.iloc[-40:]
    _o['CVD_div_bull_TF'] = bool(_c1.iloc[20:].min() <= _c1.iloc[:20].min() and _d1.iloc[20:].min() > _d1.iloc[:20].min())
    _o['CVD_div_bear_TF'] = bool(_c1.iloc[20:].max() >= _c1.iloc[:20].max() and _d1.iloc[20:].max() < _d1.iloc[:20].max())
  else:
    _o['CVD_div_bull_TF'] = False
    _o['CVD_div_bear_TF'] = False
  return _o

# --- วนทุกหุ้นจาก cache แล้ว merge เข้า StockL_df ---
_s4_rows = []
_s4_skip = []
for _sym, _g in _ALL_D.groupby('sym'):
  _d4 = _g.drop(columns='sym').tail(_S4_BARS)
  if len(_d4) < 60:
    _s4_skip.append((_sym, 'bars<60'))
    continue
  try:
    _r = {'Name': _sym}
    _r.update(s4_lastrow(_d4))
    _s4_rows.append(_r)
  except Exception as _e:
    _s4_skip.append((_sym, repr(_e)[:100]))
Strat4_df = pd.DataFrame(_s4_rows)
_s4_cols = [_c for _c in Strat4_df.columns if _c != 'Name']
StockL_df = StockL_df.drop(columns=[_c for _c in _s4_cols + ['STRAT4_SCORE'] if _c in StockL_df.columns])
StockL_df = StockL_df.merge(Strat4_df, on='Name', how='left')

# --- คะแนนรวมของ 4 กลยุทธ์ (0-100 โปร่งใส ปรับน้ำหนักเองได้) ---
def _s4b(_col):
  return StockL_df[_col].fillna(False).astype(bool)
_s4sc  = (StockL_df['ST_dir'] == 1) * 25                     # SuperTrend ขาขึ้น
_s4sc += _s4b('SQZ_fired_up_TF') * 20                        # เพิ่งคลายบีบ + โมเมนตัมบวก
_s4sc += (_s4b('SQZ_on_TF') & (pd.to_numeric(StockL_df['SQZ_mom'], errors='coerce') > 0)) * 5   # กำลังบีบพร้อมโมเมนตัมบวก = รอจังหวะ
_s4sc += (StockL_df['SMC_trend'] == 1) * 15                  # โครงสร้างขาขึ้น
_s4sc += (_s4b('SMC_BOS_up_TF') | _s4b('SMC_CHoCH_up_TF')) * 10
_s4sc += (pd.to_numeric(StockL_df['CVD_delta_ratio20'], errors='coerce') > 0) * 15   # แรงซื้อสุทธิ 20 แท่ง
_s4sc += _s4b('CVD_div_bull_TF') * 10
StockL_df['STRAT4_SCORE'] = _s4sc.astype(float)
StockL_df.loc[StockL_df.get('screened_out', pd.Series(False, index=StockL_df.index)).fillna(False) == True, 'STRAT4_SCORE'] = np.nan

# --- คำอธิบายคอลัมน์ใหม่ เข้าระบบ metadata เดิม ---
try:
  _META_EXACT.update({
   'ST_dir': ('กลยุทธ์ SuperTrend', 'ทิศทาง SuperTrend(10,3): 1 ขาขึ้น / -1 ขาลง', '1/-1'),
   'ST_line': ('กลยุทธ์ SuperTrend', 'ระดับเส้น SuperTrend ล่าสุด ใช้เป็นแนว trailing stop', 'บาท'),
   'ST_gap%': ('กลยุทธ์ SuperTrend', 'ระยะราคาปิดห่างจากเส้น SuperTrend (บวก = อยู่เหนือเส้น)', '%'),
   'ST_flip_up_TF': ('กลยุทธ์ SuperTrend', 'แท่งล่าสุดเพิ่งพลิกเป็นขาขึ้น', 'True/False'),
   'ST_flip_down_TF': ('กลยุทธ์ SuperTrend', 'แท่งล่าสุดเพิ่งพลิกเป็นขาลง', 'True/False'),
   'ST_bars_in_trend': ('กลยุทธ์ SuperTrend', 'อยู่ในเทรนด์ปัจจุบันมาแล้วกี่แท่ง', 'แท่ง'),
   'SQZ_on_TF': ('กลยุทธ์ Squeeze', 'กำลังบีบตัว (Bollinger หดเข้าไปใน Keltner) = สะสมพลัง', 'True/False'),
   'SQZ_bars_on': ('กลยุทธ์ Squeeze', 'บีบต่อเนื่องมาแล้วกี่แท่ง (ยิ่งนานยิ่งมีพลัง)', 'แท่ง'),
   'SQZ_fired_TF': ('กลยุทธ์ Squeeze', 'เพิ่งคลายตัวภายใน ' + str(_S4_FIRE_BARS) + ' แท่ง', 'True/False'),
   'SQZ_bars_since_fire': ('กลยุทธ์ Squeeze', 'คลายตัวมาแล้วกี่แท่ง', 'แท่ง'),
   'SQZ_mom': ('กลยุทธ์ Squeeze', 'โมเมนตัม (linear regression 20 แท่ง) บวก = แรงขึ้น', 'บาท'),
   'SQZ_mom_rising_TF': ('กลยุทธ์ Squeeze', 'โมเมนตัมกำลังเพิ่มขึ้นจากแท่งก่อน', 'True/False'),
   'SQZ_fired_up_TF': ('กลยุทธ์ Squeeze', 'สัญญาณ breakout: เพิ่งคลายบีบ + โมเมนตัมบวก', 'True/False'),
   'SMC_trend': ('กลยุทธ์ SMC', 'โครงสร้างราคาปัจจุบัน: 1 ขาขึ้น / -1 ขาลง / 0 ยังไม่ชัด', '1/0/-1'),
   'SMC_event': ('กลยุทธ์ SMC', 'เหตุการณ์ล่าสุด: BOS = ทะลุตามเทรนด์เดิม, CHoCH = ทะลุสวนเทรนด์ (สัญญาณกลับตัว)', 'ข้อความ'),
   'SMC_event_level': ('กลยุทธ์ SMC', 'ระดับ swing ที่ถูกทะลุครั้งล่าสุด', 'บาท'),
   'SMC_bars_since_event': ('กลยุทธ์ SMC', 'เหตุการณ์ล่าสุดผ่านมาแล้วกี่แท่ง', 'แท่ง'),
   'SMC_BOS_up_TF': ('กลยุทธ์ SMC', 'มี BOS ขาขึ้นภายใน ' + str(_S4_EVENT_BARS) + ' แท่ง', 'True/False'),
   'SMC_CHoCH_up_TF': ('กลยุทธ์ SMC', 'มี CHoCH ขาขึ้น (เพิ่งกลับตัวขึ้น) ภายใน ' + str(_S4_EVENT_BARS) + ' แท่ง', 'True/False'),
   'SMC_BOS_down_TF': ('กลยุทธ์ SMC', 'มี BOS ขาลงภายใน ' + str(_S4_EVENT_BARS) + ' แท่ง', 'True/False'),
   'SMC_CHoCH_down_TF': ('กลยุทธ์ SMC', 'มี CHoCH ขาลง (เพิ่งกลับตัวลง) ภายใน ' + str(_S4_EVENT_BARS) + ' แท่ง', 'True/False'),
   'SMC_swing_high': ('กลยุทธ์ SMC', 'swing high ยืนยันล่าสุด = แนวต้านโครงสร้าง', 'บาท'),
   'SMC_swing_low': ('กลยุทธ์ SMC', 'swing low ยืนยันล่าสุด = แนวรับโครงสร้าง', 'บาท'),
   'SMC_FVG_bull_top': ('กลยุทธ์ SMC', 'ขอบบนของ Fair Value Gap ขาขึ้นล่าสุดที่ยังไม่ถูกปิด (โซนรอรับ)', 'บาท'),
   'SMC_FVG_bull_bottom': ('กลยุทธ์ SMC', 'ขอบล่างของ FVG ขาขึ้นล่าสุดที่ยังไม่ถูกปิด', 'บาท'),
   'SMC_in_FVG_bull_TF': ('กลยุทธ์ SMC', 'ราคาปิดอยู่ในโซน FVG ขาขึ้น (จุดสังเกตแรงซื้อ)', 'True/False'),
   'SMC_OB_bull_top': ('กลยุทธ์ SMC', 'ขอบบน Order Block ขาขึ้นล่าสุดที่ยังไม่เสีย (แท่งแดงสุดท้ายก่อนทะลุขึ้น)', 'บาท'),
   'SMC_OB_bull_bottom': ('กลยุทธ์ SMC', 'ขอบล่าง Order Block ขาขึ้นล่าสุด', 'บาท'),
   'SMC_in_OB_bull_TF': ('กลยุทธ์ SMC', 'ราคาปิดอยู่ในโซน Order Block ขาขึ้น', 'True/False'),
   'CVD_delta': ('กลยุทธ์ CVD', 'delta ประมาณของแท่งล่าสุด (บวก = แรงซื้อชนะ) — ประมาณจาก OHLCV ไม่ใช่ tick จริง', 'หุ้น'),
   'CVD_delta_ratio20': ('กลยุทธ์ CVD', 'ผลรวม delta 20 แท่ง / ผลรวม volume 20 แท่ง (-1 ถึง 1, บวก = ซื้อสะสม)', 'สัดส่วน'),
   'CVD_slope20': ('กลยุทธ์ CVD', 'ความชันของเส้น CVD 20 แท่ง เทียบ volume เฉลี่ย', 'สัดส่วน'),
   'CVD_up_TF': ('กลยุทธ์ CVD', 'CVD กำลังยกตัวขึ้น (เงินไหลเข้า)', 'True/False'),
   'CVD_div_bull_TF': ('กลยุทธ์ CVD', 'divergence ขาขึ้น 40 แท่ง: ราคาทำ low ต่ำลงแต่ CVD ยกขึ้น = แอบสะสม', 'True/False'),
   'CVD_div_bear_TF': ('กลยุทธ์ CVD', 'divergence ขาลง 40 แท่ง: ราคาทำ high ใหม่แต่ CVD ไม่ยืนยัน = แรงซื้อแผ่ว', 'True/False'),
   'STRAT4_SCORE': ('คะแนน', 'คะแนนรวม 4 กลยุทธ์ 0-100: ST ขาขึ้น 25 / เพิ่งคลายบีบ+โมเมนตัมบวก 20 / กำลังบีบโมเมนตัมบวก 5 / โครงสร้างขาขึ้น 15 / BOS-CHoCH ขึ้นใหม่ 10 / CVD ซื้อสะสม 15 / CVD div bull 10', 'คะแนน'),
  })
except NameError:
  pass                       # ยังไม่ได้รันเซลล์ metadata — export จะอธิบายเป็น 'อื่นๆ' แทน

print('STRAT4: คำนวณ', len(Strat4_df), 'ตัว | ข้าม', len(_s4_skip), _s4_skip[:5])
print('  SuperTrend ขาขึ้น:', int((Strat4_df['ST_dir'] == 1).sum()),
      '| กำลังบีบ:', int(Strat4_df['SQZ_on_TF'].sum()),
      '| เพิ่งคลายบีบขึ้น:', int(Strat4_df['SQZ_fired_up_TF'].sum()),
      '| โครงสร้างขาขึ้น:', int((Strat4_df['SMC_trend'] == 1).sum()),
      '| CVD ซื้อสะสม:', int((Strat4_df['CVD_delta_ratio20'] > 0).sum()),
      '| CVD div bull:', int(Strat4_df['CVD_div_bull_TF'].sum()))

In [ ]:
import os as _os2
_xlsx = 'listSET_' + lv_date + '.xlsx'
_pqf  = 'listSET_' + lv_date + '.parquet'

# --- รวมตัวที่ถูก funnel กรองออก กลับเข้าไฟล์ (ไม่ให้หุ้นหายไปจากไฟล์) ---
# แถวพวกนี้มี ราคา/พื้นฐาน/sector ครบ แต่ไม่มี indicator เพราะไม่ได้เข้า loop คำนวณ
if 'screened_out' not in StockL_df.columns:            # กันรันซ้ำแล้วธงถูกล้าง
    StockL_df['screened_out'] = False
_FMAP = {'sector':'sector','industry':'industry','Mcap':'marketCap','PE':'trailingPE','PB':'pb',
         'ROE':'roe','ROA':'roa','D_E':'de','net_margin':'netMargin','gross_margin':'grossMargin',
         'operating_margin':'opMargin','current_ratio':'currentRatio','interest_coverage':'interestCov',
         'EPS_growth_YoY':'epsGrowth','Revenue_growth_YoY':'revGrowth','dividendYield':'dividendYield',
         'payoutRatio':'payoutRatio','beta':'beta','floatShares':'floatShares',
         'sharesOutstanding':'sharesOutstanding','enterpriseValue':'enterpriseValue'}
if _dropped:
    _extra = []
    _seen = set(StockL_df['symbol'].astype(str))       # รันซ้ำแล้วต้องไม่เพิ่มแถวซ้ำ
    for _s in _dropped:
        if 'SET:' + _s in _seen:
            continue
        _i = FUND.get(_s, {})
        _row = {_k: _i.get(_v) for _k, _v in _FMAP.items()}
        _row['symbol'] = 'SET:' + _s
        _row['close'] = _i.get('_close')
        _row['screened_out'] = True
        _row['data_quality_ok'] = False
        _ne = _i.get('nextEarnings')
        if _ne:
            _nd = pd.to_datetime(_ne, unit='s')
            _row['next_earnings'] = _nd.strftime('%Y-%m-%d')
            _row['days_to_earnings'] = int((_nd.normalize() - pd.Timestamp.today().normalize()).days)
        _extra.append(_row)
    if _extra:
        StockL_df = pd.concat([StockL_df, pd.DataFrame(_extra)], ignore_index=True)
    print('MERGE: ใส่ตัวที่ถูกกรองออกกลับเข้าไฟล์', len(_extra), 'ตัว (ราคา/พื้นฐานเท่านั้น)')

_symq = StockL_df['symbol'].astype(str).str.replace('SET:', '', regex=False)
StockL_df['avg_turnover_10d'] = [((FUND.get(_s, {}).get('_close') or np.nan) * (FUND.get(_s, {}).get('_avgvol10') or np.nan)) for _s in _symq]

# --- คะแนนรวม 0-100 (โปร่งใส ปรับน้ำหนักเองได้) ---
def _b(_col):
    return StockL_df[_col].fillna(False).astype(bool) if _col in StockL_df.columns else pd.Series(False, index=StockL_df.index)
def _n(_col):
    return pd.to_numeric(StockL_df[_col], errors='coerce') if _col in StockL_df.columns else pd.Series(np.nan, index=StockL_df.index)

_score  = _b('CDC') * 20                                        # EMA12 > EMA26
_score += (_n('MACD_hist') > 0) * 15                            # โมเมนตัมบวก
_score += (_n('RS_rank_60d') >= 70) * 15                        # ชนะตลาด 60 วัน
_score += (_n('close') > _n('EMA26')) * 10
_score += ((_n('RSI14') >= 45) & (_n('RSI14') <= 70)) * 10      # ไม่อ่อนแอ ไม่ overbought
_score += (_n('Values') > _n('ValMA25')) * 10                   # วอลุ่มเข้า
_score += (_n('ROE') > 10) * 10
_score += (_n('EPS_growth_YoY') > 0) * 10
StockL_df['SCORE'] = _score.astype(float)
StockL_df.loc[StockL_df['screened_out'] == True, 'SCORE'] = np.nan   # ไม่มี indicator = ให้คะแนนไม่ได้


# --- Metadata: อธิบายทุกคอลัมน์ ให้คนและ AI อ่านเข้าใจ ---
try:
    _meta = _build_metadata(StockL_df)
    _meta.to_csv('listSET_' + lv_date + '_columns.csv', index=False, encoding='utf-8-sig')   # ไฟล์เล็ก ให้ AI อ่านก่อนแตะข้อมูลจริง
    print('METADATA:', len(_meta), 'คอลัมน์ | ยังไม่มีคำอธิบาย', int((_meta['กลุ่ม'] == 'อื่นๆ').sum()))
except NameError:
    _meta = None
    print('METADATA: ข้ามไป — ยังไม่ได้รันเซลล์ที่นิยาม _build_metadata (กด Run all)')

with pd.ExcelWriter(_xlsx) as _w:
    if _meta is not None:
        _meta.to_excel(_w, sheet_name='Metadata', index=False)     # พจนานุกรมคอลัมน์ อ่านก่อนใช้ไฟล์
    StockL_df.to_excel(_w, sheet_name='ALL', index=False)          # ครบทุกคอลัมน์

try:                                                              # parquet: อ่านด้วย pandas ในไม่กี่วินาที
    StockL_df.to_parquet(_pqf, index=False)
except Exception as _e:
    _tmp = StockL_df.copy()
    for _c in _tmp.columns[_tmp.dtypes == object]:
        _tmp[_c] = _tmp[_c].astype(str)
    _tmp.to_parquet(_pqf, index=False)
    print('parquet: แปลง object -> str ก่อนเซฟ |', repr(_e)[:80])

print('EXPORT:', _xlsx, _os2.path.getsize(_xlsx), 'bytes |', StockL_df.shape[0], 'rows x', StockL_df.shape[1], 'cols')
print('EXPORT:', _pqf, _os2.path.getsize(_pqf), 'bytes')
print('รวมในไฟล์:', len(StockL_df), 'ตัว = คำนวณเต็ม', int((~StockL_df['screened_out']).sum()), '+ ราคา/พื้นฐานอย่างเดียว', int(StockL_df['screened_out'].sum()))
files.download(_xlsx)

METADATA: 1666 คอลัมน์ | ยังไม่มีคำอธิบาย 42
EXPORT: listSET_20260731.xlsx 10110412 bytes | 853 rows x 1666 cols
EXPORT: listSET_20260731.parquet 7556580 bytes
รวมในไฟล์: 853 ตัว = คำนวณเต็ม 853 + ราคา/พื้นฐานอย่างเดียว 0

In [ ]:
print('LV_DATE:', lv_date)

LV_DATE: 20260731

In [ ]:
# ============================================================
# ตัวอย่างคัดกรองจาก 4 กลยุทธ์ (ปรับเงื่อนไขเองได้ตามสะดวก)
# ============================================================
_S4_SHOW = ['Name', 'close', 'STRAT4_SCORE', 'SCORE', 'ST_dir', 'ST_gap%', 'ST_bars_in_trend',
            'SQZ_on_TF', 'SQZ_bars_on', 'SQZ_fired_up_TF', 'SQZ_mom',
            'SMC_trend', 'SMC_event', 'SMC_bars_since_event', 'SMC_in_FVG_bull_TF', 'SMC_in_OB_bull_TF',
            'CVD_delta_ratio20', 'CVD_div_bull_TF', 'Mcap', 'sector']
_S4_SHOW = [_c for _c in _S4_SHOW if _c in StockL_df.columns]
_S4 = StockL_df[StockL_df['STRAT4_SCORE'].notna()]

print('==== 1) คะแนนรวม 4 กลยุทธ์สูงสุด 20 อันดับ ====')
display(_S4.sort_values(['STRAT4_SCORE', 'Mcap'], ascending=False)[_S4_SHOW].head(20))

print('==== 2) SuperTrend เพิ่งพลิกขึ้น (ภายใน 3 แท่ง) ====')
_f = _S4[(_S4['ST_dir'] == 1) & (_S4['ST_bars_in_trend'] <= 3)]
display(_f.sort_values('Mcap', ascending=False)[_S4_SHOW].head(20))

print('==== 3) Squeeze: เพิ่งคลายบีบ + โมเมนตัมบวก (สัญญาณ breakout) ====')
_f = _S4[_S4['SQZ_fired_up_TF'].fillna(False).astype(bool)]
display(_f.sort_values('SQZ_bars_on', ascending=False)[_S4_SHOW].head(20))

print('==== 4) Squeeze: กำลังบีบนาน 10 แท่งขึ้นไป (รอจังหวะระเบิด) ====')
_f = _S4[(_S4['SQZ_on_TF'].fillna(False).astype(bool)) & (_S4['SQZ_bars_on'] >= 10)]
display(_f.sort_values('SQZ_bars_on', ascending=False)[_S4_SHOW].head(20))

print('==== 5) SMC: เพิ่งกลับตัวขึ้น (CHoCH up) หรือ BOS up ใหม่ ====')
_f = _S4[_S4['SMC_CHoCH_up_TF'].fillna(False).astype(bool) | _S4['SMC_BOS_up_TF'].fillna(False).astype(bool)]
display(_f.sort_values('SMC_bars_since_event')[_S4_SHOW].head(20))

print('==== 6) SMC: ราคาย่อลงมาในโซนรอรับ (FVG หรือ Order Block ขาขึ้น) ====')
_f = _S4[(_S4['SMC_in_FVG_bull_TF'].fillna(False).astype(bool) | _S4['SMC_in_OB_bull_TF'].fillna(False).astype(bool))
         & (_S4['SMC_trend'] == 1)]
display(_f.sort_values('Mcap', ascending=False)[_S4_SHOW].head(20))

print('==== 7) CVD: แอบสะสม — divergence ขาขึ้น หรือแรงซื้อสุทธิเข้ม ====')
_f = _S4[_S4['CVD_div_bull_TF'].fillna(False).astype(bool) | (_S4['CVD_delta_ratio20'] > 0.15)]
display(_f.sort_values('CVD_delta_ratio20', ascending=False)[_S4_SHOW].head(20))

print('==== 8) จัดเต็ม: ST ขาขึ้น + โครงสร้างขาขึ้น + CVD ซื้อสะสม + วอลุ่มเข้า ====')
_f = _S4[(_S4['ST_dir'] == 1) & (_S4['SMC_trend'] == 1) & (_S4['CVD_delta_ratio20'] > 0)
         & (pd.to_numeric(_S4.get('Values'), errors='coerce') > pd.to_numeric(_S4.get('ValMA25'), errors='coerce'))]
display(_f.sort_values('STRAT4_SCORE', ascending=False)[_S4_SHOW].head(20))

In [ ]:
# ============================================================
# กราฟรวม 4 กลยุทธ์รายตัว: แท่งเทียน + SuperTrend + โซน SMC (FVG/OB/BOS/CHoCH)
# + แผง Squeeze Momentum + แผง CVD    เรียกใช้: graph_strat4('PTT')
# ============================================================
def graph_strat4(_sym, _bars=250):
  pio.templates.default = "plotly_white"
  _g = _ALL_D[_ALL_D['sym'] == _sym]
  if len(_g) == 0:
    print('ไม่พบข้อมูล', _sym, 'ใน cache (_ALL_D)')
    return
  _d = _g.drop(columns='sym').tail(_S4_BARS)
  _st, _dir = s4_supertrend(_d)
  _sqz_on, _mom = s4_squeeze(_d)
  _delta, _cvd = s4_cvd(_d)
  _smc = s4_smc(_d)

  _d = _d.tail(_bars)
  _st = _st.tail(_bars); _dir = _dir.tail(_bars)
  _sqz_on = _sqz_on.tail(_bars); _mom = _mom.tail(_bars); _cvd = _cvd.tail(_bars)
  _n0 = len(_g.drop(columns='sym').tail(_S4_BARS)) - len(_d)      # ตำแหน่งแท่งแรกที่โชว์ (ไว้แปลง index เหตุการณ์)
  _x0, _x1 = _d.index[0], _d.index[-1]

  fig = make_subplots(rows=3, cols=1, shared_xaxes=True, vertical_spacing=0.02,
                      row_heights=[0.62, 0.19, 0.19])

  # แถว 1: แท่งเทียน + SuperTrend (เขียวช่วงขาขึ้น แดงช่วงขาลง)
  fig.add_trace(go.Candlestick(x=_d.index, open=_d['open'], high=_d['high'],
                               low=_d['low'], close=_d['close'], showlegend=False), row=1, col=1)
  _stu = _st.where(_dir == 1); _std = _st.where(_dir == -1)
  fig.add_trace(go.Scatter(x=_d.index, y=_stu, name='SuperTrend ขาขึ้น',
                           line=dict(color='green', width=2)), row=1, col=1)
  fig.add_trace(go.Scatter(x=_d.index, y=_std, name='SuperTrend ขาลง',
                           line=dict(color='red', width=2)), row=1, col=1)

  # โซน FVG ขาขึ้นที่ยังไม่ถูกปิด (ฟ้า) + Order Block ขาขึ้น (เหลือง)
  for _z in [_z for _z in _smc['fvg_bull'] if not _z[3]][-4:]:
    if _z[2] >= _n0:
      fig.add_shape(type='rect', x0=_d.index[_z[2]-_n0], x1=_x1, y0=_z[1], y1=_z[0],
                    fillcolor='rgba(0,120,255,0.13)', line=dict(width=0), row=1, col=1)
  if _smc['ob_bull'] is not None and _smc['ob_bull'][2] >= _n0:
    _ob = _smc['ob_bull']
    fig.add_shape(type='rect', x0=_d.index[_ob[2]-_n0], x1=_x1, y0=_ob[1], y1=_ob[0],
                  fillcolor='rgba(255,180,0,0.20)', line=dict(width=0), row=1, col=1)

  # จุด BOS / CHoCH (ข้อความบนกราฟ ณ แท่งที่ทะลุ)
  for _ei, _en, _el in _smc['events']:
    if _ei >= _n0:
      _up = _en.endswith('up')
      fig.add_annotation(x=_d.index[_ei-_n0], y=_el, text=_en.replace('_up', '▲').replace('_down', '▼'),
                         showarrow=True, arrowhead=1, arrowsize=0.8, yshift=12 if _up else -12,
                         font=dict(size=10, color='green' if _up else 'red'), row=1, col=1)

  # แนวโครงสร้างล่าสุด
  if _smc['swing_high'] == _smc['swing_high']:
    fig.add_hline(y=_smc['swing_high'], line=dict(color='gray', width=1, dash='dot'), row=1, col=1)
  if _smc['swing_low'] == _smc['swing_low']:
    fig.add_hline(y=_smc['swing_low'], line=dict(color='gray', width=1, dash='dot'), row=1, col=1)

  # แถว 2: Squeeze Momentum (แท่งเขียว/แดงตามค่าบวกลบ, จุดบนเส้นศูนย์ = กำลังบีบ)
  _mcol = ['rgba(0,150,0,0.7)' if _v >= 0 else 'rgba(200,30,30,0.7)' for _v in _mom.fillna(0)]
  fig.add_trace(go.Bar(x=_d.index, y=_mom, marker_color=_mcol, showlegend=False), row=2, col=1)
  _sq_x = _d.index[_sqz_on.values]
  fig.add_trace(go.Scatter(x=_sq_x, y=[0]*len(_sq_x), mode='markers', name='กำลังบีบ',
                           marker=dict(color='black', size=5, symbol='circle')), row=2, col=1)

  # แถว 3: CVD สะสม + เส้นค่าเฉลี่ย 20 แท่ง
  fig.add_trace(go.Scatter(x=_d.index, y=_cvd, name='CVD (ประมาณ)',
                           line=dict(color='purple', width=2)), row=3, col=1)
  fig.add_trace(go.Scatter(x=_d.index, y=_cvd.rolling(20).mean(), name='CVD MA20',
                           line=dict(color='orange', width=1)), row=3, col=1)

  fig.update_xaxes(rangeslider_visible=False)
  fig.update_yaxes(title_text=_sym, row=1, col=1)
  fig.update_yaxes(title_text='SQZ mom', row=2, col=1)
  fig.update_yaxes(title_text='CVD', row=3, col=1)
  fig.update_layout(width=1600, height=900, hovermode='x unified',
                    title=_sym + '  |  SuperTrend(10,3) + SMC + Squeeze + CVD  |  '
                          + str(_d.index[-1].date()),
                    legend=dict(orientation='h', y=1.02, x=0))
  fig.show()

# ตัวอย่าง: ดูหุ้นคะแนน STRAT4 สูงสุด 1 ตัว
if len(StockL_df) and StockL_df['STRAT4_SCORE'].notna().any():
  _top1 = StockL_df.sort_values('STRAT4_SCORE', ascending=False)['Name'].iloc[0]
  graph_strat4(_top1)

https://www.ezyquant.com/

user 9360800
pass 0865035023

https://www2.globlex.co.th/mainpage.aspx